### ISSUE TITLE
Add error handling examples

### ISSUE THREAD

**Issue by Madumo** [redux-observable/redux-observable#10]
Hi,

I think it's not clear right now how to handle errors with this middleware. There is no example of it in the basic example nor the [medium article](https://medium.com/@benlesh/redux-observable-ec0b00d2eb52#.q4vzsxqdn).

Lets say I have this action creator:

``` js
function createRequestAction({request, success, failure, abort}, fetch) {
    return payload => actions => Rx.Observable
            .fromPromise(fetch(payload))
            .map(success)
            .takeUntil(actions.ofType(abort.toString()))
            .startWith(request());
}

const getUser = createRequestAction(userActions, fetchUser);

// ...
store.dispatch(getUser({id: 123}));
```

If the promise returned by fetchUser fail, it will just throw an error and I don't see any way to handle it in a proper RxJS fashion. In RxJS v4 there was a catch method, but now there isn't. How should i properly dispatch the failure error when the request fail?

**Comment by jayphelps** [comment]
[`catch` does actually exist in rxjs v5](https://github.com/ReactiveX/rxjs/blob/56a12baa39dea4cfaf41bb5b04f5c0feca733b85/src/add/operator/catch.ts). `import 'rxjs/add/operator/catch';`

Here's an (untested) example:
```js

const fetchUser = (userId) => (
  (actions, store) => (
    // Promises aren't truly cancelable, use Observable.ajax
    // unless you *really* need to consume a Promise
    Observable.ajax(`/api/users/${userId}`)
      .map(payload => ({ type: 'FETCH_USER_FULFILLED', payload }))
      .takeUntil(actions.ofType('FETCH_USER_ABORTED'))
      // If the ajax request errors, we'll catch it and instead emit an "FETCH_USER_ERRORED" action
      // with the error info, your reducer would then be responsible for return the correct state accordingly
      .catch(error => Observable.of({ type: 'FETCH_USER_ERRORED', error }))
      .startWith({ type: 'FETCH_USER_PENDING' });
  )
);
```

There's also `onErrorResumeNext`, which was just [recently added](https://github.com/ReactiveX/rxjs/pull/1679) in rxjs@v5 master, it isn't yet in any beta release.

We do need to add usage examples for this here, I agree. I'm going to be adding a real API to the examples so we can do real `Observable.ajax()` and demo error handling too.

**Comment by istarkov** [comment]
Want to say about `fetchUser` and similar flows there we have `BLBLA_PENDING` actions.
There is some problem with `unsubscribe`.

If this action is attached using HOC like yours [dispatchOnMount](https://github.com/redux-observable/react-redux-observable/blob/master/src/dispatchOnMount.js) and then on Component unmount, `unsubscribe` will stop flow execution, you can get `PENDING` state in redux.

Now to solve this I use something like `.finally(() => store.dispatch({type: CLEAR_PENDING}))` but even I'm `rxjs` newcomer this does not look like `rx` way ;-)

Writing every time some action before `unsubscribe` from Component also does not look as a good solution.

Any thoughts?

**Comment by IanVS** [comment]
Returning an observable in a `.catch` seems to correctly dispatch the action, however I'm running into trouble from `Observable.fromPromise` (which I am using to wrap a jQuery ajax call.  Specifically, it is throwing an error of `Uncaught undefined` from https://github.com/ReactiveX/rxjs/blob/33d559d7fde1ce6caee4f0f56d283293788b362b/src/observable/PromiseObservable.ts#L78 (the rationale for which seems to be for handling errors thrown from a subscriber's `onNext`: https://github.com/Reactive-Extensions/RxJS/issues/925).

It seems that RxJS should check that `err` is not undefined in its uncaught error trap before throwing it, since it might be handled in the observable (as we're doing here).  I'm happy to open an issue at RxJS if you agree.

**Comment by SethDavenport** [comment]
I'm trying to understand error handling in the context of an epic:

```typescript
loginEpic = (action$: ActionsObservable) => {
    return action$.ofType(SessionActions.LOGIN_USER)
      .flatMap(({payload}) => http.post(`${BASE_URL}/auth/login`, payload))
      .map(result => ({
        type: SessionActions.LOGIN_USER_SUCCESS,
        payload: result.json().meta
      }))
      .catch(error => Observable.of({
        type: SessionActions.LOGIN_USER_ERROR
      }));
  }
```

This works great the first time the epic is triggered (by dispatching the LOGIN_USER action). If the command succeeds, you can even dispatch it several times.

However in the failure case, once the error is caught, the `action$` stream is finished and I can't retry because this epic no longer appears to be listening.

Do you have any advice? What I think I need is a way to handle an error in the stream and then continue the subscription to the original stream.

**Comment by matthewwithanm** [comment]
One way to get what you want is to do `.flatMap(action => post().map().catch())` instead of `.flatMap(action => post()).map().catch()`.

**Comment by r-park** [comment]
Assuming http.post returns an observable, might this work:
```js
loginEpic = (action$: ActionsObservable) => {
  return action$.ofType(SessionActions.LOGIN_USER)
    .switchMap(({payload}) => http.post(`${BASE_URL}/auth/login`, payload)
      .map(result => ({
        type: SessionActions.LOGIN_USER_SUCCESS,
        payload: result.json().meta
      }))
      .catch(error => Observable.of({
        type: SessionActions.LOGIN_USER_ERROR
      }))
    );
}
```

**Comment by SethDavenport** [comment]
Thanks - yes `http.post` does return an observable (this is in the context of an angular2 project).

Turns out this works too:

```typescript
  login = (action$: ActionsObservable) => {
    return action$.ofType(SessionActions.LOGIN_USER)
      .flatMap(({payload}) => this.http.post(`${BASE_URL}/auth/login`, payload))
      .map(result => ({
        type: SessionActions.LOGIN_USER_SUCCESS,
        payload: result.json().meta
      }))
      .retry(error => Observable.of({
        type: SessionActions.LOGIN_USER_ERROR
      }));
  }
```

(using `retry` instead of `catch`).

**Comment by jayphelps** [comment]
@SethDavenport hmmm AFAIK `.retry()` doesn't accept a function like that (only a number of retry attempts). Not sure how that's working 😆 

You want to catch the error from the the ajax observable to not let it propagate up to the outermost one.

http://jsbin.com/boqaso/edit?js,output

````js
const fetchBadURLEpic = action$ =>
  action$.ofType(FETCH_BAD_URL)
    .flatMap(action =>
      Observable.ajax('http://example.com/i-will-fail')
        .mapTo({ type: FETCH_BAD_URL_FULFILLED })
        .catch(error => Observable.of({
          type: FETCH_BAD_URL_REJECTED,
          payload: error,
          error: true
        }))
    );
```

**Comment by SethDavenport** [comment]
You're right - I need to sleep

**Comment by jayphelps** [comment]
@SethDavenport if at all possible, we would love-you-long-time if you find the time to create a basic angular project that uses redux-observable. Doesn't need to be fancy--just a basic hello world style and we can figure out the rest and add documentation and examples for it. We're working on React and Ember ones since we're more familiar with them. If not, seriously no worries. We'd love more Angular users to keep this project framework agnostic and not create an echo chamber of React features.

**Comment by SethDavenport** [comment]
Funny you should mention that - I was initially messing around with this as part of some documentation work for ng2-redux: https://github.com/angular-redux/ng2-redux/pull/159

I'm planning to update my company's ng2 starter project with this approach but I haven't quite finished yet (https://github.com/rangle/angular2-redux-starter).  I'll ping you when I do.

**Comment by jayphelps** [comment]
@SethDavenport HUGE THANK YOU! <3

**Comment by SethDavenport** [comment]
Of course - thanks for a very useful middleware, and double thanks for including typings :)

At ng2-redux we're trying to put together a coherent set of patterns that work well with Angular2's emphasis on classes, DI, and Observables, while at the same time remaining compatible with most of the redux middleware community.

We needed an RxJS answer for saga-style side effects and this really fits the bill. Being able to integrate a pattern like this without changing a line of code reinforces my belief that sticking with stock Redux was the right call for us.

**Comment by jayphelps** [comment]
@SethDavenport That's incredibly great to hear. I tweeted something related today 
> You *can* implement redux with RxJS instead, but is there a strong reason? They have strong community, dev tools, lots of middleware, etc.
> 
> https://twitter.com/_jayphelps/status/754092387144638464

**Comment by matthewwithanm** [comment]
What about global error handling? (e.g. log any uncaught epic errors)

**Comment by jayphelps** [comment]
@matthewwithanm Depends on whether you want the Epics that errored to resume listening for actions. If yes, this works:

http://jsbin.com/wubeqa/edit?js,output

```js
const rootEpic = (action$, store) =>
  combineEpics(firstEpic, secondEpic)(action$, store)
    .catch((error, stream) => {
      console.error('ERROR: ', error, stream);
      // resume with the errored observable instead of just terminating
      return stream;
    });
```

If you wish to just let things terminate, you'd use `.do()`:

```js
const rootEpic = (action$, store) =>
  combineEpics(firstEpic, secondEpic)(action$, store)
    .do({
      error: error => console.error('ERROR: ', error)
    });
```

Composition is one of the major reasons we chose this pattern. Because an uncaught exception will cause the entire stream to terminate, we've considered making the first example effectively the default of what the middleware does--so that all Epics are not impacted. But this is potentially too opinionated, so at the very least we should mention and document this pattern.

**Comment by jayphelps** [comment]
@matthewwithanm btw, if you want to still emit something that looks fairly close to how a real uncaught error looks like (stack trace and all that)

In Chrome, this works:

```js
console.error('Uncaught', error.stack);
```

Updated my above comment to reflect.

**Comment by skoch-fixeads** [comment]
Exists others approaches to handler exceptions on AJAX request like this?


`let Ob = Rx.Observable;

const source = Ob
  .of('ASYNC_ACTION')
  .switchMap( (action) =>
     Ob.of('ASYNC_FETCH')
       .switchMap(() => Rx.Observable.throw(400))
       .catch(e => 
         Ob.merge(
            Ob.of(e).filter(er => console.log(er)),
            Ob.of(e).filter(er => er === 401)
              .mergeAll(
                Ob.of('hide spin 401'),
                Ob.of('change state 401'),
                Ob.of('show message error 401')
              ),
             Ob.of(e).filter(er => er === 404)
              .mergeAll(
                Ob.of('hide spin 404'),
                Ob.of('change state of 404'),
                Ob.of('show message error 404')
              ),
             Ob.merge(
                Ob.of('hide spin general'),
                Ob.of('show general error message')
              )
        
         )
       )
  )
source.subscribe(
  a => console.log(a),
  e => console.log('error:' + e.message )
);
//hide spin general
//show general error message
`

**Comment by skoch-fixeads** [comment]
Exist some way to do something like this? catch specific error and handler multiples actions?

```

let Ob = Rx.Observable;

const source = Ob
  .of('ASYNC_ACTION')
  .switchMap( (action) =>
     Ob.of('ASYNC_FETCH')
       .switchMap(() => Rx.Observable.throw(401))
       .catch(e => 
         Ob.merge(
            Ob.of(e).filter(er => er === 401)
              .mergeAll(
                Ob.of('hide spin 401'),
                Ob.of('change state 401'),
                Ob.of('show message error 401')
              ),
             Ob.of(e).filter(er => er === 404)
              .mergeAll(
                Ob.of('hide spin 404'),
                Ob.of('change state of 404'),
                Ob.of('show message error 404')
              ),
             Ob.merge(
                Ob.of('hide spin general'),
                Ob.of('show general error message')
              )
         )
       )
  )
 
  
     

source.subscribe(
  a => console.log(a),
  e => console.log('error:' + e )
);


```

**Comment by stvkoch** [comment]
the problem here rising that defaultIfEmpty only accept one scalar argument...
I want operator some like defaultOfIfEmpty(Ob.of(...))

Important part it's **_complete method**

```
import { Operator } from '../Operator';
import { Observable } from '../Observable';
import { Subscriber } from '../Subscriber';

/* tslint:disable:max-line-length */
export function defaultOfIfEmpty<T>(this: Observable<T>, defaultSource?: T): Observable<T>;
export function defaultOfIfEmpty<T, R>(this: Observable<T>, defaultSource?: R): Observable<T | R>;
/* tslint:disable:max-line-length */

/**
 * Subscribe to defaultSource when source Observable completes without emitting any
 * `next` value, otherwise mirrors the source Observable.
 *
 * `defaultOfIfEmpty` emits the values emitted by the source Observable or subscribe to defaultSource and emits values of defaultSource on source Observable if the source Observable
 * is empty (completes without having emitted any `next` value).
 *
 */
export function defaultOfIfEmpty<T, R>(this: Observable<T>, defaultSource: R = null): Observable<T | R> {
  return this.lift(new DefaultIfEmptyOperator(defaultSource));
}

class DefaultIfEmptyOperator<T, R> implements Operator<T, T | R> {

  constructor(private defaultSource: R) {
  }

  call(subscriber: Subscriber<T | R>, source: any): any {
    return source.subscribe(new DefaultOfIfEmptySubscriber(subscriber, this.defaultSource));
  }
}

/**
 * We need this JSDoc comment for affecting ESDoc.
 * @ignore
 * @extends {Ignored}
 */
class DefaultOfIfEmptySubscriber<T, R> extends Subscriber<T> {
  private isEmpty: boolean = true;

  constructor(destination: Subscriber<T | R>, private defaultSource: R) {
    super(destination);
  }

  protected _next(value: T): void {
    this.isEmpty = false;
    this.destination.next(value);
  }

  protected _complete(): void {
    if (this.isEmpty) {
      this.defaultSource.subscribe(x => this.destination.next(x));
    }
    this.destination.complete();
  }
}

```

**Comment by anwarhamr** [comment]
Has anyone seen this or am I setting something up wrong? 
`TypeError: action$.ofType(...).do(...).concatMap(...).map(...).catch is not a function`
here is the test:
```
import { ActionsObservable } from 'redux-observable';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/toArray';

test('epilogV0x should ask for missing page',async ()=>{
 ...
  const action$ = ActionsObservable.of(
    testData
  );

  //do the test
  epilog0x_handleMissingPagesAndEvents(action$, store, {log})
    .toArray()
    .subscribe(
      actualOutputActions => {
        expect(actualOutputActions).toMatchObject(expectedOutputActions);
      error=>console.log(error)
    );
});

```

and my epic is this:
```
export const epilog0x_handleMissingPagesAndEvents = (action$,store,{bleCommunicator,log})=>
  // every time we get data try to get missing page data too.
  action$
    .do(action=>console.log("you're doing it dude!"))
    .catch(error => {
      log.info(firmwareVersion+' readChar error',error);
      return Observable.of({type:'ERROR',erro:`epilog0x_handleMissingPagesAndEvents exception: ${error}`});
    });
```

**Comment by jayphelps** [comment]
@anwarhamr the error suggests you need to add the catch operator to Observable via import. It also doesn't appear related to your test. My best guess is that it works in your app because you probably import the catch operator somewhere else so it just happens to work. If that doesn't solve the issue you might be able to find help on [gitter channel](https://gitter.im/redux-observable/redux-observable_ or on [StackOverflow](https://stackoverflow.com/questions/tagged/redux-observable0

**Comment by anwarhamr** [comment]
@jayphelps it was the include missing, thank you for the quick response!
 I just got back on this code from a few weeks down... how fast I forget all the hoops ;)  
The chain was from my real impl of the epic but the example given above was updated for brevity

**Comment by Madumo** [comment]
At the time i opened this issue, if i remember correctly, there was a lot less documentation, examples, and public knowledge about this library and RxJS v5. Now [there is good documentation](https://redux-observable.js.org/docs/recipes/ErrorHandling.html), and you can find a lot of examples on the web.

I don't feel this issue should stay open, as it's turning into a stackoverflow post.
