### ISSUE TITLE
UMD export not working properly with System.js

### ISSUE THREAD

**Issue by blesh** [redux-observable/redux-observable#126]
Specifically, if you look at the [third and sixth lines in the current umd file](https://unpkg.com/redux-observable@0.12.0/dist/redux-observable.js)

You'll notice it's requiring `undefined`.

```js
module.exports = factory(require(undefined), require(undefined), require(undefined));
```

```js
exports["ReduxObservable"] = factory(require(undefined), require(undefined), require(undefined));
```

**Comment by jayphelps** [comment]
Fairly confident the issue is that we're using https://github.com/jayphelps/webpack-rxjs-externals to generate the externals for RxJS but that lib is only outputting the `root` prop. It needs to output:
`root`, `commonjs2`, `commonjs`, and `amd` too.

I'm on it.
