### ISSUE TITLE
react native problem (exact same architecture produces error:Actions must be plain objects.use custom middleware for async actions)

### ISSUE THREAD

**Issue by kordeviant** [redux-observable/redux-observable#141]
```
export function fetchPopularRepos(action$) {
  return action$.ofType('FETCH_REPOS')
    .switchMap(() =>
      Observable.ajax.getJSON('https://api.github.com/users')
        .map(data => {
             console.log(data)
        })
    );
}


```
this works perfectly on web but on react native , as soon as ajax call tries to map result to .map produces error. thunk and epicmiddleware are applied correctly. react native thinks that my action is not plain object when redux observable is listening on it.
![screenshot_1478109641](https://cloud.githubusercontent.com/assets/22198402/19941019/c78bc13c-a143-11e6-8e4a-8169de60cc5f.png)

**Comment by kordeviant** [comment]
![screenshot_1478109641](https://cloud.githubusercontent.com/assets/22198402/19940994/b7819118-a143-11e6-91d6-d256a7d653b5.png)

**Comment by rgbkrk** [comment]
That final map:

```
        .map(data => {
             console.log(data)
        })
```

it needs to return an action

**Comment by kordeviant** [comment]
thanks! really!
