### ISSUE TITLE
"Using React" JSBin example broken

### ISSUE THREAD

**Issue by alukach** [redux-observable/redux-observable#143]
I'm looking at the [Using React JSBin example](http://jsbin.com/jexomi/edit?js,console,output) mentioned in the README.md, however it appears to be incomplete/broken.  The beginning portion sets up some actions around Search, however the actual Component addresses some tooling around `ping` and `isPinging`.  Attempting to run the code brings up an error of `"ReferenceError: ping is not defined`.

At time of writing, this is the example:

```javascript
/**
 * IMPORTANT ***************************************************************
 * 
 * This example uses the global version of RxJS that includes ALL operators.
 * Inside your app, you will likely need to import the operators you use or
 * import all of them in your index.js entry file.
 * 
 * Learn more about this: http://goo.gl/4ZlYeC
 */

console.clear();

const SEARCH_DEBOUNCED = 'SEARCH_DEBOUNCED';
const SEARCH = 'SEARCH';

const searchDebounced = () => ({ type: SEARCH_DEBOUNCED });
const search = payload => ({ type: SEARCH, payload });
const searchFulfilled = payload => ({ type: SEARCH_FULFILLED, payload });

const searchDebouncedEpic = action$ =>
  action$.ofType(SEARCH_DEBOUNCED)
    .debounceTime(500)
    .switchMap(action =>
      Observable.ajax.getJSON(`https://api.github.com/users/${action.payload}`)
        .map(response => searchFulfilled(response))
    )

const users = (state = {}, action) => {
  switch (action.type) {
    case SEARCH_FULFILLED:
      return {
        ...state,
        // `login` is the username
        [action.payload.login]: action.payload
      };

    default:
      return state;
  }
};

// components/App.js

const { connect } = ReactRedux;

let App = ({ isPinging, ping }) => (
  <div>
    <h1>is pinging: {isPinging.toString()}</h1>
    <button onClick={ping}>Start PING</button>
  </div>
);

App = connect(
  ({ isPinging }) => ({ isPinging }),
  { ping }
)(App);

// redux/configureStore.js

const { Provider } = ReactRedux;
const { createStore, applyMiddleware } = Redux;
const { createEpicMiddleware } = ReduxObservable;

const epicMiddleware = createEpicMiddleware(pingEpic);

const store = createStore(pingReducer,
  applyMiddleware(epicMiddleware)
);

// index.js

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
);
```

**Comment by jayphelps** [comment]
Whoops! sorry about that. Fixed now. It was supposed to be the ping/pong example but I unintentionally edited that jsbin.

**Comment by jayphelps** [comment]
Thanks very much for reporting!

**Comment by alukach** [comment]
Thanks for the quick reply! Looks like the same JSBin is referenced in https://github.com/redux-observable/redux-observable/issues/112. As someone getting their feet wet with this library, it's super valuable to have a set of examples available, perhaps each example should be a fork of the JSBin mentioned in this Issue so that they can represent a single concept snapshot from a given time? (Or maybe this is already the pattern but there were just a few slip-ups along the way)

ps, thanks for the great work on this library so far, the concept is excellent and the thorough documentation and Netflix talk really make on boarding a smooth process!
