### ISSUE TITLE
Please update to rxjs version 5.0.0-rc.4 

### ISSUE THREAD

**Issue by xaviercobain88** [redux-observable/redux-observable#152]
Please update to rxjs version 5.0.0-rc.4 because of this known issue with observables and react native:
https://github.com/facebook/react-native/issues/6063
Seems like with new rxjs version works fine
Thnx

**Comment by jayphelps** [comment]
You shouldn't need us to update anything on our end for you to be able to use any 5.x.x version? Have you tried?

**Comment by latamautos** [comment]
you mean  `npm shrinkwrap`? I'm going to try it with 5.0.0-rc.4 version overriding the actual rxjs dependency version

**Comment by xaviercobain88** [comment]
you mean npm shrinkwrap? I'm going to try it with 5.0.0-rc.4 version overriding the actual rxjs dependency version

**Comment by jayphelps** [comment]
Not shrinkwap--you just use regular npm install dependencies. redux-observable uses peer dependencies so you have to install RxJS and can install any version of v5.

**Comment by jayphelps** [comment]
Have you tried just `npm install --save rxjs@5.0.0-rc.4` ? That should work--we intended to let people upgrade their rxjs independently of redux-observable, with the only restriction being that it's in the 5.x.x range.

**Comment by xaviercobain88** [comment]
Cool! thnx

**Comment by jayphelps** [comment]
Let me know if that doesn't work! 😄

**Comment by grahamp** [comment]
I am getting the error with 
"rxjs": "^5.0.0-rc.4"

I get the following error message if I try and include that module version:

> _node_modules/rxjs/symbol/iterator.js: Property left of AssignmentExpression expected node to be of a type [\"LVal\"] but instead got \"ConditionalExpression\"","type":"TransformError","errors":[{}]}_

**Comment by xaviercobain88** [comment]
facebook/react-native#6063 more details about the issue

**Comment by jayphelps** [comment]
@grahamp sounds unrelated to redux-observable. Sounds similar to https://github.com/facebook/react-native/issues/6063. Feel free to post an issue on rxjs's repo, but you'll need to include a lot more details like whether this is TypeScript, what build pipeline, very *for sure* that the version inside your node_modules directory is `5.0.0-rc.4` (`rm -rf node_modules && npm install` to be **sure**)

**Comment by grahamp** [comment]
@jayphelps, Thanks so much for the help! I will try and get a full bug report together for the  rxjs repro, I am a little new to react-native so I could be missing something. I have a deadline so I will find another solution for now. 

Just FYI:  I do have the babel.rc with  "presets": [ "react-native"],
 I did delete all my modules, killed and restarted NPM, cleared the cache and updated my global modules.  And here is my package.json 
{
  "name": "installerapp",
  "version": "1.2.1",
  "description": "Device installer application for users.",
  "private": true,
  "repository": {
    "type": "git",
    "url": "git+https://github.com/nauto/installer-app.git"
  },
  "author": "Graham Poor",
  "license": "ISC",
  "scripts": {
    "preinstall": "rm -rf typings",
    "postinstall": "node node_modules/typings/dist/bin.js install",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "adb reverse tcp:8081 tcp:8081 && node node_modules/react-native/local-cli/cli.js run-android",
    "ios": "node node_modules/react-native/local-cli/cli.js run-ios",
    "prebuild": "rm -rf build",
    "build": "tsc",
    "lint": "eslint src/**",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-react-native"
  },
  "dependencies": {
    "crypto-js": "^3.1.8",
    "immutable": "^3.8.1",
    "lodash": "^4.17.2",
    "react": "15.4.1",
    "react-native": "0.38.0",
    "react-native-barcodescanner": "^3.1.1",
    "react-native-button": "^1.7.1",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-drawer": "^2.3.0",
    "react-native-lock": "^0.4.0",
    "react-native-material-design": "^0.3.7",
    "react-native-material-kit": "^0.3.3",
    "react-native-orientation": "^1.17.0",
    "react-native-scrollable-tab-view": "^0.7.0",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "redux-observable": "^0.12.2",
    "redux-promise": "^0.5.3",
    "redux-promise-middleware": "^4.2.0",
    "redux-storage": "^4.1.1",
    "redux-storage-engine-reactnativeasyncstorage": "^1.0.2",
    "redux-thunk": "^2.1.0",
    "rxjs": "^5.0.0-rc.4",
    "tcomb-form-native": "^0.6.1",
    "typescript": "^2.0.10",
    "typings": "^2.0.0"
  },
  "devDependencies": {
    "@types/react": "^0.14.51",
    "@types/react-dom": "^0.14.19",
    "babel-eslint": "^7.1.1",
    "babel-jest": "^17.0.2",
    "babel-preset-react-native": "^1.9.0",
    "eslint": "^3.1.1",
    "eslint-config-standard": "^5.3.5",
    "eslint-plugin-promise": "^2.0.0",
    "eslint-plugin-react": "^5.2.2",
    "eslint-plugin-react-native": "^1.2.0",
    "eslint-plugin-standard": "^2.0.0",
    "jest": "^17.0.3",
    "jest-react-native": "^17.1.0",
    "react-test-renderer": "^15.3.0",
    "redux-devtools": "^3.2.0",
    "tslint": "^4.0.2",
    "typescript": "^2.0.10",
    "typings": "^2.0"
  },
  "bugs": {
    "url": "https://github.com/nauto/installer-app/issues"
  },
  "homepage": "https://github.com/nauto/installer-app#readme",
  "main": ".eslintrc.js"
}

**Comment by SamMatthewsIsACommonName** [comment]
@grahamp  I'm having the same error did you get it solved?
