### ISSUE TITLE
[Feature request] Inject dependencies in epics

### ISSUE THREAD

**Issue by AugustinLF** [redux-observable/redux-observable#163]
In my app when I don't use redux-observable, I use a variant of redux-thunk that lets me inject dependencies in my actions (see how it is used in this [action](https://github.com/este/este/blob/master/src/common/todos/actions.js#L5)), it's also something made possible by the [redux-inject](https://www.npmjs.com/package/redux-inject) middleware. This lets me have efficient DI in my actions, depencencies set up at the store creation. However, redux-observable doesn't provide such an API.

For instance, it would work like that
```javascript
const store = createStore(
  rootReducer,
  applyMiddleware(epicMiddleware, dependencies),
);
```

Would that be something you would be interested? If so, I'd gladly work on a PR.

**Comment by jayphelps** [comment]
Are you wanting to inject things into the **actions** themselves or inject things into your **epics**? 

I feel pretty confident we won't support injecting things into the actions themselves--it's really outside the scope of redux-observable and easily done with other middleware you would in addition.

For injecting dependencies into the epics, this is already supported as a pattern, but no first-class API exists for it yet. See #115

``` js
// given epics like this
const epic1 = (action$, store, api) => {
  // access to API here!
};
```

``` js
import * as api from './api/location';

// inject API into all epics as third arg
const rootEpic = (...args) => combineEpics(epic1, epic2)(...args, api);
```

which makes it easier to test:

``` js
const fakeApi = {
  fetchSomething: () => Observable.of('fake response')
};
epic1(action$, fakeStore, fakeApi);
```

**Comment by AugustinLF** [comment]
Thanks for your answer, I indeed meant injecting things into the epics! I didn't think of your workaround, that would do the job, great :)

But your proposal is what I had in mind.

**Comment by bali182** [comment]
If this is implemented, how would additional arguments be handled? Would the config objects `dependencies` field simply overtake the role of passing more stuff into epics or would the current way of passing arguments kept, and dependencies passed after what is currently passed?

**Comment by jayphelps** [comment]
@bali182 if you mean would this replace

```js
const rootEpic = (...args) => combineEpics(epic1, epic2)(...args, api);
```

yes, it would. You could still do this, but it would be bumped to the fourth arg position instead of the third, as the third would be anything injected using the `dependencies` option. If you don't inject anything using `dependencies`, I'm not sure if we would choose to either force `null` or `undefined`, or just not pass anything at all, freeing up that parameter position.

The primary reason I haven't added this is that I've been hesitant to lay claim on that parameter position, cause I wasn't sure if we would need it for something more important. But it's been over a year and I'm pretty happy with the status quo, so adding this before 1.0 seems like a good idea. (along with a testing docs overhaul with learnings)

**Comment by bali182** [comment]
@jayphelps Great, that's good news! So `dependencies` will be a single value passed in epics at a fixed argument position? The example with `{ dependencies: [api] }` gave me the impression, that you want to pass this spread style as well (thinking of the array) but I like the single-value-at-fixed-position version much better. You can always pass an object and destructure in the epic this way, and it's harder to shoot yourself in the foot by messing with argument order.

**Comment by jayphelps** [comment]
@bali182 oh I misunderstood cause I forgot that I proposed an array of dependencies.

I'm leaning instead towards `{ dependencies: someobject }` which then `someobject` which be passed as-is as the third argument, no spreading--which I think is what you want as well.

```js
createEpicMiddleware(rootEpic, { dependencies: api });

// later

const epic1 = (action$, store, api) => {
  // access to API here!
};
```

Or you can do other things like this:

```js
createEpicMiddleware(rootEpic, { dependencies: { api, somethingelse } });

// later

const epic1 = (action$, store, { api, somethingelse }) => {
  // access to API and somethingelse 
};
```

**Comment by bali182** [comment]
Yes this sounds perfect in my opinion. Also not much work  to migrate if someone was relying on the extra arguments.
