### ISSUE TITLE
Documentation is missing essential detail in ajax example

### ISSUE THREAD

**Issue by srigi** [redux-observable/redux-observable#176]
As a beginner I started to code examples from official documentation. In *[A Real World Example](https://redux-observable.js.org/docs/basics/Epics.html#a-real-world-example)* there is used the `ajax` object. But very essential piece is missing - from where this identifier comes from. It is very hard to find this information, so please add it there. Beginners will be thankfull.

BTW it is:
```
import { ajax } from 'rxjs/observable/dom/ajax';
```

**Comment by jayphelps** [comment]
Definitely should be added.

It was excluded mostly because we don't want to take an opinion on how you should import your operators. _But_, this one is different cause we don't use `Observable.ajax` so it's not clear where it comes from if you're not familiar.

**Comment by srigi** [comment]
Thanks for positive response. I can see that it is included in docs sources. Will this propagate to the web docs? I am asking on behalf of all people who may be strugling same as I was.

Good job anyway, thanks.

**Comment by jayphelps** [comment]
@srigi it's now live.
