### ISSUE TITLE
ability to combine epics from an array or object

### ISSUE THREAD

**Issue by b3bakyt** [redux-observable/redux-observable#179]
It would be handy to be able to combine Epics from an array or object of epics, for example:

```
import { combineEpics } from 'redux-observable';
import * as epics from './myListOfEpics';

export default combineEpics(epics);
```

in this case we might be able to generate epics dynamically.

**Comment by jayphelps** [comment]
Hey 👋 this is a duplicate of https://github.com/redux-observable/redux-observable/issues/58
