### ISSUE TITLE
Use with redux-promise

### ISSUE THREAD

**Issue by tomjmul** [redux-observable/redux-observable#181]
Don't know if this is a bug or a feature, but it is unexpected behaviour. When I dispatch a promise to the store using redux-promise, my epic gets invoked twice. Once with the promise object itself and then later with the resolved value.

**Comment by istarkov** [comment]
redux-promise dispatches the paylod on promise resolve, so you have two action, the action with promise and the action with promise result. Having that redux-observable intercepts all actions it is expected behavior

**Comment by jayphelps** [comment]
Expected behavior if you placed redux-observable middleware before your redux-promise middleware. Reverse the order if you want redux-promise to intercept your dispatched promise before it reaches redux-observable. Regular POJO actions that your promise emits would still reach.

**Comment by tomjmul** [comment]
That thought had just occurred to me now as I've started getting my head around things; I came back here to respond and close the issue. Thanks for your replies.
