### ISSUE TITLE
epic timeout functionality with takeuntil

### ISSUE THREAD

**Issue by lucib** [redux-observable/redux-observable#184]
hey,

i want to implement a timeout functionality with takeUntil and i'm getting strange error
the example is based on the example found here (https://medium.com/@markusctz/action-streams-and-redux-77f8ac99c2e9#.nn2495jrx)

```js
fetchDashboardCurrentUserTiles_ = (action$: ActionsObservable<any>) => {

    let url = this.apiEndpoint + '/User/tiles';
    return action$.ofType(DashboardActions.FETCH_CURRENT_USER_TILES_)
      .flatMap(({payload}) => {
        const dashboardResponse$ = this.authService.AuthGet(url)
          .map(result => (
            {
              type: DashboardActions.FETCH_CURRENT_USER_TILES_SUCCESS_,
              payload: result.json()
            }
          ));
          // Trigger a timeout action
          const timeout$ = of({ type: 'TIMEOUT', payload})
          // But only after 15s
          .delay(15000);
          return merge(
            // Cancel the publish if it times out
            dashboardResponse$.takeUntil(timeout$),
            // Cancel the timeout if the response comes back in time
            timeout$.takeUntil(dashboardResponse$)
          );
      });
  }
```

i'm getting 
```
Cannot read property 'toLowerCase' of undefined
   at Headers.has (headers.js:121)
    at Headers.getAll (headers.js:168)
    at Headers.append (headers.js:78)
    at AuthService._setRequestOptions (auth.service.ts:193)
    at MergeMapSubscriber.project (auth.service.ts:127)
    at MergeMapSubscriber._tryNext (mergeMap.js:120)
    at MergeMapSubscriber._next (mergeMap.js:110)
    at MergeMapSubscriber.Subscriber.next (Subscriber.js:89)
    at PromiseObservable.js:66
    at ZoneDelegate.invoke (zone.js:242)
    at Object.onInvoke (ng_zone.js:271)
    at ZoneDelegate.invoke (zone.js:241)
    at Zone.run (zone.js:113)
    at zone.js:535
    at ZoneDelegate.invokeTask (zone.js:275)
```
and 

Warnings while compiling.
```
client?93b6:90 ./~/rxjs/observable/of.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\node_modules\rxjs\Observable\of.js
    Used by 1 module(s), i. e.
```

if i comment out timeout$.takeUntil(dashboardResponse$)
i receive only warning not errors

is this the correct way to have a timeout functionality ?

**Comment by jayphelps** [comment]
Hey, have you tried our [Gitter](https://gitter.im/redux-observable/redux-observable) or [StackOverflow](stackoverflow.com/questions/tagged/redux-observable)? We try to keep issues for bugs caused by redux-observable.

**Comment by jayphelps** [comment]
Your warnings are almost certainly unrelated--they sound like a Windows thing with webpack or node, if I had to take a guess. _Maybe_ related to rxjs (not redux-observable) having `rxjs/observable/` directory and `rxjs/Observable.js` file, but I've never heard of these warnings from any of the folks I know on Windows that use RxJS. Some google searching reveals other people have had similar warnings with other files.

Regarding the error at hand, the error is happening at `Headers.has (headers.js:121)`. Where some code is calling `.toLowerCase()` on some variable that has an undefined value. Use your debugger to pause on that section of the code (or on uncaught exceptions) and walk the stack back to find out why it's undefined for you.
