### ISSUE TITLE
Proposal: ofType should be abstracted out as a separate operator.

### ISSUE THREAD

**Issue by jshthornton** [redux-observable/redux-observable#185]
`ofType` is just an operator function. I propose that we move it out into a separate module which `ActionObservable` can then utilise. Eventually I would suggest that `ofType` being on `ActionObservable` should be removed all together.

The reasoning for this is that it will allow testing of epics to use standard Observables, which then permits the developers to write tests which can subscribe to the actions. An example test:

```
const actions$ = Observable.create(function(observer) {
  observer.next(actions.doSomething());
});

actions$.ofType = ofType;

const epicAction$ = epics.doSomething(actions$);

const subscribe = epicAction$.subscribe((action) => {

});
```

**Comment by jayphelps** [comment]
Hmm.. I'm OK exporting the operator by itself, but I'm pretty happy with the way ActionsObservable works right now. Did you know you can do this?

```js
import { ActionsObservable } from 'redux-observable';

const action$ = ActionsObservable.of(actions.doSomething());
epics.doSomething(actions$)
  .subscribe(action => { });

```

**Comment by jshthornton** [comment]
@jayphelps you can indeed do the example I gave via ActionsObservable. I am just proposing this to allow for flexibility if developers wish to do more crazy Observable creations during testing.

It would also be good to move out the ofType operator to make the API more consistent with rxjs. rxjs looks like it is favouring the bind syntax, so we should consider it too.

**Comment by jayphelps** [comment]
@jshthornton rxjs doesn't necessarily favor bind syntax, there's a high probability it won't get accepted by TC39 at this point. We don't make any suggestions on which method of usage is best, it depends on your project requirements.

**Comment by evertbouw** [comment]
RXJS 5.5 adds support for lettable operators. I think this should be supported by redux-observable as well. I made a quick version that seems to work: https://gist.github.com/evertbouw/e29b80cb686c4d15c0b202e14cb2ddbf

If something like this is added to the repo it would make sense to me to remove the ofType operator from the class.

**Comment by jayphelps** [comment]
#343 added `ofType` as a lettable operator. 🎉
