### ISSUE TITLE
[Feature request] Support for stringifyable action factories

### ISSUE THREAD

**Issue by thezanke** [redux-observable/redux-observable#192]
I think it would be immensely helpful if `action$.ofType()` knew how to handle stringifyable action factories like those that you see from redux-actions or redux-act. This is helpful for people who, following the guidance of the React docs, have picked up action creator factory libraries to reduce boilerplate. One of the major pieces of boilerplate these packages eliminate is the need to maintain a list of constants because all action factories have a `.toString()` method that return their type so they can be used as the action type as well as the action creator.

This would be easy to handle, especially since there is no reason for calling `ofType()` on a function as it is. The quickest way to implement this in this case would probably be just calling `String()` on `keys[i]` when comparing it against `type`.

This would allow for something like the following:
```
import { action1, action2 } from 'actions/bots';

export default (action$, store) =>
  action$.ofType(action1)
    .do(//something)
    .map(() => action2());
```

I'll whip up a quick PR.

**Comment by thezanke** [comment]
I just noticed that this has been discussed before and I just didn't see it when I looked (used wrong terms). The fear is breaking support for using symbols as a type. Could we just have a simple matcher that just tests if `typeof key[i] === 'function'` before calling `String()` or `.toString()` on it? This would really help clean up the need to use constants file and makes it so I don't have to wrap with `String()` myself every single time I use `ofType()`.

**Comment by jayphelps** [comment]
Hey @theengineear! Thanks for the ticket + PR--bringing code to the table is always super appreciated!!

> I just noticed that this has been discussed before

Yeah, just for posterity, it has previously been proposed in #71, then PR'd in #175

> Could we just have a simple matcher that just tests if typeof key[i] === 'function' before calling String() or .toString() on it? 

This idea seems promising. As long a test was added that showed Symbols were supported still too I think this is solid
