### ISSUE TITLE
Some promises do not get dispatched

### ISSUE THREAD

**Issue by MrHayato** [redux-observable/redux-observable#199]
**Do you want to request a *feature* or report a *bug*?**  Bug

This is the epic I currently have, simplified:

```
const s$ = action$
    .ofType('GET_STUFF_FROM_API')
    .switchMap(() =>
        Observable.concat(
            Observable.of({ type: 'BEGIN_FETCH' }),
            Observable.fromPromise(fetch('some_api'))
                .flatMap(result => Observable.concat([
                    {
                        type: 'SAVE_TO_STATE',
                        payload: result,
                    },
                    { type: 'FETCH_COMPLETE' },
                ]))
                .catch(err => Observable.of({ type: 'ERROR', payload: err })),
        )
    );

// For debugging. Everything is logged to console as expected!
s$.subscribe(
    x => console.log('Next:', x),
    err => console.log('Error:', err),
    () => console.log('Completed')
);

return s$;
```

**What is the current behavior?**

When I run this, the only actions that are dispatched are the `GET_STUFF_FROM_API` and `BEGIN_FETCH` actions. The `fetch` call happens successfully, and it returns the payload as I need it, but the SAVE_TO_STATE and FETCH_COMPLETE actions do not fire.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

**What is the expected behavior?**

I expect the SAVE_TO_STATE and FETCH_COMPLETE actions to fire when the api call is completed. I have tried to replace the `fetch('some_api')` with the following, and it also failed:
`Observable.fromPromise(new Promise((resolve, reject) => { setTimeout(() => resolve({ foo: 'bar' }), 2000); }))`
However, if I replace the promise with `Observable.fromPromise(Promise.resolve({ foo: 'bar' }))` then this works as expected! Likewise, if I use Promise.reject, the `ERROR` action occurs as expected.
Additionally, the `.subscribe` I've used for debugging logs out all the actions that I expect, in all use cases.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

This happens on Chrome, on 0.13.0. Have not tested on other browsers, never tried on older versions.

**Comment by MrHayato** [comment]
It is worth mentioning that this is with Bluebird promises.

**Comment by istarkov** [comment]
Seems like you are doing something wrong, outside the code you provide,
there are no errors in your example, and it works as expected
See the your example in action http://jsbin.com/kevetogaso/edit?js,console,output 
as you could see all actions are logged in `someReducer`

**Comment by MrHayato** [comment]
Yeah, it looks like there was something wrong with my setup. I cleared out my node_modules and reinstalled, and everything seems to be working again. No idea why. Thanks though!
