### ISSUE TITLE
react-native can not resolve rxjs module

### ISSUE THREAD

**Issue by craigcosmo** [redux-observable/redux-observable#200]
rxjs module can not resolve in react-native

**What is the current behavior?**
<img width="376" alt="screen shot 2017-02-18 at 4 22 00 pm" src="https://cloud.githubusercontent.com/assets/538657/23092120/8b7ea904-f5f6-11e6-9808-cd0cb52905ad.png">

**reproduce**
just create an epic like this, react-native will show blood

```js
import 'rxjs'

export default action$ =>
  action$.ofType('PING')
    .delay(1000)
    .mapTo({ type: 'PONG' })
```

**What is the expected behavior?**

It should resolve and no error

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

` "redux-observable": "^0.13.0",`

**Comment by craigcosmo** [comment]
To solve this, rxjs needs to be installed seperately like `npm i --save rxjs`.

The rxjs version that come bundled with redux-observable is not compatible with react-native. But latest version 5.0+ is.

**Comment by jayphelps** [comment]
FWIW the issue is technically redux-observable doesn't come with any version of RxJS at all. You have to install it separately, as you mentioned.
