### ISSUE TITLE
Docs: Bug in Real World AJAX Example

### ISSUE THREAD

**Issue by dthielman** [redux-observable/redux-observable#213]
I didn't find this in the issue tracker; if it turns out to be a duplicate, please let me know and I'll search more thoroughly in the future. 

**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
Docs: The example just below the section [A Real World Example](https://redux-observable.js.org/docs/basics/Epics.html#a-real-world-example) does not actually return the user info. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

The code is located [here](https://jsbin.com/jopuza/9/edit?js,output). Just click the `Fetch User Info` button and note that nothing changes. The typo between version [8](https://jsbin.com/jopuza/8/edit?js,output) and version [9](https://jsbin.com/jopuza/9/edit?js,output) appears to be that the response from the ajax call is not passed to the dispatched action. The current behavior errors as the code is trying to access a field on an undefined object.

**What is the expected behavior?**
The payload should be passed into the action, and the result should be visible. 

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
Just the docs.

Thanks! Very happy to have discovered this project.

**Comment by jayphelps** [comment]
Thank you so much for taking the time to report this and great details! I believe it's fixed now, can you confirm?

**Comment by dthielman** [comment]
Confirmed! If I follow the bin from the docs and execute the code, works like a charm. Thanks!
