### ISSUE TITLE
Cancellation jsbin example fix

### ISSUE THREAD

**Issue by betatim** [redux-observable/redux-observable#215]
The [JSBin example](https://jsbin.com/fivaca/7/edit) in https://redux-observable.js.org/docs/recipes/Cancellation.html# should be
```js
const fetchUserEpic = action$ =>
  action$.ofType(FETCH_USER)
    .mergeMap(action =>
      fakeAjax(`/api/users/${action.payload}`)
        // next line is different
        .map((x) => fetchUserFulfilled(x))
        .takeUntil(action$.ofType(FETCH_USER_CANCELLED))
    );
```
otherwise the example never shows the user info in the text area.

A modified jsbin: https://jsbin.com/kogedoyari/edit?js,output

**Comment by jayphelps** [comment]
Whoops! Thank you for noticing and letting us know! Fixed.
