### ISSUE TITLE
Error: Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by javico2609** [redux-observable/redux-observable#221]
**Do you want to request a *feature* or report a *bug*?**  bug

**What is the current behavior?**

if active middleware when use configureStore returned this error, if don't put into Redux.configureStore everything is ok but the documentation see they needed to initialize

Error: Actions must be plain objects. Use custom middleware for async actions.

```
export class AppModule {
  constructor(
    private ngRedux: NgRedux<IAppState>,
    private devTools: DevToolsExtension,
    private settingsService: ISettingsService) {
    let enhancer = isDevMode() ? [devTools.enhancer()] : [];

    const middleware = [
      createEpicMiddleware(this.settingsService.getTheme)
    ];

    ngRedux.configureStore(rootReducer, INITIAL_STATE, middleware, enhancer);
  }
}

//Service Injectable

 getTheme = store => next => (action: ActionsObservable<any>) => {
        Observable.fromPromise(this.storage.get(LocalStorageConstants.THEME_KEY))
            .map(theme => {
                return next({
                    type: ActionsConstants.UPDATE_THEME,
                    payload: (theme) ? theme : LocalStorageConstants.THEME_DEFAULT
                });
            })
    }
```

**What is the expected behavior?**

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

```
    "ng2-redux": "^5.1.2",
    "redux": "^3.6.0",
    "redux-observable": "^0.14.1",
```

**Comment by jayphelps** [comment]
It's not clear what you're doing. What is getTheme? It looks like a custom middleware, but the signature doesn't make sense to me `(action: ActionsObservable<any>)`.

**Comment by javico2609** [comment]
ok, thx for respond quickly, i fixed the problem using

 createEpicMiddleware(combineEpics(
        this.settingsService.getTheme
 ))

without using combineEpics return error

**Comment by jayphelps** [comment]
Sounds like issue was resolved.
