### ISSUE TITLE
 Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by craigcosmo** [redux-observable/redux-observable#227]
**adminAction**

```js
export function saveBook(data){
	return {
		type: 'save',
		payload: data
	}
}
```

**adminEpic**

```js
import request from 'request'
import 'rxjs'

export default action$ =>
action$.ofType('save')
	.mergeMap( 
		action =>
			request().post('http://mydomain.com/post', {data: action.payload})
			.map(response => console.log(response))
	)
// request().post() return a promise
```

**adminComponent**

```js
export default class AdminView extends React.Component {

	componentDidMount(){
		this.props.submitBook('hello')
	}
	render() {
		return (
			<div></div>
		)
	}
}
```

when the component mount,I got this error:

![screen shot 2017-03-27 at 4 48 28 pm](https://cloud.githubusercontent.com/assets/538657/24350664/3d148912-130d-11e7-92c5-0c9e2cfaf17c.png)

**Comment by craigcosmo** [comment]
I should've used fromPromise operator. rxjs always expect a stream.

**Comment by jayphelps** [comment]
Returning a promise in mergeMap does work, your problem is that you are not returning anything in your map below it where you console.log. Now your epic just emits `undefined`
