### ISSUE TITLE
Redux-observable conflict with React-redux-router

### ISSUE THREAD

**Issue by nhatkhoa** [redux-observable/redux-observable#229]
I got issue, redux-observable can dispatch mapTo action to redux.

`
  const epicMiddleware = createEpicMiddleware(getRootEpic)
  const middleware = [routerMiddleware(history), epicMiddleware]
  
  const store = createStore(
    makeRootReducer(),
    initialState,
    composeEnhancers(
      applyMiddleware(...middleware),
      ...enhancers
    )
  )
`

react-redux-router link : [https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux)

**Comment by jayphelps** [comment]
Hey @nhatkhoa, I'm not sure what you're asking? 🤔 

Both libraries work together, but judging from the code you included, one thing I see that might cause you issues is that you put the `routerMiddleware` _before_ the `epicMiddleware`. If you do that, then actions your epics emit won't be seen by the `routerMiddleware`.

Instead, reverse the order. Is that your issue?
