### ISSUE TITLE
Test: when the dispatch is finished?

### ISSUE THREAD

**Issue by OscarBengtsson** [redux-observable/redux-observable#232]
I followed the steps from [documentation](https://redux-observable.js.org/docs/recipes/WritingTests.html) to test epic.

```
...
store.dispatch({ type: FETCH_USER });
expect(store.getActions()).toEqual([
   { type: FETCH_USER },
   { type: FETCH_USER_FULFILLED, payload }
]);
...
```
But I get failed because second action is been received some later like following.

```
Test failed
    Expected value to equal:
      [{"type": "FETCH_USER"}, {"type": "FETCH_USER_FULFILLED", "payload": [some]}]
    Received:
      [{"type": "FETCH_USER"}]
    
    Difference:
    
    - Expected
    + Received
    
    @@ -1,20 +1,5 @@
     Array [
       Object {"type": "FETCH_USER"},
       Object {"type": "FETCH_USER_FULFILLED", "payload": [some]} ] // this is what should be.
```
So I think I should know when the dispatch is finished or some like that.
How can I solve this?

// UPDATED
I used fetch() and Rx.Observable.fromPromise instead of ajax.getJSON()
Here is my epic.
```
const fetchUserEpic = (action$) =>
  action$
    .ofType(FETCH_USER)
    .mergeMap(() => {
      return Rx.Observable.fromPromise(api.fetchUser())
        .map((users) => ({
          type: FETCH_USER_FULFILLED,
          payload: { users }
        }))
        .catch((error) => Rx.Observable.of({
          type: FETCH_USER_ERROR,
          payload: { error }
        }))
        .takeUntil(action$.ofType(FETCH_USER_CANCELLED))
    })
```

**Comment by jayphelps** [comment]
The reason is that promises always resolve on the [next microtask](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/) so your `api.fetchUser()` isn't emitting synchronously.

You'll need to either mock it out, use something like `Promise.resolve().then(() => expect(store.getActions).toEqual(...)` to wait until the next microtask, or you can experiment with testing your epics _directly_ without using redux.

```js
it('Epics with the appropriate input and output of actions', (done) => {
  const action$ = ActionsObservable.of(executeCell('id', 'source')));

  executeCellEpic(action$, store)
    .toArray()
    .subscribe(actions => {
      expect(actions).to.deep.equal([
        kernelNotConnected() // whatever action creators
      ]);

      done();
    });
});
```

This will be our preferred testing story in the docs when I (or someone else) has time to write them up. So instead of using redux and the middleware in your tests, we just call the epic function directly with our own mocks. Much easier and cleaner.

**Comment by jayphelps** [comment]
Taking discussion to StackOverflow 😄  http://stackoverflow.com/questions/43188196/redux-observable-failed-jest-test-for-epic

**Comment by OscarBengtsson** [comment]
Thanks for your solution. I printed actions array and I see it is correct.
Anyway, I get an error though it is outside of this issue.
```
../node_modules/jsdom/lib/jsdom/browser/Window.js:148
      return idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._location);
                                                                              ^

TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (/../node_modules/jsdom/lib/jsdom/browser/Window.js:148:79)
    at Timeout.callback [as _onTimeout] (/.../node_modules/jsdom/lib/jsdom/browser/Window.js:525:40)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
npm ERR! Test failed.  See above for more details.

**Comment by jayphelps** [comment]
@OscarBengtsson let's move the discussion to StackOverflow please 😄

**Comment by OscarBengtsson** [comment]
Ok but it is too long to comment on StackOverflow.:)

**Comment by OscarBengtsson** [comment]
@jayphelps I'd appreciate if you check [stackoverflow](http://stackoverflow.com/questions/43190171/redux-observable-cannot-read-property-location-of-null)

**Comment by OscarBengtsson** [comment]
How can I get the callbacks like catch() and takeUntil()?

**Comment by jayphelps** [comment]
@OscarBengtsson what do you mean?

**Comment by OscarBengtsson** [comment]
Oh sorry. never mind. It was just my fault

**Comment by jayphelps** [comment]
No worries! Glad you got it handled. 👍
