### ISSUE TITLE
RFC upgrade typings to TypeScript 2.3

### ISSUE THREAD

**Issue by jayphelps** [redux-observable/redux-observable#251]
We'd like to upgrade our TypeScript type definition to TS 2.3 because we'd like to take advantage of default generic params to help users be more typesafe but still flexible.

If you have any objections to this, please speak now with your reasons and at what point you think it's reasonable to do so--but keep in mind we can't accommodate _everyone_ since there will undoubtedly be a mix of people from both sides.

One example of why we want to upgrade is in #250

**Comment by Hotell** [comment]
hi @jayphelps maybe this should be closed right, cause default generics are already in ? :)

**Comment by rgbkrk** [comment]
Yeah, we're good to go here especially since #250 went in sometime ago. Thanks @Hotell.
