### ISSUE TITLE
Proposal: Epics that support fractal stores

### ISSUE THREAD

**Issue by bennett000** [redux-observable/redux-observable#257]
There are some cases where it is desirable to have reducers and state that is ignorant of an application's entire state.  For example [fractal store](https://github.com/gcazaciuc/redux-fractal) and [@angular-redux/store](https://github.com/angular-redux/store/blob/master/articles/fractal-store.md) support the idea of these isolated states.

## Current Real World Use Case

Library support aside I do have a very specific use case in mind.  We are working on a large Angular enterprise project and we can encapsulate huge chunks of functionality using Angular's module system.  With the sub store functionality in `@angular-redux/store` we're able to create Angular modules that neatly encapsulate actions and reducers.

We're also using `redux-observable` epics and this is where our encapsulation hits a snag.  Epics pass in a lite version of the store and that store is obviously the primary store.  This means that if we try and encapsulate our epics in an Angular module they would need to be aware of the global state.

Ideally we'd like to make epics that are only aware of their slice of state.

## Redux Observable Changes That Could Accommodate "Fractal Stores"

It seems like this functionality could be achieved _without_ breaking any API changes.  _One_ way this could work (and I stress _one way_ as there are many possibilities) would be to expand the `combineEpics` API.

Currently the `combineEpics` code looks like [this](https://github.com/redux-observable/redux-observable/blob/master/src/combineEpics.js#L6)

```js
export const combineEpics = (...epics) => (...args) =>
  merge(
    ...epics.map(epic => {
      const output$ = epic(...args);
      if (!output$) {
        throw new TypeError(`combineEpics: one of the provided Epics "${epic.name || '<anonymous>'}" does not return a stream. Double check you\'re not missing a return statement!`);
      }
      return output$;
    })
  );
```

In this case epics are all epic functions that take action streams and return action streams.  I could make a PR that expands this API to look something like:

```js
export const combineEpics = (...epics) => (action$, store, ...args) =>
  merge(
    ...epics.map(epic => {
      let output$;
      if (typeof epic === 'function') {
        output$ = epic(action$, store, ...args);
      } else if (typeof epic === 'object' && typeof epic.epic === 'function' && epic.store) {
        /** maybe make `epic.store` a "lite" version of the store here? */
        output$ = epic.epic(action$, epic.store, ...args);
      } else {
        throw new TypeError(`combineEpics: requires an epic function or a an object with an epic function and a store`)
      }
      if (!output$) {
        throw new TypeError(`combineEpics: one of the provided Epics "${epic.name || '<anonymous>'}" does not return a stream. Double check you\'re not missing a return statement!`);
      }
      return output$;
    })
  );
```

Then when combining epics it would be up to the consumer to pass in the epic and a sub-store.

## Final Thoughts

We're not married to encapsulating things this way it's just a possibility.  I also have not had a chance to bounce this idea off of anyone else so it might be totally insane.

**Comment by jayphelps** [comment]
I'm pretty ignorant on this whole sub-store thing. It's really unclear to me what this has to do with redux-observable. 😕

**Comment by bennett000** [comment]
@jayphelps tl;dr is that this functionality is now irrelevant to my project I'm happy to close this issue :)

Creating multiple stores would be a solution but it seems to go against the Redux paradigm of having one store and I'm not sure how that would play with something like DevTools.

Really it doesn't have anything to do with `redux-observable` other than the fact that epics are given access to the complete state.  In the case where an epic needs to access state that epic needs to know how to navigate the complete state as opposed to a slice of state.

Again I don't have any need for this functionality so I will close the issue.  If somebody else bugs you about it in the future then maybe we can talk more then?
