### ISSUE TITLE
Websocket example of your Netflix Javascript Talks video

### ISSUE THREAD

**Issue by rolele** [redux-observable/redux-observable#260]
Hi,
I saw the great video about redux-observable. Thanks.
I am interested in the Websocket non-trivial example that you showed on slide.
Would you mind adding the stockTickerEpic with the rest of the redux code as an example?

**Comment by jayphelps** [comment]
Good idea. I'll try and find some time, though to be honest our examples in general are pretty lacking. It's mostly been "if you already know Rx you should know how to do stuff" but it's a good idea regardless. Hopefully I (or someone else) will find time to create more examples.

**Comment by rolele** [comment]
Your JsBin are great to understand.
Now simulating the websocket on a jsbin might be challenging

**Comment by casertap** [comment]
@jayphelps I came up with this: https://jsfiddle.net/rolele/ued0oh9q/

but I think I really miss the point here. 
I think you might be able to look at the console and debug this quite quickly.

**Comment by jrmcdona** [comment]
Hi @casertap did you ever get your web socket figured out?  Do you have an updated jsbin?

Thanks

**Comment by jayphelps** [comment]
here's a working example of multiplexing a website using a mock (aka fake) WebSocket server. If you don't need multiplexing, things are easier than this.

https://jsbin.com/rumese/edit?js,output

Enter whatever fake ticker symbols you want and add them e.g.
![image](https://user-images.githubusercontent.com/762949/28135688-fa4def36-66fb-11e7-9d5e-4a8817409a8d.png)

**Comment by stevenmcconnon** [comment]
Here is the code on the screen during the video for the websockets example for posterity's sake:

```
const socket = WebSocketSubject.create("ws://stock/endpoint")

const stockPickerEpic = (action$, store) => 
	action$.ofType('START_TICKER_STREAM')
		.mergeMap(action =>
			socket.multiplex(
				() => ({sub: action.ticker}),
				() => ({unsub: action.ticker}),
				msg => msg.ticker === action.ticker
		)
		.retryWhen(
			err => window.navigator.onLine ?
			Observable.timer(1000) :
			Observable.fromEvent(window, 'online')
		)
		.takeUntil(
			action$.ofType('CLOSE_TICKER_STREAM')
			.filter(closeAction => closeAction.ticker=== action.ticker)
		)
		.map(tick => ({type: 'TICKER_TICK', tick}))
	);
```
