### ISSUE TITLE
React Native 0.44 + redux-observable 0.13.0: AJAX response 0, then we only get that response afterward

### ISSUE THREAD

**Issue by joeldalley** [redux-observable/redux-observable#264]
.

**Comment by jayphelps** [comment]
It's tough to grasp what the specific issue is here. How do I reproduce and what is the error?

**Comment by joeldalley** [comment]
@jayphelps The problem we experience is that, after some number of successful executions of our epic, which is a switchMap with a combineLatest in it that combines four ajax response streams, we begin getting AJAX UNSENT (0) responses, and then every subsequent application of this same epic function only produces AJAX failures from then on. Until I close the program and start over, after which we begin the cycle again of having a few successes followed by this apparently unrecoverable failure state, which persists indefinitely.

I'm surprised this hasn't been reported by anybody yet.

**Comment by jayphelps** [comment]
@joeldalley can you provide a jsbin?

**Comment by joeldalley** [comment]
I'll put something together @jayphelps. Our project is React Native and isn't open source, so let me get you something.
