### ISSUE TITLE
The docs aren't concise

### ISSUE THREAD

**Issue by rm-rf-etc** [redux-observable/redux-observable#268]
The docs are frustrating. Why is there not a hello world? Instead of showing how to get it working, the docs focus on implementation details, like "Optional Adapters", and "Combining Epics". You could provide these as side notes with a link.

The examples don't provide necessary context. "later... dispatch()" is confusing. Provide complete examples.
`// later...
dispatch(fetchUser('torvalds'));`

**Comment by jayphelps** [comment]
I'm sorry they aren't acceptable for you, but they're the best we have right now and I did put a ton of work into them. Someone is welcome to submit PRs to improve but I don't think this particular ticket is constructive in many ways.
