### ISSUE TITLE
Using takeUntil() function with apollo-client

### ISSUE THREAD

**Issue by vincentpageau** [redux-observable/redux-observable#279]
I'm using Apollo-Client to make queries and mutations to my GraphQL server. Since Apollo has its own error handling, I was wondering if it was possible to use the takeUntil function to cancel my query calls and my mutations.

Using Apollo, here is what my mutation looks like:

```
export const languageTimeZoneEpic = (action$) => {
  return action$.ofType(CHANGE_LANGUAGE)
    .mergeMap(action => client.mutate({
      mutation: languageMutation,
      variables: { id: action.id,  language: action.selected_language }
    }).then(result => changeLanguageFulfilled(result))
      .catch(error => changeLanguageError(error))
  );
};
```

My mutation is made with no problem and if there is an error, it catches it.
The problem here is if I add the `takeUntil()` function like in the example below, my function just doesn't work at all anymore.

```
export const languageTimeZoneEpic = (action$) => {
  return action$.ofType(CHANGE_LANGUAGE)
    .mergeMap(action => client.mutate({
      mutation: languageMutation,
      variables: { id: action.id,  language: action.selected_language }
    }).then(result => changeLanguageFulfilled(result))
      .catch(error => changeLanguageError(error))
  ).takeUntil("END_LANGUAGE");
};
```

I was wondering if you guys had a way to be able to use the `takeUntil()` function even if I use a client that has its own error handling.

*The takeUntil() here would be called if I dispatch another action before the mutation is complete.

Thank you

**Comment by vincentpageau** [comment]
[Here!](https://stackoverflow.com/questions/45150517/using-rxjs-takeuntil-function-with-apollo-client) is a link to my StackOverflow question.

**Comment by jayphelps** [comment]
Answering on SO 👍
