### ISSUE TITLE
"ajax error 0" & "405 (Method Not Allowed)" but request url works if pasted in chrome

### ISSUE THREAD

**Issue by NathHorrigan** [redux-observable/redux-observable#280]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
Following errors logged in console: "ajax error 0" & "405 (Method Not Allowed)" 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

The epic used below, The error suggests that I'm using the wrong http method but I should be using a GET request and when I post the generated url into chrome, everything works fine so its not URL based error.
```
export const fetchMarkers = (action$) =>
  action$.ofType(actionTypes.fetchMarkers)
    .mergeMap(action => {

      const center = action.payload.location.lat + ',' + action.payload.location.lng

      let params = queryString.stringify({
        'client_id': 'CGHZG04XKVAKD0BCIB51F5H4W5GUH2QQVCQH2AVENELBL542',
        'client_secret': 'E2MATUBFNLEKBKDDHB5NWZ3NKLQLQRU1CLJQ2PKC40L5GJTX',
        'll': center,
        'radius': 20 * 1000,
        'limit': 50,
        'intent': 'browse',
        'categoryId': '4d4b7105d754a06374d81259',
        'v': moment().format('YYYYMMDD')
      })

      return ajax.get(`https://api.foursquare.com/v2/venues/search?${params}`)
        .map(response => {
          return {
            'type': actionTypes.fetchedMarkers,
            'payload': response
          }
        })
    })
```

**What is the expected behavior?**
Ajax request completes

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
Redux-Observable: 0.14.1
RxJS: 5.4.2
Chrome: Version 61.0.3158.0 (Official Build) canary (64-bit)

**Comment by jayphelps** [comment]
Hey, if there was some sort of bug in RxJS it wouldn't be related to redux-observable so gonna close--redux-observable and RxJS are separate libraries.

I'm pretty certain that this also isn't an issue with RxJS but rather the server API is expecting something different than what you're providing or _maybe_ there's a bug in their API but this is also unlikely.

**Comment by stevematdavies** [comment]
I really would like to see some clear documentation on the ajax implementation here, since I am also having a number of inconsistencies and errors in my GET requests, headers are not being passed, body is empty etc etc. Sadly there seems to be hardly any clear examples of this.

**Comment by jayphelps** [comment]
@stevematdavies It's RxJS's built-in ajax utilities. The RxJS docs initiative is going on here: https://github.com/ReactiveX/rxjs-docs

**Comment by stevematdavies** [comment]
@jayphelps Thanks, but it links through to rxjs documentation which is not the clearest. I was hoping for some examples rather than an api reference.

**Comment by jayphelps** [comment]
@stevematdavies :shrugs:

**Comment by stevematdavies** [comment]
@jayphelps not to worry, its a common issue with libraries like these we are finding.
