### ISSUE TITLE
Redux-observable RxJS - ajax.delete returns an error and keeps retrying until the observable fails

### ISSUE THREAD

**Issue by stelioschar** [redux-observable/redux-observable#285]
I'm leaving this here. Originally posted [here](https://stackoverflow.com/questions/45330340/redux-observable-rxjs-ajax-delete-returns-an-error-and-keeps-retrying-until-th)

First of all I'd like to say a big thank you for all the good work you've done in redux-observables.

I'm facing some issues with `ajax.delete`. I'm running the code below where a **DELETE** request from `ajax` is being done and if the first fails, it keeps retrying until the request is successful.

```javascript
let RetryStrategy = attempts => attempts
    .zip(Observable.range(1, 4))
    .flatMap(([error, i]) => {
        if (i > 3) {
            return Observable.throw('Network error occured')
        }
        return Observable.timer(i * 1000)
    })

export const deleteSurveyQuestionEpic = (action$, {getState, dispatch}) =>
    action$.ofType('MY_ACTION')
        .switchMap(
            action => ajax.delete(`myURL`)
                .map(res => res.response)
                .flatMap(response => {
                    console.log(response) // <-- returns null
                    return arrayRemove('formName', 'questions', 1) // <-- redux-form action-creator
                })
                .retryWhen(RetryStrategy)
                .takeUntil(action$.ofType('MY_CANCEL_ACTION'))
                .catch((e) => {
                    return Observable.of(
                        errorSurvey((e.xhr && `Error ${e.xhr.statusText}: ${e.xhr.statusText}`) || 'Network error occured')
                    )
                })
        )
```

The problem is that in the network tab I see that the DELETE request returns **200 - OK** but the ajax.delete understands it as an error.

While looking for this issue i found [this comment](https://stackoverflow.com/questions/40708264/proper-use-of-redux-ovservable-ajax-http-methods-put-delete-post#comment68644560_40708264) where @jayphelps  is wondering if the browser makes a CORS request.

This is the case for me, while browser before each network request it makes a CORS request and after that it makes the regular request.

I'm confused and I'm not sure if this is an issue that is caused by the CORS process or I'm missing something in my implementation, once the PUT and GET requests work fine.

NOTE:
I tried to add play with `ajax.delete`'s `crossDomain` option, but I didn't manage to solve my issue.

**Comment by jayphelps** [comment]
Hey @stelioschar, I replied to the SO question requesting further info so we can continue there! You'll get better help if you reproduce and ask these sorts of questions outside the context of redux-observable since there are a lot more people using just RxJS and your problem appears only related to Rx. 💃
