### ISSUE TITLE
TypeError is not a function in jest test

### ISSUE THREAD

**Issue by athomann** [redux-observable/redux-observable#286]
**Do you want to request a *feature* or report a *bug*?**  
Possible Bug.  This would seem like its related to https://github.com/ReactiveX/rxjs/issues/1866 but it looks like I was importing the operator and Observable correctly?

**What is the current behavior?**
I setup an Epic that was meant to use multiple `action.ofType` through an `Observable.merge` to return the same ajax request.  Something like this -
```
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/merge';
import 'rxjs/add/operator/mergeMap';

export const getFields = (action$: ActionsObservable<*>) => {
  return Observable.merge(
    action$
      .ofType(UPDATE_REPORT)
      .mergeMap(action => fetchFields(action)),
    action$
      .ofType(FETCH_WORKFLOW_REPORT_SUCCESS)
      .mergeMap(action => fetchFields(action))
  );
};

```

I took this pattern from https://stackoverflow.com/a/43599309 by @jayphelps This pattern works in usage but breaks in Jest tests.  I get the error 

```
 ● Test suite failed to run

    TypeError: _Observable.Observable.merge is not a function
```

I was able to fix the issue using this pattern instead, but still curious if the above is a bug?  

```
    export const getFields = (action$: ActionsObservable<*>) => 
        action$
            .ofType(UPDATE_REPORT, FETCH_WORKFLOW_REPORT_SUCCESS)
            .mergeMap(action => fetchFields(action))
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

**What is the expected behavior?**
Passing tests with correct imports.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
    "rxjs": "^5.3.0",
    "redux-observable": "^0.14.1",

**Comment by jayphelps** [comment]
The error indeed just means you're not importing that static operator as expected--it's not Observable. It doesn't break in your app because you're likely importing it elsewhere, or importing everything.

**Comment by jayphelps** [comment]
So, what I said above is most likely true (if it works in your app you're importing static merge elsewhere or everything) however this particular file doesn't include the correct import. It's importing the prototype merge operator*not* the static version.
### change this
     import 'rxjs/add/operator/merge';
### to this
    import 'rxjs/add/observable/merge';

**Comment by athomann** [comment]
Ah, I now feel dumb haha, this fixed this tests. I'll read more into the differences of static vs prototype.  Not sure if it's out there, but do you think something similar to `babel-plugin-lodash` would be useful?  Import directly from the entire library but then the plugin transforms it to the correct import?

**Comment by jayphelps** [comment]
It's not entirely possible currently because most operators are on the prototype and you cannot statically guarantee they aren't used without restricting it to a subset of JS (e.g. no computed property keys, etc). See the rxjs repo issue tickets for reference/discussions
