### ISSUE TITLE
Professional logo

### ISSUE THREAD

**Issue by ericis** [redux-observable/redux-observable#293]
yes, the logo is fun and "3 ducks" is funny and the presentation from @jayphelps is entertaining...

But, to "compete" with alternatives, I personally feel this library will need a more "professional" logo. Redux now has a logo. Redux-Saga has a nice complimenting logo.

Suggesting Redux-Observable follow suit. (apologies to the animated duck artist)

**Comment by jayphelps** [comment]
I definitely see where you're coming from, but ultimately this doesn't make me (or anyone else) any money so to be totally honest I'm not concerned that the ducks might not perceived as professional to a small minority.

I think it's fun, and one could argue that the ducks have actually increased adoption. While it by nature competes with redux-saga, I don't have any desire to _intentionally_ compete with them.

**Comment by jayphelps** [comment]
As of now the ducks live on, but if others also feel strongly about this please voice your opinions here and we can reconsider. 🦆 🦆 🦆

**Comment by BerkeleyTrue** [comment]
🦆 🦆 🦆!!!
