### ISSUE TITLE
feat: Injecting Dependencies Asynchronously/Lazily

### ISSUE THREAD

**Issue by Hotell** [redux-observable/redux-observable#301]
**What is the current behavior?**

There is currently no way how to lazily add dependencies to middleware, please correct me if I'm missing something.

**What is the demanded behavior?**

We are building apps in modular way, so they are very easily lazy loadable, let's  take for instance, this very contrived example:

**app structure:**
``` 
src/
  --/core
  --/users
  --/transactions
  --/cars
  main.tsx
```
every folder has it's own set of reducers/epics/components/services

**services** ? -> we are using angular patterns here, so service is just a class with injected globally configured `Http` service ( interceptors, base urls, request/response transforms etc )

```ts
// users/user.service.ts
export class UserService {
  private http: Http
  constructor(http: Http){ 
    this.http = http
  }
  getUser(id:string){
     return this.http.get(`users/${id}`).then(normalizeResponse)
  }
}
```

which is then instantiated in a singleton way:

```ts
// users/users.di.ts

import {UserService} from './user.service'
import {http} from '../core'

export const userService = new UserService(http)
```

so this service is then used in users module epic, like this:

```ts
// users/users.epics.ts

import {userService} from './users.di.ts'

const fetchUserEpic = (action$, store ) =>
  action$.ofType('FETCH_USER')
    .mergeMap(({ payload }) =>
      userService.getUser(payload)
        .map(response => ({
          type: 'FETCH_USER_FULFILLED',
          payload: response
        }))
    );
```

here I cannot use 3rd argument ( dependencies ), so as you can imagine, this is impossible to unit test without some very strange black magic.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
- version: latest

**Comment by jayphelps** [comment]
One way to accomplish this is to just add more properties to the object you pass as the dependencies object.

I'm not sure how you're lazily loading them, so this is just pseudo code:

```js
const epic$ = new BehaviorSubject(combineEpics(epic1, epic2));
const rootEpic = (action$, store) =>
  epic$.mergeMap(epic =>
    epic(action$, store)
  );

const dependencies = {};
const epicMiddleware = createEpicMiddleware(rootEpic, { dependencies });

export function addEpic(newEpic, newDependencies) {
  // merges any new dependencies into our existing dependencies object
  // since objects are passed by reference this object is still the same one
  // that we passed to redux-observable above initially
  Object.assign(dependencies, newDependencies);
  
  // merges this new epic into our existing rootEpic above
  epic$.next(newEpic);
}
```

```js
import { addEpic } from './thatotherfile';
import { userService } from './whatever';

const fetchUserEpic = (action$, store, { userService }) => {
  // all your stuff from before
};

// sometime later...add another Epic, keeping the state of the old ones
addEpic(fetchUserEpic, { userService });
```

**Comment by Hotell** [comment]
Whoa!, looks good @jayphelps, thx a lot! will try it out.

Overall I think, that this definitely belongs to docs/recipes WDYT? I can submit PR once I'll implement this pattern properly.

cheers !

**Comment by jayphelps** [comment]
@Hotell agreed that would be awesome!! I'm thinking we could just add it to the end of the [Adding New Epics Asynchronously](https://redux-observable.js.org/docs/recipes/AddingNewEpicsAsynchronously.html) recipe.

Glad that helped! 🚀

**Comment by Charlynux** [comment]
@jayphelps Thanks for your snippet it helps me a lot !

But don't you miss the dependencies argument when creating rootEpic ?
```
const rootEpic = (action$, store, dependencies) =>
  epic$.pipe(mergeMap(epic => epic(action$, store, dependencies)));
```

**Comment by linonetwo** [comment]
Oh my, @Charlynux point it out, forgetting passing dependencies in mergeMap is the main cause.

**Comment by linonetwo** [comment]
End up with something like this:
```js
// create root epic that can asynchronously loading new epic
const rootEpic = new BehaviorSubject(combineEpics());
const epicMiddleware = createEpicMiddleware((action, store, dependencies) => rootEpic.mergeMap(epic => epic(action, store, dependencies)), {
  dependencies: { ipfs },
});
const context = require.context('./epics', true, /\.js$/);
context.keys().forEach(key => {
  const epicToLoad = context(key).default;
  rootEpic.next(epicToLoad);
});
```

**Comment by KushP05** [comment]
@jayphelps, What action should be taken when addEpic has already been called say with epicFirst and some tries to call addEpic with the same epicFirst.

**Comment by kushalmahajan** [comment]
Umm... how would we do that in latest version ? 

Since this solution will break because of `TypeError: Providing your root Epic to `createEpicMiddleware(rootEpic)` is no longer supported, instead use `epicMiddleware.run(rootEpic)``

The error points to `https://redux-observable.js.org/MIGRATION.html#setting-up-the-middleware` but I'm not sure if that helps.  Urgent help needed!

**Comment by Charlynux** [comment]
> Urgent help needed!

Not sure that's the best way to get some help.

By the way, I think you have all elements to answer the question your self.
Some renaming in the old code could may be help you.
```
const rootEpic = new BehaviorSubject(combineEpics());
const hyperRootEpic = (action, store, dependencies) => rootEpic.mergeMap(epic => epic(action, store, dependencies));
const options = {
  dependencies: { ipfs },
};

const epicMiddleware = createEpicMiddleware(hyperRootEpic, options);
```
Now, you could follow the migration guide.

(I don't try this code, nor the last version of redux-observable.)

**Comment by evertbouw** [comment]
> Not sure that's the best way to get some help.

It's not. This issue is closed so it's very hard to find. Opening a new issue will be faster. You can also ask in our [Gitter](https://gitter.im/redux-observable/redux-observable) or the rxjs channel in the [Reactiflux Discord](https://discordapp.com/invite/reactiflux).

In the migration guide you can find that you no longer pass `rootEpic` to `createEpicMiddleware` :
```diff
-const epicMiddleware = createEpicMiddleware(rootEpic, { dependencies });
+const epicMiddleware = createEpicMiddleware({ dependencies });
```
Instead you'll need to call `epicMiddleware.run` with your root epic somewhere after calling `createStore`
```js
const store = createStore(rootReducer, composeEnhancers(applyMiddleware(epicMiddleware)));
epicMiddleware.run(rootEpic);
```

**Comment by kushalmahajan** [comment]
Thanks for pointing to help channels.  Replied to linked issue for what worked.
