### ISSUE TITLE
Uncaught errors from promises getting swallowed when running in Jest

### ISSUE THREAD

**Issue by pelotom** [redux-observable/redux-observable#304]
Example:

```js
const ohNoEpic = action$ => action$
  .ofType('OH_NO') // where OH_NO is some real action type that will be matched
  .mergeMap(() =>
    Observable.fromPromise(new Promise(() => { throw Error('oh no') }))
  )
```

In the browser this yields a stack trace on the console... in Jest, nothing happens. If the promise was a real epic that was being tested, the test would eventually time out, with no useful error message being printed.

**Comment by pelotom** [comment]
Interestingly, if I remove the `.ofType()` call, I won't see errors in the browser either:

```js
const ohNoEpic = action$ => action$
  // .ofType('OH_NO') // where OH_NO is some real action type that will be matched
  .mergeMap(() =>
    Observable.fromPromise(new Promise(() => { throw Error('oh no') }))
  )
```

**Comment by jayphelps** [comment]
Hmm not able to reproduce: https://jsbin.com/harayiw/edit?js,output

Have you tried using "Pause On **Caught** Exception" option in your debugger, to see who's swallowing the error?

**Comment by pelotom** [comment]
Notice the part about "in Jest" :) ... if you modify your example to be a Jest test case like so:

```js
// test.js

const { Observable } = require('rxjs');

const ohNoEpic = action$ =>
  action$.mergeMap(() => Observable.fromPromise(new Promise(() => {
    console.log('error is about to happen!');
    throw Error('oh no');
  })));

const reducer = (state, action) => {
  console.log('received action', action);
};

const { createStore, applyMiddleware } = require('redux');
const { createEpicMiddleware } = require('redux-observable');

const epicMiddleware = createEpicMiddleware(ohNoEpic);

const store = createStore(reducer,
  applyMiddleware(epicMiddleware)
);

describe('#304', () => {
  it('test', () => {
    store.dispatch({ type: 'WHATEVER' });
    console.log('done with test');
  })
});
```

and run it:

```bash
> jest test.js

 PASS  ./test.js
  #304
    ✓ test (3ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.89s, estimated 1s
Ran all test suites matching "test.js".
  console.log test.js:10
    received action { type: '@@redux/INIT' }

  console.log test.js:10
    received action { type: 'WHATEVER' }

  console.log test.js:5
    error is about to happen!

  console.log test.js:25
    done with test
```

So the error gets thrown before the test case completes, but nothing is printed and the test thinks it's passed. I can dig in some more to try and figure out who is swallowing the exception, maybe Jest is to blame.

**Comment by pelotom** [comment]
If I don't use a `Promise`, but directly construct an `Observable`, the error bubbles up and the test fails:

```js
  action$.mergeMap(() => new Observable(() => {
    console.log('error is about to happen!');
    throw Error('oh no');
  }));
```

```
 FAIL  ./test.js
  ● #304 › test

    oh no

      at Observable [as _subscribe] (test.js:6:9)
      at Observable.Object.<anonymous>.Observable._trySubscribe (node_modules/rxjs/Observable.js:171:25)
      at Observable.Object.<anonymous>.Observable.subscribe (node_modules/rxjs/Observable.js:159:65)
      at Object.subscribeToResult (node_modules/rxjs/util/subscribeToResult.js:22:27)
      at MergeMapSubscriber.Object.<anonymous>.MergeMapSubscriber._innerSub (node_modules/rxjs/operator/mergeMap.js:130:38)
      at MergeMapSubscriber.Object.<anonymous>.MergeMapSubscriber._tryNext (node_modules/rxjs/operator/mergeMap.js:127:14)
      at MergeMapSubscriber.Object.<anonymous>.MergeMapSubscriber._next (node_modules/rxjs/operator/mergeMap.js:110:18)
      at MergeMapSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/Subscriber.js:89:18)
      at Subject.Object.<anonymous>.Subject.next (node_modules/rxjs/Subject.js:55:25)
      at Object.dispatch (node_modules/redux-observable/lib/cjs/createEpicMiddleware.js:72:16)
      at Object.it (test.js:24:11)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  #304
    ✕ test (3ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.056s
Ran all test suites matching "test.js".
  console.log test.js:10
    received action { type: '@@redux/INIT' }

  console.log test.js:10
    received action { type: 'WHATEVER' }

  console.log test.js:5
    error is about to happen!
```

**Comment by pelotom** [comment]
Aha, but if I make the observable _error_ without throwing an exception, it is still swallowed, so I think that's the real issue:

```js
  action$.mergeMap(() => new Observable(observer => {
    console.log('error is about to happen!');
    observer.error('oh no');
  }));
```

**Comment by pelotom** [comment]
Ok, this has nothing to do with Jest, it's about Node:

```js
// test.js

const { Observable } = require('rxjs');

const ohNoEpic = action$ =>
  action$.mergeMap(() => new Observable(observer => {
    console.log('error is about to happen!');
    observer.error('oh no');
  }));

const reducer = (state, action) => {
  console.log('received action', action);
};

const { createStore, applyMiddleware } = require('redux');
const { createEpicMiddleware } = require('redux-observable');

const epicMiddleware = createEpicMiddleware(ohNoEpic);

const store = createStore(reducer,
  applyMiddleware(epicMiddleware)
);

store.dispatch({ type: 'WHATEVER' });
console.log('done with test');
```

```
> node test.js
received action { type: '@@redux/INIT' }
received action { type: 'WHATEVER' }
error is about to happen!
done with test
```

**Comment by jayphelps** [comment]
> Notice the part about "in Jest" :) ... if you modify your example to be a Jest test case like so:

I had seen that.

OOoooooo that example is good. This actually isn't Node related, I can reproduce now with that example in the browser https://jsbin.com/tiqirij/edit?js,output

I'm pretty confident this is caused by this outstanding rxjs bug https://github.com/ReactiveX/rxjs/pull/2796

**Comment by pelotom** [comment]
Yep, I just discovered I could reproduce in the browser too :)

Cool, thanks for the pointer, I might try against that patch.

**Comment by jayphelps** [comment]
@pelotom that would be awesome if you have the time.

**Comment by pelotom** [comment]
Hm, it looks like that PR fixes this case:

```js
action$.mergeMap(() =>
  new Observable(observer => observer.error('oh no'))
);
```

but not this case:

```js
action$.mergeMap(() =>
  Observable.fromPromise(new Promise((resolve, reject) => reject('oh no')))
);
```

or this case:

```js
action$.mergeMap(() =>
  Observable.fromPromise(new Promise(() => { throw Error('oh no') }))
);
```

**Comment by jayphelps** [comment]
@pelotom does that particular thing only happen with Jest? I can't reproduce it normally: https://jsbin.com/zuboju/edit?js,output

**Comment by jayphelps** [comment]
OHHHHHHHHHHHHH so your particular issue is actually because your epic does not error synchronously because Promises are **always** async (they schedule the callback on a new microtask aka "next tick")

So the error probably does propagate, but it's not propagated to the `store.dispatch({ type: 'WHATEVER' });` callsite.

Here's a demonstration: https://jsbin.com/goruvur/edit?js,output

**Comment by pelotom** [comment]
Yep, it appears so.

**Comment by pelotom** [comment]
Confirmed that it only happens in Jest now.

**Comment by pelotom** [comment]
Where does it propagate to, then?

**Comment by pelotom** [comment]
So using this code:

```js
const { Observable } = require('rxjs');

const ohNoEpic = action$ =>
  action$.mergeMap(() => Observable.fromPromise(new Promise((resolve, reject) => {
    console.log('about to error');
    reject('oh no');
  })));

const reducer = (state, action) => {
  console.log('received action', action);
};

const { createStore, applyMiddleware } = require('redux');
const { createEpicMiddleware } = require('redux-observable');

const epicMiddleware = createEpicMiddleware(ohNoEpic);

const store = createStore(reducer,
  applyMiddleware(epicMiddleware)
);

describe('#304', () => {
  it('test', done => {
    store.dispatch({ type: 'WHATEVER' });
    console.log('done with test');
  })
});
```

because I'm using the `done` callback, the test is asynchronous, and it currently fails due to timing out:

```
> jest test.js
  console.log test.js:10
    received action { type: '@@redux/INIT' }

  console.log test.js:10
    received action { type: 'WHATEVER' }

  console.log test.js:5
    error is about to happen!

  console.log test.js:25
    done with test

 FAIL  ./test.js (5.645s)
  ● #304 › test

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:488:11)
      at tryOnTimeout (timers.js:323:5)
      at Timer.listOnTimeout (timers.js:283:5)

  #304
    ✕ test (5006ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.152s
Ran all test suites matching "test.js".
```

At no point does the error get printed, much less fail the test. I'm not sure in what sense you mean that the error propagates; it's clearly getting swallowed somewhere...

**Comment by jayphelps** [comment]
```js
describe('#304', () => {
  it('test', done => {
    store.dispatch({ type: 'WHATEVER' });
    console.log('done with test');
  })
});
```

This will always timeout regardless because you have to call `done()` when it's done.

**Comment by pelotom** [comment]
Well, ideally the test should fail, not timeout, because an error occurred, but at any rate we should _see_ the error in the output...

**Comment by jayphelps** [comment]
This whole error propagation thing is a little complicated but you can think of it as Promises wrap your callbacks in sort of a try/catch and also schedule it on a new microtask. It catches errors so that it can send them to anyone listening via the second `.then(success, fail)` argument. If no one listens, it is essentially "swallowed" as far as normal JS callstack is concerned.

This was the status quo for quite a while actually, but that obv means its hard to debug cause you wouldn't see the traditional error in your console or error logs. To resolve this, in the relatively recent history they have provided a new global event listener for unhandled Promise errors named `unhandledrejection`:

```js
window.addEventListener('unhandledrejection', function(event) {
    console.error('Unhandled rejection promise: ', event.promise, ', reason: ', event.reason);
});
```
Browsers like Chrome now hook into this and automatically display these unhandled rejections in your console now, so while they're still "swallowed" in the traditional sense we can still listen for them and see them in the console of modern versions of browsers.

In node, things are a bit different because this behavior is contentious and this swallowing behavior is much more complex and desirable for various reasons. Node has supported a similar event listening mechanism for a while, but up until extremely recently it did NOT log them out in any way by default. This changed [in 6.6](http://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html).

In fact, in the future node will actually terminate the process when an unhandled rejection is encountered! Right now in the latest node you'll see a warning:

> DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. */

**Comment by jayphelps** [comment]
You can also confirm this with this:

```js
describe('#304', () => {
  it('test', done => {
    new Promise(() => { throw Error('oh no') });
    console.log('done with test');
  })
});
```

You can remove the done, so its sync too. It still won't catch the Promise error and in older versions of node you won't see any indication of that unhandled rejection (unless someone hooks into process.on('unhandledrejection')`)

**Comment by pelotom** [comment]
Thanks for the info. I guess I'm surprised that / don't understand why `Observable.fromPromise` can't shield me from needing to know about these particular semantics of promises; shouldn't an erroring promise just turn into an observable that errors? In other words, why can't

```js
Observable.fromPromise((resolve, reject) => reject('oh no'))
```

have the same semantics as

```js
Observable.create(observer => observer.error('oh no'))
```

But ok, assuming there's a good reason for that, how do I solve this problem for running in Jest? I tried listening for it as you suggested

```js
process.on('unhandledrejection', reason => console.log('unhandled!', reason))
```

but the callback doesn't get triggered.

**Comment by pelotom** [comment]
> In node, things are a bit different because this behavior is contentious and this swallowing behavior is much more complex and desirable for various reasons. Node has supported a similar event listening mechanism for a while, but up until extremely recently it did NOT log them out in any way by default. This changed in 6.6.

> In fact, in the future node will actually terminate the process when an unhandled rejection is encountered! Right now in the latest node you'll see a warning:

> `DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. /*`

BTW, I'm running node 8.1.4, and if I run this as a straight node program the process _does_ fail (not merely giving a warning). As far as I'm concerned that's great behavior!

**Comment by jayphelps** [comment]
Promises are always scheduled on the microtask, Observables are scheduled synchronously by default, unless a scheduler is provided (operators like debounce provide async scheduler automatically).

Try this:

```js
try {
  Observable.create(observer => observer.error('oh no'))
    .subscribe(); 
} catch (e) {
  console.log('yep, I caught it: ', e);
}
```

It's also not possible to force a Promise to be synchronous.
 
I suggest reading https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/ or other resources on JavaScript scheduling.

***

> But ok, assuming there's a good reason for that, how do I solve this problem for running in Jest? I tried listening for it as you suggested

There are many ways, one way would be to mock out Promise so that it is synchronous. Mostly all the solutions aren't great.

Instead of actually using an entire real redux store, I have been recommending people just call their epic directly and provide their own ActionsObservable, mock store (if neccesary), and inject dependencies. Take a look at [this section in the docs](https://redux-observable.js.org/docs/recipes/InjectingDependenciesIntoEpics.html). There is also some inspiration in #108 on various possible techniques.

I think it's been enough time that we could update the testing section of the docs to recommend that pattern instead.

```js
it('test', () => {
  const action$ = ActionsObservable.of({ type: 'WHATEVER' });

  return ohNoEpic(action$)
    .toArray()
    .toPromise();
});
```

Would produce cause Jest to fail this test with your your "oh no" error. If you wanted to instead asserted that the error was expected:

```js
it('test', () => {
  const action$ = ActionsObservable.of({ type: 'WHATEVER' });

  return ohNoEpic(action$)
    .toArray()
    .toPromise()
    .catch(error => {
      // untested, but you get the idea :)
      expect(error).toBe('oh no');
    });
});
```

**Comment by pelotom** [comment]
I'm trying to write integration tests, so I'm exercising everything starting from the react props all the way to the real server and back. So I don't want to just call epics directly and test them in isolation, I want them to be set up and invoked indirectly through the same mechanisms they would be in the regular app.

Do you know of any way that I could just inject a catch-all handler for uncaught promise errors? I was hopeful about `process.on('unhandledrejection')`, but that didn't seem to work...

**Comment by jayphelps** [comment]
I only know of `process.on('unhandledrejection')` which has worked for me in the past. It's likely that it won't be used for promises given to rxjs because rxjs will add an error handled to them, so they might not be considered "unhandled". Any further specifics I can't help with, sorry!

**Comment by pelotom** [comment]
So I wrote a function `myFromPromise` which does what, in my mind, `Observable.fromPromise` should be doing:

```js
function myFromPromise(p) {
  return new Observable(observer => {
    p.then(result => {
      observer.next(result);
      observer.complete(result);
    }).catch(reason => {
      console.log('caught error', reason)
      observer.error(reason);
    })
  })
}
```

When I use it in place of `Observable.fromPromise`, I get

```
received action { type: '@@redux/INIT' }
received action { type: 'WHATEVER' }
about to error
done with test
caught error Error: oh no
    at Promise (/Users/tom/code/playground/redux-observable-#304/test.js:6:11)
    at Promise (<anonymous>)
    at MergeMapSubscriber.action$.mergeMap [as project] (/Users/tom/code/playground/redux-observable-#304/test.js:4:40)
    at MergeMapSubscriber._tryNext (/Users/tom/code/playground/rxjs/dist/cjs/operator/mergeMap.js:120:27)
    at MergeMapSubscriber._next (/Users/tom/code/playground/rxjs/dist/cjs/operator/mergeMap.js:110:18)
    at MergeMapSubscriber.Subscriber.next (/Users/tom/code/playground/rxjs/dist/cjs/Subscriber.js:89:18)
    at Subject.next (/Users/tom/code/playground/rxjs/dist/cjs/Subject.js:55:25)
    at Object.dispatch (/Users/tom/code/playground/redux-observable-#304/node_modules/redux-observable/lib/cjs/createEpicMiddleware.js:72:16)
    at Object.<anonymous> (/Users/tom/code/playground/redux-observable-#304/test.js:28:11)
    at Module._compile (module.js:569:30)
(node:31732) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: oh no
(node:31732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Which is... baffling? If I'm catching the promise, why is it showing up as an unhandled promise rejection warning? It seems there is just something deeply wrong about my mental model of how promises work.

**Comment by jayphelps** [comment]
@pelotom when I run this in node I get the UnhandledPromiseRejectionWarning:

```js
Promise.reject('test').then(result => {
  // not called
});
```

If I run this I do not, I just get my console.log:

```js
Promise.reject('test').then(result => {
  // not called
}).catch(reason => {
  console.log('caught error', reason);
});
```

**Comment by pelotom** [comment]
Ok, I think what this boils down to is that Jest doesn't handle asynchronous errors well unless they are part of the asynchronous testcase itself. An extremely simple example is given [here](https://github.com/facebook/jest/issues/4019). Apparently there is a [PR](https://github.com/facebook/jest/pull/4016) to address this. In the mean time, I've worked around this by injecting an optional error handler into my store creation function, then wrap the root epic in an epic which will catch on the result stream and call the handler:

```js
  const wrappedEpic = (action$, store, dependencies) => {
    const result$ = appEpic(action$, store, dependencies)
    return handleAsyncError ? result$.catch(error => {
      handleAsyncError(error)
      return Observable.empty()
    }) : result$
  }
```

In the context of Jest I provide a `handleAsyncError` which is capable of failing the currently-running test. This works!

**Comment by pelotom** [comment]
Thanks for helping me to understand the issue and come to a solution @jayphelps!

**Comment by jayphelps** [comment]
You're welcome! Glad you found a solution. 🤘
