### ISSUE TITLE
Configuration with Create React Native App

### ISSUE THREAD

**Issue by MrLoh** [redux-observable/redux-observable#306]
I'm not sure what's going on, but I cant get redux-observable to work in my create-react-native-app project. I've uses redux-observable before in several web projects. My store setup is the following. But the rxjs operators don't seem to be imported correctly, I always just get `action$.filter is not a function`. 

Am I missing something, or is this an incompatibility with react native? 

```js
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
const rootEpic = action$ => action$.filter(action => action.type === 'PING').map({ type: 'PONG' });

const epicMiddleware = createEpicMiddleware(rootEpic);

const store = createStore(rootReducer, applyMiddleware(epicMiddleware));
```

**Comment by MrLoh** [comment]
If I simply do something like this in my index.js file, everything works, so I wonder wether it's a problem with injecting the Operators on react native. 

```js
import { Observable } from 'rxjs';
import 'rxjs/add/operator/filter';
Observable.of(1, 2, 3, 4, 5, 6).filter(i => i % 2 === 0).map(i => i + 2).subscribe(console.log);
```

**Comment by jayphelps** [comment]
This usually means you accidentally have two versions of rxjs installed--one that redux-observable needs is given by webpack, the other your package.json says it needs that you are given. When you import the operators they are added to your Observable, but not the Observable redux-observable has and gives to your epic.

A large percentage of our community is React-native btw 😎

**Comment by jayphelps** [comment]
Import Observable and check 'action$ instanceof Observable'. Should be true, if not, two copies.

**Comment by jayphelps** [comment]
If it is two copies it may also be another dependency you have that is pulling in a different version, you'll have to do some digging through your node_modules.

**Comment by MrLoh** [comment]
Yep that was it. Thanks a lot. Lint-staged was the culprit. Very easy to find in the yarn.lock file. 

What's the best way to fix this. For now I removed lint-staged and I guess they should really have rxjs as a peer dependency. But in the meantime, how can I use both packages.

**Comment by jayphelps** [comment]
@MrLoh hmm can you link me? This one I found from google doesn't itself seem to use rxjs https://github.com/okonet/lint-staged/blob/master/package.json Different lint-staged or maybe one of its deps?

It it possible to share your lockfile in its entirety? in a gist plz 😄 I'm a bit confused how it could be causing this, since I assume you're not importing lint-staged in your UI/webpack app bundle, only used it for dev/build purposes

**Comment by MrLoh** [comment]
this was the git diff of my yarn.lock adding redux-observable and rxjs and removing lint-staged https://gist.github.com/MrLoh/a406be1e537a8c56c805f09bc61ce1b6

**Comment by jayphelps** [comment]
Ah okay so lint-saged deps on listr which depends on rxjs. That seems fine AFAIK (even if they're different versions of rxjs) as long as you aren't importing lint-staged or listr in your webpack app, I was under the impression it wouldn't cause issues.

**That said** clearly there is an issue somewhere. I'm not sure I can be a ton of help, as I don't use yarn so I'm not sure if there's something particularly unique about it that would be relevant here. Just for kicks you might try blowing away your node_modules completely and reinstalling them--I know the lockfile is supposed to make this unnecessary but hey, simple thing to try 😉 

If there's an easy way to extract out a repo I can use to reproduce, I'm happy to take a look when I have time. But you may find it's not easy or not worth it. Your call of course.

In the past when this has come up I've used various community tools to analyze the deps graph webpack generates for the bundle and it usually fairly quickly reveals who is importing each copy and why. [Here's a guide that seems good](https://medium.com/@joeclever/three-simple-ways-to-inspect-a-webpack-bundle-7f6a8fe7195d) (haven't read it for real tho).

**Comment by MrLoh** [comment]
I'll definitely look into it and let you know. When I find the time.

**Comment by MrLoh** [comment]
Seems that reinstalling lint-staged now after rxjs had ben installed solved the issue. very odd.

**Comment by jayphelps** [comment]
👍👍👍
