### ISSUE TITLE
Comment: awesomeness

### ISSUE THREAD

**Issue by haf** [redux-observable/redux-observable#307]
I just wanted to let you guys know that we've moved to redux-observable for all things IO/async and they're kicking ass.

Well done with this library.

**Comment by jayphelps** [comment]
Yay! This made my day. Thank you for sharing!😄

**Comment by akaztp** [comment]
Yep, I can follow along with @haf comment!
I've even incorporated the epics approach into my latest web app architecture. It really makes the view/business logic very modular!
I've documented it in this article: [Web app architecture based on Redux](https://medium.com/@akaztp/web-app-architecture-based-on-redux-1e16294c817a)

**Comment by jayphelps** [comment]
Thanks again @haf
