### ISSUE TITLE
Should Epic TypeScript signature include a separate return type?

### ISSUE THREAD

**Issue by thirty3** [redux-observable/redux-observable#308]
Most of the examples I have seen using Redux-Observables are in Javascript and as such typing doesn't matter. I ran into a TypeScript compiler issue when I changed the type contained in the returned observable to be different to the type contained in the input ActionObserable.

Looking at the signature for Epic
```
export declare interface Epic<T, S, D = any> {
  (action$: ActionsObservable<T>, store: MiddlewareAPI<S>, dependencies: D): Observable<T>;
}
```
Since `T` is used in `action$` as well as the result, does this not imply that the type cannot change?

Should another generic `R` not be introduced for return type?
```
export declare interface Epic<T, S, R, D = any> {
  (action$: ActionsObservable<T>, store: MiddlewareAPI<S>, dependencies: D): Observable<R>;
}
```

I changed my signatures locally to work like this and I got the expected behavior, but perhaps I am missing some point of the original signature?

Thanks,
Leon

**Comment by jayphelps** [comment]
Hey @thirty3! Thanks for contributing. This is indeed a good question, we've been discussing it in #219 so going to close this as a duplicate.

One thing to keep in mind is that any action your epic **outputs** will also recursively be an **input** seen by your action$.ofType. It's just not as obvious cause you usually aren't matching against them. So _technically_ the input and output are the same union type. Would love to hear your thoughts over in #219.
