### ISSUE TITLE
It might be there is bug in combineEpics 

### ISSUE THREAD

**Issue by irwansyahwii** [redux-observable/redux-observable#320]
**Do you want to request a *feature* or report a *bug*?**  
Report bug

**What is the current behavior?**

I got error inside my Epic the first time I run my app.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

**What is the expected behavior?**

Should be no errors happening

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
0.16.0

So I took a look at the source code and the issues, it seems you guys are trying to prevent users to not forget to do explicit return inside the epic by directly calling the epics when the combineEpics called. But when the epic filtering the action using `ofType` it returns `undefined` broke the pipeline. So the solution is to fix the `combineEpics` by making sure it pass the correct action or remove the checking completely.

**Comment by jayphelps** [comment]
Hmm it's not clear what the bug is? What exactly is the error? Can you provide code and steps to reproduce the problem?

**Comment by irwansyahwii** [comment]
Sorry my bad, developing using Windows Insider program introduced many false alarms. I will close this issue. Thank you for this great library @jayphelps :)

**Comment by jayphelps** [comment]
🕺
