### ISSUE TITLE
Either CombineEpics typing is misleading or I don't understand something

### ISSUE THREAD

**Issue by raqystyle** [redux-observable/redux-observable#323]
**Do you want to request a *feature* or report a *bug*?**  
I want to report a bug.

Here's the problem. I have a bunch of modules (store/state, actions, reducer, epic(s), views). If I combine reducers like this:
```ts
type Module1State = { .... }
...
type Module2State = { .... }
...
type RootState = {
  m1: Module1State
  m2: Module2State
}
...
const rootReducer: Reducer<RootState> = combineReducers<RootState>({
  m1: module1reducer,
  m2: module2reducer
});
```
... I get my `RootState` just like it is shown above.

Now, each module has its own Epic:

```ts
type Module1Action = ... | ... | ...
type Module1State = { .... }
...
const m1Epic: Epic<Module1Action, Module1State>
```

Okay. The problem appears when I want to combine such Epics:

```ts
import { m1Epic, m1ActionType, m1State } from './m1';
import { m2Epic, m2ActionType, m2State } from './m2';
...
type RootAction = m1ActionType | m2ActionType
type RootState = {
  m1: m1State
  m2: m2State
}
...
const store = createStore<RootAction>(
  rootReducer,
  applyMiddleware(
    createEpicMiddleware(
      combineEpics<RootAction, RootState>(m1Epic, m2Epic)
    )
  )
);
```

This will not compile because according to https://github.com/redux-observable/redux-observable/blob/master/index.d.ts#L51 `combineEpics` takes type `S` for Root State Type. Therefor, `RootState` is not assignable to `m1State` or `m1State`

Therefore, it's either me being stupid and doing something wrong or there's an issue with the type signatures...

**Comment by jayphelps** [comment]
Hey 👋 The actions and state types must be all actions and all state because every epic receives every action, and can access every piece of state in the store.

If you'd prefer to isolate them further you probably can create additional abstractions on top that would do this for you.

**Comment by raqystyle** [comment]
@jayphelps Hi, thank you for the prompt reply!
Correct me if I'm wrong, but if I understood correctly, I shouldn't do this:
```ts
const m1Epic: Epic<Module1Action, Module1State>
```
... without this extra layer of abstraction?

**Comment by rgbkrk** [comment]
Yeah, that's correct. What I end up doing, at least because I'm using FlowType is:

```js
export function loadEpic(
  action$: ActionsObservable<CONTENTS_ACTION>,
  store: Store<*, *>
) {
  return action$
    .ofType("LOAD")
    .do((action: LOAD_ACTION) => {
      // If there isn't a filename, save-as it instead
      if (!action.filename) {
        throw new Error("save needs a filename");
      }
    })

```

since it lets me carve out the types within the operators just fine.

The reason it tends to be useful to have the `action$` all available is that you can use other actions to end certain streams.

```
.takeUntil(action$.ofType('CANCEL_LOAD').filter(action => action.id === someID))
```

**Comment by jayphelps** [comment]
@raqystyle let us know if you need more help. 😄

**Comment by challme28** [comment]
@rgbkrk What is your `CONTENTS_ACTION`? Is it an array of actions? (LOAD_ACTION, SAVE_ACTION...)

**Comment by rgbkrk** [comment]
In the above example it's:

```js
CONTENTS_ACTION = LOAD_ACTION | SAVE_ACTION
```

Whereas in the [current code it's `ALL_ACTIONS`](https://github.com/nteract/nteract/blob/62da299a22317a59e77959521f49411824e2a3ef/packages/nbextension/nteract_on_jupyter/actions/index.js#L5).
