### ISSUE TITLE
Errors swallowed silently with Observable.zip

### ISSUE THREAD

**Issue by jagretz** [redux-observable/redux-observable#338]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
This fails silently within `.zip()`. Using the example below, the first argument to `ajax` is an object literal, `{ ...action, url: action.foo.links.bar }` but `action.foo.links` is undefined so `.bar` can never be reached. I would have expected a TypeError to have been thrown but nothing happens and instead the observable just dies.

I have some easy solutions to this problem (like checking the action props prior to making the ajax invocation) but I think it's a bug with redux-observable that should be documented. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

```javascript
export function fetchEpic(action$, store) {
    return action$.ofType(FETCH)
        .switchMap(action => Observable.zip(
            // Strip out the desired url and assign it as an immediate child property.
            ajax({ ...action, url: action.foo.links.bar }, {}, store)
                .map(fetchFooSuccess)
                .catch(error => fetchError(action, error)),
            Observable.of(mockResponse).map(response => ({ response }))
        .do(results => {
            setItem("store", results[2]);
        })
        .mergeMap(results => Observable.of(
            fetchSuccess(...results),
            setStore(results[2])
        ))));
}
```
**What is the expected behavior?**
An error is thrown.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
v0.14.1 on Chrome browser

**Comment by jayphelps** [comment]
I think this is the same bug in rxjs that's causing #263, which is being tracked here https://github.com/ReactiveX/rxjs/issues/2813

You can work around this by using a bit of function composition in your root epic to detect and rethrow the error yourself

```js
const rootEpic = (...args) =>
  combineEpics(epic1, epic2, ...etc)(...args)
    .do({
      error: e => setTimeout(() => { throw e; })
    });
```

**Comment by jagretz** [comment]
Works. Thanks a bunch! Allows me to route my user appropriately given the the action it fails with.
