### ISSUE TITLE
Upgrade to rxjs 5.5.0 breaks... everything

### ISSUE THREAD

**Issue by magnusheino** [redux-observable/redux-observable#341]
action$.ofType does not return what it used to return. .map, .mergeMap etc isn't there anymore.

**Comment by siimeon** [comment]
I have same issue

I managed to get somethings working by importing operations one by one, but after some fighting did go back to `5.4.3`

**Comment by evertbouw** [comment]
If you used to do `import "rxjs";` you can quickly fix it by doing `import "rxjs/Rx";`.

**Comment by siimeon** [comment]
@evertbouw Thanks for your help 👍 that fixes my problem my problem

**Comment by jayphelps** [comment]
Uh oh! Thanks all for reporting. The issue is with rxjs, I believe I've found the cause. Let's move this over to https://github.com/ReactiveX/rxjs/issues/2984 (no need to comment there, but you're welcome to 👍  it)

**Comment by jayphelps** [comment]
Hey all, 5.5.1 of rxjs was released, which fixed this issue.

**Comment by magnusheino** [comment]
Should I switch back to importing rxjs, or whats the difference between rxjs ans rxjs/Rx?

**Comment by jayphelps** [comment]
Right now there is no difference. My completely personal opinion is that people should import just `rxjs`, not `rxjs/Rx`
