### ISSUE TITLE
getStore() returns incorrect store on websocket openObserver?

### ISSUE THREAD

**Issue by proProbe** [redux-observable/redux-observable#342]
I am currently trying to do `send the user information` based on store() when a connection to a websocket is opened. I am using a `Subject` here that is put on websockets "openObserver" and then I am creating an epic that uses that subject.

My store looks something like this:
```
// TYPE
user: {
  name?: string
}

// initValue
user: {
  name: undefined
}
```
The interactionflow is similar to this:
`start app => insert username => connect to socket => on opened connection, send username`
 
My problem here is that whenever the "openObserver"-subject reacts, it does "getStore()" but does not have the `inserted username`. Is this perhaps a bug?

**Do you want to request a *feature* or report a *bug*?**  
Bug?

**What is the current behavior?**
Store is not correct

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**
Here is some code
```
// Websocket and openSubject
const openSubject = new Subject();
const wsPath = process.env.WS_PATH || "ws://localhost:3000/socket";
export const socket$ = Observable.webSocket({
  url: wsPath,
  openObserver: openSubject,
});
...
// Epic for the openSubject
const openSubjectEpic = (action$, store) =>
    openSubject
      .mapTo(socket$.next(JSON.stringify(store.getState().user))) // <=== store here is old
      .mapTo({type: "NOOP"});
```

**What is the expected behavior?**
that `getStore()` returns the store with a `user.name` in it.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
^0.16.0

**Comment by jayphelps** [comment]
Hey there. Your code is running when the epic is first called rather than when you receive some action. I’ll try to find some time to explain, in the meantime I’d recommend going through the our docs and brush up on how Observables work.

**Comment by proProbe** [comment]
Ah, I see the problem. it gets `subscribed` as soon as I register the epic. Then I am not sure how this should be thought about and how a solution would look like? How would one send data depending on the current store back to the websocket when it is opened?

**Comment by BerkeleyTrue** [comment]
@proProbe I've found having an `appMounted` action dispatch on the top level `componentDidMount` is useful for this sort of thing. You could use such an action to trigger the start of the websocket connection.

```js
// Epic for the openSubject
const openSubjectEpic = (action$, store) =>
  actions.ofType('appMount')::switchMap(() =>
    openSubject
      .mapTo(socket$.next(JSON.stringify(store.getState().user))) // <=== store here is old
      .mapTo({type: "NOOP"}));

**Comment by jayphelps** [comment]
@proProbe did you figure out a solution?

**Comment by proProbe** [comment]
@jayphelps Oh yes! I tried @BerkeleyTrue solution yesterday and it worked like a charm. Thanks for all the help. Reactive programming feels like the next tool I would love to have under my belt.
