### ISSUE TITLE
Epics not working properly with react native 0.49.3

### ISSUE THREAD

**Issue by nikhilag** [redux-observable/redux-observable#344]
I upgraded react native to react native 0.49.3 and for some reason my app has stopped working properly now. On dispatching an action, the epic is not called at all. While debugging, I see dispatch(action) being executed but for some reason the epic for that action is not invoked.

Has anyone else tried using redux observable with react native 0.49.3?

**Comment by jayphelps** [comment]
Could you put together a repo for me to reproduce? I'm happy to take a look.

**Comment by nikhilag** [comment]
@jayphelps Sorry for this late response. I ended up migrating to redux-thunk temporarily. I wasn't able to figure out when this issue would occur. I noticed that some epics were working (related to my login code) but some were not (related to fetching the data) even though I had not made any change in my code after upgrading react native.

**Comment by jayphelps** [comment]
@nikhilag no problem, glad you got unblocked by using redux-thunk. Lmk if you decide to revisit and I'll help take a look. FWIW there hasn't been any other reports yet.
