### ISSUE TITLE
Adding new epics asyncronously causes the epic to be called twice with the same action in quick succession.

### ISSUE THREAD

**Issue by anwarhamr** [redux-observable/redux-observable#349]
I'm having an issue w/ duplicate actions being passed to my epic when I have added them dynamically using the examples here.  [Adding New Epics Asynchronously](https://redux-observable.js.org/docs/recipes/AddingNewEpicsAsynchronously.html)

I have a stackoverflow question out on this with example code here:
[https://stackoverflow.com/questions/46854844/dynamically-adding-epics-during-runtime-calls-the-newly-added-epics-multiple-tim](https://stackoverflow.com/questions/46854844/dynamically-adding-epics-during-runtime-calls-the-newly-added-epics-multiple-tim)

**Comment by jayphelps** [comment]
Answered on StackOverflow 😄
