### ISSUE TITLE
Can't import modules from 'redux-observable'

### ISSUE THREAD

**Issue by BenoKop** [redux-observable/redux-observable#356]
**Do you want to request a *feature* or report a *bug*?**  

BUG

**What is the current behavior?**

Getting an error when I import modules from 'redux-observable':

**Imports**
`import { createEpicMiddleware } from 'redux-observable';`
OR
`import { combineEpics } from 'redux-observable';`

**Error**
```
./node_modules/redux-observable/lib/esm/ActionsObservable.js
Module not found: Can't resolve 'rxjs/Observable' in 'C:\wamp64\www\bob-web\notice-cmi\node_modules\redux-observable\lib\esm'
```

**What is the expected behavior?**

Just to start an app without import errors

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

Version of redux-observable: 0.17.0
Browser: Mozilla Firefox
OS: Windows 8
I don't know, i'm new :)

**Comment by evertbouw** [comment]
Are you sure you've installed rxjs as well? `yarn add rxjs` or `npm i -S rxjs`

**Comment by BenoKop** [comment]
I noticed i forgot to install it ...
Thanks for the fast reply :)

**Comment by jayphelps** [comment]
Thanks @evertbouw ! 🤠
