### ISSUE TITLE
Observable type error reference

### ISSUE THREAD

**Issue by NoctisHsu** [redux-observable/redux-observable#368]
Hello everyone,

I get an problem when try to define the typescript interface on my epic function, but got an error message like this.

![Image of error](https://cdn-std.dprcdn.net/files/acc_575359/mimkWN)

I try to find the problem, it seems like an module path problem , so I try to fix the problem and make an Pull request.
https://github.com/redux-observable/redux-observable/pull/369

Thank you very much. 😃

**Comment by jayphelps** [comment]
Hey there. The issue is most likely that you have not yet imported concatMap

**Comment by jayphelps** [comment]
The reason your PR solved it is because it then pulled in all of rxjs, including concatMap. You can either import operators individually or import them all with `import “rxjs”;`

**Comment by NoctisHsu** [comment]
Thank you so much for the speedy reply.
It's clear to me now.
I  import with "rxjs/add/operator/concatMap" and the problem is solved.
Thank you very much . 👍

**Comment by jayphelps** [comment]
@NoctisHsu woohoo! so glad. Take care.
