### ISSUE TITLE
`./utils/console` is not being resolved

### ISSUE THREAD

**Issue by pfrendo** [redux-observable/redux-observable#372]
`./utils/console` is not being resolved, can this be replaced with console.log ?

**Comment by evertbouw** [comment]
Can you elaborate on when this problem occurs? Right now I cannot reproduce this.

`./utils/console` is being used so a deprecation warning is only shown once instead of every time you use a deprecated feature.

**Comment by jayphelps** [comment]
Hey @pfrendo, indeed we'll need some way to reproduce this. Let us know when you have a way!
