### ISSUE TITLE
ofType cannot infer that return type is of that type

### ISSUE THREAD

**Issue by EamonnLaffey** [redux-observable/redux-observable#382]
Suppose you have types for two actions:

```typescript
const PING = "PING";
interface PING {
  type: typeof PING;
}
const ping: () => PING = () => ({
  type: PING,
});

const PONG = "PONG";
interface PONG {
  type: typeof PONG;
}
const pong: () => PONG = () => ({
  type: PONG,
});

type RootAction = PING | PONG;
type RootState = ...;
```

We should now be able to write epics and have proper typing. For example:

```typescript
const epic: Epic<RootAction, RootState> = action$ => 
  action$
    .ofType(PING)
    .map(action => /* The type of action here is still PING | PONG */)
```

Although we come into an issue that `ofType` does not return an observable that is of the type we expect.

We now have to cast the returned action into the type that we expect it to be. I have previously seen that done as below. However, with typescript 2.6 introducing strict function types we can no longer do that either.

```typescript
const epic: Epic<RootAction, RootState> = action$ => 
  action$
    .ofType(PING)
    .map((action: PING)  => /* typescript 2.6 with strict function types doesn't like this. */)
```

One solution to get around this is to use rxjs `filter` instead of using `ofType`. However, by doing this the code becomes a little repetitive and difficult to read. This is especially an issue as the pattern of filtering on action type using redux observable is very common.  

```typescript
const epic: Epic<RootAction, RootState> = action$ => 
  action$
    .filter<RootAction, PING>((action): action is PING => action.type === PING)
    .map(action  => /* action is now of type PING! */)
```

The function ofType is implemented to accept a variadic parameter of keys. However, typescript does not support variadic generic templates (yet). I propose having a number of overloads for different number of parameters.

For example this is the current type definition for `ofType` within the `ActionsObservable` class:
```typescript
ofType(...key: T['type'][]): ActionsObservable<T>;
```

This would become something like this to solve the problem:
```typescript
ofType<T extends Action>(key: T['type']): ActionsObservable<T>;
ofType<T1 extends Action, T2 extends Action>(key1: T1['type'], key2: T2['type']): ActionsObservable<T1 | T2>;
ofType(...key: T['type'][]): ActionsObservable<T>;
```

We can now use ofType and send through the type of the action and get correct type information

```typescript
const epic: Epic<RootAction, RootState> = action$ => 
  action$
    .ofType<PING>(PING)
    .map(action => /* action is now of type PING! */)
```

I would be happy to work on this and add more documentation about using redux observable with typescript but would like some input first. So let me know!

**Comment by evertbouw** [comment]
A change already landed on master that adds a generic to the ofType method:
```typescript
ofType<R extends Action = T>(...key: R['type'][]): ActionsObservable<R>;
```
https://github.com/redux-observable/redux-observable/blob/master/index.d.ts#L29

Also the lettable version has this signature:
```typescript
export declare function ofType<T extends Action>(...keys: T['type'][]): (source: Observable<T>) => Observable<T>;
```

So your last example already works with the lettable operator and is going to work with the dot operator in the next version.

If you want to use multiple action types, wouldn't you be able to do `ofType<PING | PONG>(PING, PONG)` and achieve the same result?

**Comment by Hotell** [comment]
while https://github.com/redux-observable/redux-observable/blob/master/index.d.ts#L29 fixes the `.ofType` chain via explicitly setting generic action creator types, lettable `ofType` is still broken.

```ts
const enum ActionTypes {
  One = 'ACTION_ONE',
  Two = 'ACTION_TWO',
}
interface ActionOne {
  type: ActionTypes.One
  myStr: string
}
interface ActionTwo {
  type: ActionTypes.Two
  myBool: boolean
}
type AllActions = ActionOne | ActionTwo

// This is fine
const epic1 = (action$: ActionsObservable<AllActions>) => action$.ofType<ActionOne>(ActionTypes.One).map((action) => {})

// With lettable, doesn't work
const epic11 = (action$: ActionsObservable<AllActions>) =>
  action$.pipe(ofType<ActionOne>(ActionTypes.One), map((action) => {}))
```

![image](https://user-images.githubusercontent.com/1223799/34327794-30d95c30-e8ce-11e7-8bd3-911043e4c051.png)

When explicit generic is removed the type narrowing doesn't work 

```ts
// With lettable, without explicit generic, no errors, type narrowing doesn't work though
const epic11 = (action$: ActionsObservable) =>
  action$.pipe(ofType<ActionOne>(ActionTypes.One), map((action) => {}))
```

![image](https://user-images.githubusercontent.com/1223799/34327825-fb5db898-e8ce-11e7-9566-50252d087a7c.png)

Isn't there any way how to do this without explicit generics + make the lettable work ?

thanks
