### ISSUE TITLE
I just came accross this when I was using strongly typed actions.

### ISSUE THREAD

**Issue by femto11** [redux-observable/redux-observable#390]
**Do you want to request a *feature* or report a *bug*?**  

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsbin.com or similar.**

**What is the expected behavior?**

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

**Comment by jayphelps** [comment]
Hey there 👋 there isn’t any details to this issue. Can you edit?

**Comment by femto11** [comment]
I just came accross this when I was using strongly typed actions along with epics.

The Epic Interface is currently beeing defined like so: 

```
export declare interface Epic<T extends Action, S, D = any> {
  (action$: ActionsObservable<T>, store: MiddlewareAPI<S>, dependencies: D): Observable<T>;
}
```
which implies that the outgoing action is of the same type as the incoming one. I think that this might usually not be the case. So wouln't it be better to have an extended definition of this Interface like this:

```
export declare interface Epic<TSource extends Action, TResult extends Action, S, D = any> {
  (action$: ActionsObservable<TSource>, store: MiddlewareAPI<S>, dependencies: D): Observable<TResult>;
}
```

**Comment by jayphelps** [comment]
Gotcha. This is actually being discussed here https://github.com/redux-observable/redux-observable/issues/219

There’s some really good discussions in there why it’s the way it is and what we might do to change it. E.g. everything an epic outputs is also then provided as input recursively; this might not be obvious to people.

**Comment by jayphelps** [comment]
After taking a look at https://github.com/redux-observable/redux-observable/issues/219 can you add your thoughts there? That would be super helpful.

**Comment by femto11** [comment]
Sorry for starting another thread on this.

So having read #219 and having thought a little bit more about this issue, I now think that adding an additional template parameter for the outgoing action would solve only a part of the problem. In particular. when an epic is hooked onto more than only one specific action, we would need a separate template Parameter for all of them. Then you end up defining Epic Interfaces for 1 to n different input actions.  They do it for C# in that way or you wait for variadic template parameters in appearing in typescript. :(

So, I came up with a simpler solution. I declare a type that merges all possible action types for all the epics in that area. So basically:

```
type ActionsForEpics = 
  Action<void> | Action<SomePayload> | ...;

const someEpic = (): Epic<ActionsForEpics, {}> =>
  (action$, store): Observable<Action<SomePayload>> => 
    action$.ofType(actionTypes.SOMEACTION.toString())
    .map(action => resultingAction(somePayload));
```
As you see, in case the outgoing action I can even be very specific. 

Thank you for your help! Observables are fun, so this library is a pleasure for me.
