### ISSUE TITLE
Provide functional `ofType` operator

### ISSUE THREAD

**Issue by Sawtaytoes** [redux-observable/redux-observable#394]
**Do you want to request a *feature* or report a *bug*?**  
Feature

**What is the current behavior?**
```js
$action.ofType(ACTION_IDENTIFIER)
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**
Without mocking `ofType`, I cannot easily unit test my observables. Ideally, there would be a functional `ofType` operator without modifying `Observable` or `Subject`.

```js
import { filter } from 'rxjs/operators'

export const ofType = (
	requiredType => (
		filter(({ type }) => type === requiredType)
	)
)
```

This is all we need. Once we use this version of `ofType`, we can call the epic function in our unit tests with a standard RxJS observable.

**What is the expected behavior?**
```js
action$.pipe(ofType(ACTION_IDENTIFIER))
```

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
v0.17.0

**Comment by jayphelps** [comment]
We actually added a lettable version in 0.17.0

https://redux-observable.js.org/docs/basics/Epics.html#a-basic-example

![image](https://user-images.githubusercontent.com/762949/34646805-dee266fc-f326-11e7-9fd7-cdaec284820f.png)

Also, when doing tests I would recommend using ActionsObservable instead of regular Observable. It has `ActionsObservable.of()` as well as `ActionsObservable.from()`. This needs to be better documented.

```js
import { ActionsObservable } from 'redux-observable';
import { fetchUserEpic } from './somewhere/fetchUserEpic';

const mockResponse = { name: 'Bilbo Baggins' };
const action$ = ActionsObservable.of(
  { type: 'IGNORED' },
  { type: 'FETCH_USERS_REQUESTED' }
);
const store = null; // not needed for this epic
const dependencies = {
  getJSON: url => Observable.of(mockResponse)
};

// Adapt this example to your test framework and specific use cases
fetchUserEpic(action$, store, dependencies)
  .toArray() // buffers all emitted actions until your Epic naturally completes()
  .subscribe(actions => {
    assertDeepEqual(actions, [{
      type: 'FETCH_USER_FULFILLED',
      payload: mockResponse
    }]);
  });
```

***

Let me know if I'm misunderstanding of course 😄

**Comment by Sawtaytoes** [comment]
You're right, that's exactly what I was asking. I must've not understood what lettable operators were last time I read the docs and then skipped over that section every other time.

`ActionsObservable.of()` and `ActionsObservable.from()` seem really important. Thanks for abstracting that away! I can go back and remove my own functionality for this now.

**Comment by jayphelps** [comment]
@Sawtaytoes woot woot!
