### ISSUE TITLE
Add documentation for how we can send no action from our epic

### ISSUE THREAD

**Issue by Sawtaytoes** [redux-observable/redux-observable#395]
**Do you want to request a *feature* or report a *bug*?**  
Feature or Documentation

**What is the current behavior?**
As there is no documentation and only an error in the code, we need to be aware that all epics need to return an action. This means we'll be returning some sort of empty action `{ type: '' }` just to be on the safe side every time we map.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**
```js
export const addSomethingEpic = (action$, getState) => (
	action$
	.pipe(
		ofType(ADD_SOMETHING),
		map(({ id, something }) => (
			!getState().has(id)
			? addSomething(id, something)
			: noAction()
		)),
	)
)
```

**What is the expected behavior?**
We should only need the observable to return when it calculated an action; otherwise, it needs to stop so the subscriber on the other end doesn't trigger.

```js
export const addSomethingEpic = (action$, getState) => (
	action$
	.pipe(
		ofType(ADD_SOMETHING),
		map(({ id, something }) => (
			!getState().has(id)
			&& addSomething(id, something)
		)),
		filter(Boolean),
	)
)
```

This could be extrapolated even more using functional composition so we can use an operator that does the `filter(Boolean)` task for us. For example:
```js
import { filter } from 'rxjs/operators'

export const isValidAction = () => filter(Boolean)
```

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
0.17.0

**Comment by jayphelps** [comment]
This seems like a very good recipe, though I would caution that redux-observable defers to idiomatic RxJS, with `ofType` being the only notable exception.

So the RxJS operator `ignoreElements()` is the easiest way to have an epic that never emits anything, otherwise if you need to choose, using `filter` is the way to go.

Can you elaborate on `!getState().has(id)`? Typically state shouldn't contain any functions as it should ideally be serializable.

**Comment by jayphelps** [comment]
e.g. if you want to not emit an action based on state

```js
export const addSomethingEpic = (action$, getState) => (
  action$
  .pipe(
    ofType(ADD_SOMETHING),
    filter(({ id }) => someCheck(getState(), id)),
    map(({ id, styles }) => addSomething(id))
  )
)
```

**Comment by Sawtaytoes** [comment]
In the app I'm currently working on, I've run into a lot of instances where my state needs to be a `Map`. Normally I'd use an object, but I found I could pass components directly into a map as the `id`.

**createReducer.js**
```js
export default (reducerActions, initialState) => (
	(state = initialState, action) => (
		reducerActions[action.type]
		? reducerActions[action.type](state, action)
		: state
	)
)
```

**reducers/something.js**
```js
import createReducer from 'utils/createReducer'

export const ADD_SOMETHING = 'STYLES::ADD_SOMETHING'
export const REMOVE_SOMETHING = 'STYLES::REMOVE_SOMETHING'

export const addSomething = (id, something) => ({
	id,
	something,
	type: ADD_SOMETHING,
})

export const removeStyles = id => ({
	id,
	type: REMOVE_SOMETHING,
})

export const initialState = new Map()

export const reducerActions = {
	[ADD_SOMETHING]: (
		(prevState, { id, something }) => (
			new Map(prevState)
			.set(id, something)
		)
	),

	[REMOVE_SOMETHING]: (
		(prevState, { id }) => {
			const state = new Map(prevState)

			state.delete(id)

			return state
		}
	),
}

export default createReducer(reducerActions, initialState)
```

At the component level, it looks like this:
```js
import React, { Fragment } from 'react'

import LifeCycles from 'components/helpers/LifeCycles'

export const SomethingManager = ({ addSomething, component, something, removeSomething }) => (
	<Fragment>
		<LifeCycles
			componentWillMount={() => addSomething(component, something)}
			componentDidUnmount={() => removeSomething(component)}
		/>
	</Fragment>
)

export const SomethingComponent = () => (
	<SomethingManager component={SomethingComponent} something="something" />
)
```

In this case, I can directly pass the component itself in as an ID. Since it's already got a memory reference, I don't have to bloat up my application state with component name strings.

**Comment by Sawtaytoes** [comment]
In your example, you filter on the boolean check prior to mapping. Makes a lot of sense and should've been the pattern I was using all along!

I appreciate you quickly responding with a far better solution; although, I think this kind of solution should really be documented somewhere. When I was playing around with redux-observable, I randomly got an error saying something needed to return an action object, and I had to come up with the "best practice" myself rather than being able to reference it in the docs.

**Comment by jayphelps** [comment]
@Sawtaytoes you're welcome! The error you got is from redux, since everything your epic emits is dispatched. `rootEpic(action$, store).subscribe(store.dispatch)`

**Comment by Sawtaytoes** [comment]
Ah yeah, I wonder if this could be solved better if I wrote an article about using redux-observable, things to look out for, and simple solutions to common problems. The fact that it does a dispatch directly with whatever the observable returns is key to understanding how an epic works. Another concept that was important to know is the epic function itself is only called once. At that point, the `action$` observable takes over.

**Comment by jayphelps** [comment]
👍 I would **love** it if you could wordsmith the docs, even just a little bit, to make them more clear. It's hard for me to know for sure what's obvious, what's not, etc.

**Comment by ZheyangSong** [comment]
simply do return `Observable.empty()` in a flattening operator will let the store do nothing.

**Comment by Sawtaytoes** [comment]
🧛

@ZheyangSong I've ended up doing that in later revisions of my epics.

@jayphelps 

Instead of wordsmithing the docs, I ended up writing an article about common use cases:
https://medium.com/@Sawtaytoes/redux-observable-can-solve-your-state-problems-15b23a9649d7

After reading what I wrote before, that was my plan all along!

This could be linked to as a helpful resource from the docs. The Redux documentation has [lots of examples](https://redux.js.org/introduction/examples), so I'd think that's what Redux-Observable needs too especially considering how most of my early problems came from being greenfield to RxJS in general.

It also seems like the docs have improved since v1.0.0.

**Comment by squirrelsRduck** [comment]
cool, thanks, this thread and the ignoreElements() operator that @Sawtaytoes provided helped me a bunch.  im coming from an Angular background and in their redux library, ngrx, there's a decorator used on each "epic" (though in their lingo they're effects, not epics).  and in that decorator, you can specify {dispatch: false} which essentially puts a ignoreElements at the end of your rxjs operator chain
