### ISSUE TITLE
how can I measure the epics duration time when running complete

### ISSUE THREAD

**Issue by wjljack** [redux-observable/redux-observable#400]
In the majority situation, epics listen an action and emit an action,many async task in it ,I want to measure the duration of epics  between the action in  and action out . How can I  do this,need urgently,thank you.

**Comment by jayphelps** [comment]
Hey @wjljack 👋 If you ask on StackOverflow someone may be able to help 🙂 We ask that the issue tracker only be used to report bugs. Thanks!

https://stackoverflow.com/questions/tagged/redux-observable
