### ISSUE TITLE
Types not Narrowed through ofType [TypeScript]

### ISSUE THREAD

**Issue by cjol** [redux-observable/redux-observable#417]
Using `action$.ofType(...)` does not narrow the type of the ActionsObservable. Instead, the resulting Observable has the same type as `action$`, which means any subsequent operators don't have access to much useful type information. For example, this gives a type error on the access to `action.firstProp`: 

```
export const pingEpic: Epic<MyActions, StateType> = (action$, store) =>
  action$
    .ofType("PING")
    .delay(1000)
    .map((action): ActionTwo => ({
      type: "PONG",
      secondProp: action.firstProp + " 2"
    }));
```

Demo: https://stackblitz.com/edit/typescript-f4qzhx?file=ping-pong.ts

Note that in the demo above you can get rid of the type error by adding a type annotation to the map (e.g. `.map((action:ActionOne):ActionTwo => ({...})`. This only works because strict mode is not enabled on StackBlitz.

Instead, a new type definition is needed for ofType:

```diff
-   ofType(...key: T["type"][]): ActionsObservable<T>;
+   ofType<S extends T>(...key: S["type"][]): ActionsObservable<S>;
```

Making this change on my local copy of the .d.ts file allows me to do this, and have access to all the lovely type information:

```
export const pingEpic: Epic<MyActions, StateType> = (action$, store) =>
  action$
    .ofType<ActionOne>("PING")
    .delay(1000)
    .map((action): ActionTwo => ({
      type: "PONG",
      secondProp: action.firstProp + " 2"
    }));
```

What do you think?

**Comment by jayphelps** [comment]
@cjol Can you take a look at the latest code in master? https://github.com/redux-observable/redux-observable/commit/63b2accd0a4ff3d8665a0e66a653ad819a4f62ec

```ts
ofType<R extends T = T>(...key: R['type'][]): ActionsObservable<R>;
```

I believe this basically the same thing you're asking for right? It hasn't made it into a release yet, but I expect one this weekend.

Let me know if I'm confused, and this is different 😄 

***

FYI for everyone coming here later: the latest word direct from the TypeScript team was that it was not possible to automatically narrow the union without some sort of explicit type param hint. So for now, to narrow you must explicitly pass the correct type param.

* https://github.com/Microsoft/TypeScript/issues/17915
* https://stackoverflow.com/questions/46312206/narrowing-a-return-type-from-a-generic-discriminated-union-in-typescript/46313086#46313086

**Comment by cjol** [comment]
Yes, this looks great. Glad to hear you're one step ahead of me!

**Comment by jayphelps** [comment]
Released https://github.com/redux-observable/redux-observable/releases/tag/v0.18.0
