### ISSUE TITLE
Clean up / update dependencies

### ISSUE THREAD

**Issue by cilice** [redux-observable/redux-observable#423]
Hey!

While I was updating dependencies at a project for work, I noticed redux-observable installed `gitbook-plugin-github` because it's in the [dependencies](https://github.com/redux-observable/redux-observable/blob/master/package.json#L108) but it's also installed as a [devDep](https://github.com/redux-observable/redux-observable/blob/master/package.json#L92)

I cloned redux-observable and noticed some other issues like `eslint` using [outdated config options](https://travis-ci.org/redux-observable/redux-observable/jobs/340541662#L3050), webpack still being in the 2.x version and more outdated libraries.
Additionally, `babel-preset-es2015` and not `babel-preset-env` is used, which is also deprecated.

Additional things I'd also like to address:
- move from mocha/sinon/chai to jest
- use prettier
- commit a .lock file? I'm not sure why this has been disabled. I'm fine with either `yarn` or `npm`, both are stable now and npm's initial problems are long fixed

We should fix this, so I thought I'd create an issue to ask how to think about all these changes and updates and whether I'd be allowed to start some PRs.

**Comment by jayphelps** [comment]
fixed in #425 and #424 thanks again!

**Comment by oliviertassinari** [comment]
*Note, the fix wasn't released yet*
![capture d ecran 2018-04-26 a 13 07 46](https://user-images.githubusercontent.com/3165635/39302414-db5bd748-4952-11e8-9546-3cfb0622adf0.png)

**Comment by evertbouw** [comment]
@oliviertassinari Correct, the dependency was removed after the 0.18 release and we haven't had a non-alpha release since. Version 1.0 should be near!
