### ISSUE TITLE
Outdated webpack version

### ISSUE THREAD

**Issue by cilice** [redux-observable/redux-observable#434]
Currently, webpack is used to create the UMD builds but webpack is still on version `2.7.0` while `3.11.0` is the out.

<img width="585" alt="screen shot 2018-02-22 at 02 57 13" src="https://user-images.githubusercontent.com/835588/36516579-f7a24668-177e-11e8-9165-570de76c12ee.png">

Also, the examples could use a webpack update as well to promote best practises.

- examples/navigation has webpack@1
- examples/redux-observable-cancellable-counter and examples/redux-observable-shopping-car have webpack 3, but it's both a devDep and a dep 

---

As an alternative to that, we could use rollup https://github.com/rollup/rollup to bundle redux-observable instead of gulp+babel and webpack for the builds.

**Comment by jayphelps** [comment]
Would a newer version of webpack buy us improvements in size or something else? Similar to the mocha stuff, "if it ain't broke don't fix it", but even if it makes no practical difference you're welcome to upgrade them!

> Also, the examples could use a webpack update as well to promote best practises.

The examples are definitely in need of love in general!

**Comment by jayphelps** [comment]
We're on the latest webpack now 😄
