### ISSUE TITLE
Migration to 1.0.0 documentation

### ISSUE THREAD

**Issue by wmaurer** [redux-observable/redux-observable#467]
**Do you want to request a *feature* or report a *bug*?**  

Possible documentation bug

**What is the current behavior?**

Looking at the migration documentation, the following code snippet is given:

```
const fetchUserEpic = (action$, state$) =>
  action$.pipe(
    ofType(FETCH_USER),
    withLatestFrom(
      state$.pipe(
        take(1), // We don't want to react to changes in this example
      )
    ),
    mergeMap(([action, state]) =>
      getJson(`/users/${action.id}`, { 'Authorization': `Bearer ${state.authToken}` }).pipe(
        map(respose => fetchUserFulfilled(response))
      )
    )
  );
```

From my understanding of RxJS, the `.pipe(take(1))` is unnecessary because `withLatestFrom` will only take one single emitted value from `state` (per action). Is my understanding correct?

**What is the expected behavior?**

If my understanding is correct, the documentation could be changed as follows:
```
const fetchUserEpic = (action$, state$) =>
  action$.pipe(
    ofType(FETCH_USER),
    withLatestFrom(state$),
    mergeMap(([action, state]) =>
      getJson(`/users/${action.id}`, { 'Authorization': `Bearer ${state.authToken}` }).pipe(
        map(respose => fetchUserFulfilled(response))
      )
    )
  );
```

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

n/a

**Comment by jayphelps** [comment]
You're absolutely right! Thank you for noticing! While they are not the same, using take(1) in this case is actually _wrong_ and not what we want as it will never update the state after the first time.
