### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by dmytro-lymarenko** [redux-observable/redux-observable#468]
This happens because `rxjs` doesn't have `merge` import as it is done here:

https://github.com/redux-observable/redux-observable/blob/cd39eb6da15bf963523b4c64861edfd1cbe8afd0/src/combineEpics.js#L1

We should use this `import { merge } from 'rxjs/observable/merge';` instead of. (in v0.18.0 it was correct https://github.com/redux-observable/redux-observable/blob/f632eaae81b1b3d13b6e90687931f1a5863b0e0d/src/combineEpics.js#L1)

I'm using rxjs@5.5.8

**Comment by evertbouw** [comment]
Hey! Redux-observable v1-alpha is meant to be used with Rxjs v6. You can install `rxjs@6.0.0-rc.0` or lock redux-observable to `0.18.0` for now.

**Comment by jayphelps** [comment]
Please lmk if we're mistaken or we can help!

**Comment by andrii-maglovanyi** [comment]
@jayphelps looks like it still uses version 0.18.0 when I try to install 1.0.0-aplha.2
`Uncaught TypeError: You must provide a root Epic to createEpicMiddleware
    at createEpicMiddleware (createEpicMiddleware.js?629a:26)`
