### ISSUE TITLE
Redux 4 Support

### ISSUE THREAD

**Issue by jayphelps** [redux-observable/redux-observable#478]
This issue will track overall progress and issues for supporting redux v4. I have almost all the tests passing now and a WIP PR is imminent once I split off some changes that I also made that are related to synchronous emission on start up, but I think need to be done as follow ups as they might need community input to be intuitive.

Feel free to file individual tickets if you find something, just know tha I imagine a majority are already covered by our existing tests and so are known.

Related: #449

@evertbouw

**Comment by nairihar** [comment]
Hi, I have tried to run tests using Redux 4 and got 6 errors, I have investigated the issues.

When you doing "deep.equal" using "chai" module, you also add this in every test
`{ type: '@@redux/INIT' }`

But in log you can find redux init action value like this
"type": "@@redux/INITh.f.7.9.g"
"@@redux/INITh.f.7.9.g"
and etc ...

so test will fail because  "@@redux/INITh.f.7.9.g" not equal to  '@@redux/INIT' 

I have added two functions which filtering the Redux init value.


```
const isReduxInitAction = (action) => !!action.type.match(/@@redux\/INIT/);
const removeReduxInit = (actions) =>
  actions.filter(action =>
    !isReduxInitAction(action)
  );

```

Actually, all errors not like this, using these functions you can fix part of them.

**Comment by nairihar** [comment]
Please look this changes in my forked repo
https://github.com/nairihar/redux-observable/commit/dc799a4570696946f28b60d49af8cb4655eb61c3

**Comment by jayphelps** [comment]
Hey @nairihar I super appreciate your help though you definitely should hold off as I’ve galready got everything working and there were also changes that had to be made to behavior.

**Comment by nairihar** [comment]
thanks @jayphelps, I will wait for new releases of redux-observable which will work with redux 4

**Comment by evertbouw** [comment]
@nairihar btw for tests it would be fine to `import { __DO_NOT_USE__ActionTypes } from 'redux'` imo

**Comment by nairihar** [comment]
yes @evertbouw, cool, I did not know about it.

**Comment by ohjames** [comment]
I've been using the current release with redux 4, the only bug I noticed is about emitting events during middleware initialisation. So I added an `INIT` action I dispatch at startup use a `pipe(first(), switchMap(...))` for these cases to ensure the emitted actions are delayed until after middleware initialisation.

**Comment by ckrasi-acx** [comment]
@jayphelps any news on progress?

**Comment by evertbouw** [comment]
I've done some initial testing with https://github.com/redux-observable/redux-observable/pull/501 and I think it's ready for a new prerelease build.

I've also worked on docs for a bit, that'll need more work. Big thing I didn't touch yet is all the jsbin examples. Is there an easy or right way to update those?

**Comment by jayphelps** [comment]
redux v4 is supported as of [1.0.0-alpha.3](https://github.com/redux-observable/redux-observable/blob/master/CHANGELOG.md#100-alpha3-2018-06-01), with the latest release now being 1.0.0-beta.1

I'm not sure if #449 is still an issue, but for any other issues please create new tickets 😄
