### ISSUE TITLE
Support rxjs v6

### ISSUE THREAD

**Issue by Tomekmularczyk** [redux-observable/redux-observable#491]
**Do you want to request a *feature* or report a *bug*?**  

Feature. Support for rxjs v6. 

**What is the current behavior?**

Currently, imports are breaking. If that's all it takes to migrate it I can prepare PR myself.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

v.0.18.0

**Comment by evertbouw** [comment]
For RxJS 6 support you can try redux-observable@next. This will also change the store to state$, take a look at https://redux-observable.js.org/MIGRATION.html to get started.

**Comment by Tomekmularczyk** [comment]
@evertbouw cool I didn't know about it. Are there plans for when it's going to be released?

**Comment by evertbouw** [comment]
@jayphelps was working on Redux 4 support and a few other things. I'll let him answer

**Comment by jayphelps** [comment]
redux v4 with rxjs v6 is coming in the 1.0.0 of redux-observable, you can try it out and start the migration using `npm install --save redux-observable@next`, the latest `next` being [1.0.0-beta.1](https://github.com/redux-observable/redux-observable/blob/master/CHANGELOG.md#100-beta1-2018-06-04) as of this writing. 🎉
