### ISSUE TITLE
Should state$ already use distinctUntilChanged() ?

### ISSUE THREAD

**Issue by jayphelps** [redux-observable/redux-observable#497]
Right now the new state$ observable doesn't do any kind of checking if the state really did update, so if an action is dispatched but no state updated, state$ _will still emit the same state as before_. This could be potentially be unexpected and seems like regardless it's undesirable.

Since redux users are _supposed_ to use some sort of immutable data pattern in doing their reducer state updates, we could use `distinctUntilChanged()` to only notify state$ observers when the state tree has actually changed. The only problem I see is that I have many times seen people not follow 100% immutable patterns, in which case this decision would lead to hard-to-debug stale bugs..but these same bugs would exist in libraries like react-redux which also rely on immutability/shallow comparisons, so I'm inclined to say we should do it.

Thoughts?

**Comment by rgbkrk** [comment]
I'm totally cool with building `distinctUntilChanged` in, especially if that's a similar assumption for `react-redux`.

**Comment by evertbouw** [comment]
You always want to do `distinctUntilChanged` so I agree it's a good idea to build it in. But then users won't be trained to add it everywhere themselves so I think it would be easy to miss elsewhere. Should we ship an operator like `select` from ngrx? It's basically `pipe(map(/* selector */), distinctUntilChanged())`

**Comment by deanius** [comment]
But suppose you want to provide a zip of {action$, state$}? They no longer match up - got a solution to that?

**Comment by evertbouw** [comment]
Since currently action$ and state$ emit the same number of items and at the same time, you can use `action$.pipe(withLatestFrom(state$))` to achieve the same result.

**Comment by jayphelps** [comment]
> But suppose you want to provide a zip of {action$, state$}? They no longer match up - got a solution to that?

As @evertbouw mentioned `withLatestFrom` might be what you're looking for, or perhaps `combineLatest` might be more close to `zip` except not needing 1:1 emission patterns.

`withLatestFrom` is going to use the source you apply it to as the signal to continue, e.g. `action$.pipe(withLatestFrom(state$))` would use actions as the notifier, emitting an array containing the latest values from both `[action, state]`; when state$ emits it just updates the internal cache but doesn't use it as a notifier to emit.

`combineLatest` on the other hand uses any of the provides sources as notifiers, waiting for _at least_ one emission from each but after that no longer synchronized (`zip` always synchronizes 1:1 emissions from each source)

```ts
const somethingEpic = (action$, state$) =>
  combineLatest(action$, state).pipe(
    tap(([action, state) => console.log(action, state)
    ignoreElements()
  );
```

**Comment by deanius** [comment]
Thanks for the idea, and that thoughtful explanation @jayphelps !

**Comment by wldcordeiro** [comment]
This seems like a good optimization. Definitely support putting `distinctUntilChanged` in.
