### ISSUE TITLE
1.0.0-beta.1 - createEpicMiddle type is broken, not accepting rootEpic anymore

### ISSUE THREAD

**Issue by wmira** [redux-observable/redux-observable#516]
**Do you want to request a *feature* or report a *bug*?**  

bug

**What is the current behavior?**

createEpicMiddleWare type on index.d.ts is only accepting options
```typescript
interface Options<D = any> {
  adapter?: Adapter;
  dependencies?: D;
}

export declare function createEpicMiddleware<T extends Action, O extends T = T, S = void, D = any>(options?: Options<D>): EpicMiddleware<T, O, S, D>;
```
**What is the expected behavior?**

createEpicMiddleware should accept a rootEpic

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

1.0.0-beta.1 
works on 1.0.0-alpha2

Was there any update on the api?

**Comment by evertbouw** [comment]
The types are correct, you must now call `epicMiddleware.run(rootEpic)`, see https://redux-observable.js.org/MIGRATION.html#setting-up-the-middleware.

**Comment by wmira** [comment]
@evertbouw thanks.
