### ISSUE TITLE
Add ability to add new delegator

### ISSUE THREAD

**Issue by alisd23** [redux-observable/redux-observable#52]
In an app which uses code splitting, reducers might be loaded lazily as the user navigates. It would nice to be able to add delegators to the root delegator after the app is run initially to support these kinds of applications.

**Comment by istarkov** [comment]
You could just `dispatch` loaded delegator, and it will work the same as processor delegators.
```
dispatch((action$, store) => action$.blabla(....));
```
See the source https://github.com/redux-observable/redux-observable/blob/master/src/reduxObservable.js#L14

**Comment by martypenner** [comment]
That's really only for thunkservables, though. The processor [here](https://github.com/redux-observable/redux-observable/blob/master/src/reduxObservable.js#L10) is the root delegator/process manager.

**Comment by istarkov** [comment]
@martypenner for now there is just one difference from
[this](https://github.com/redux-observable/redux-observable/blob/master/src/reduxObservable.js#L11)
```
processor(actionsObs, store).subscribe(store.dispatch);
```
and [this](https://github.com/redux-observable/redux-observable/blob/master/src/reduxObservable.js#L15-L17)
```
let obs = from(action(actionsObs, store));
let sub = obs.subscribe(store.dispatch);
return sub;
```

you could unsubscribe from second.
Both will work in exactly the same manner. So having that your delegators are loadable, you can use `dispatch` variant

**Comment by istarkov** [comment]
In the future having [this comment](https://github.com/redux-observable/redux-observable/issues/44#issue-160238580) `I, personally, would like to deprecate the thunkservable method prior to RC, but I feel like @jayphelps might have different opinions.` this method could become a problem, but now it work.

**Comment by jayphelps** [comment]
(delegators == old term for what we're currently calling "process managers")

Because process managers just return a stream, you can already implement this yourself--though we do intend to support something like `replaceManager(newRootManager)` which would just do the same thing you could do under the hood.

When I get a sec I'll post the code to do this in the meantime.

**Comment by istarkov** [comment]
```javascript
const dynamicD$ = new Rx.Subject();
const combineDelegators = (dynamicDelegators$, ...delegators) => (actions, store) =>
    dynamicDelegators.mergeMap(dynamicD => dynamicD(actions, store))
    	.merge(...(delegators.map((delegator) => delegator(actions, store))));

// .....
// to add call
dynamicD$.next((action$, store) => blabla)
```

**Comment by alisd23** [comment]
Ahh ok I see, clever. I agree it should definitely be built in functionality, like the redux *combineReducers*. Cheers guys

**Comment by alisd23** [comment]
Is it worth opening a pull request for a built in version of this now? or is the code likely to change a lot soon?
I don't mind implementing it if you think its worth doing.

**Comment by alisd23** [comment]
I've opened a pull request for this now. Let me know what you think, anything that needs changing. I've heard the naming is likely to change so can just leave it open for now until that's been decided.

**Comment by jayphelps** [comment]
Check out https://github.com/redux-observable/redux-observable/pull/75
