### ISSUE TITLE
RXJS ajax.delete doesnt send Authorization header

### ISSUE THREAD

**Issue by kondricz** [redux-observable/redux-observable#529]
**Do you want to request a *feature* or report a *bug*?**  

BUG

**What is the current behavior?**

RXJS ajax.delete doesnt send Authorization header from the browser. Returns with 401 - Not Authorized.
I have read different opinions whether we should send a body in a delete request, however our back-end works like this at the moment, and they expect a body. However I tested without a body and I am getting back the same problem.

```

export const deleteMembersEpic = (action$, store) => action$
  .ofType(DELETE_MEMBER)
  .switchMap(action => {
    const token = getLoginToken(store.getState());
    return ajax.delete(`${URL_API}/${ENDPOINT_API_EMPLOYEES}`, {
      employees: [action.payload]
    }, {
      'Content-Type': 'application/json',
      Authorization: token
    }).map(memberDeletedSuccesfully)
      .catch(inValidRequest);
  });

```

**What is the expected behavior?**

Adding members which is 90% the same code works as expected.

```

export const addMembersEpic = (action$, store) => action$
  .ofType(ADD_NEW_MEMBER)
  .switchMap(action => {
    const token = getLoginToken(store.getState());
    return ajax.post(`${URL_API}/${ENDPOINT_API_EMPLOYEES}`, {
      employees: [action.payload]
    }, {
      'Content-Type': 'application/json',
      Authorization: token
    }).map(memberAddedSuccesful)
      .catch(inValidRequest);
  });

```

In the moment I change from ``` ajax.post() ``` to ```ajax.delete() ``` it doesnt send the authorization header anymore.

Funny enough the request works from POSTMAN.

![image](https://user-images.githubusercontent.com/30053409/41411333-beae537c-6fdc-11e8-9733-40498f24c764.png)

It gives back 500 - Internal Server Error (as expected for now :) )

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

WIN 10 64x

    "redux": "3.7.2",
    "redux-observable": "0.18.0",
    "rxjs": "5.5.8"

**Comment by evertbouw** [comment]
Issues with Rxjs belong here: https://github.com/ReactiveX/rxjs since that community is larger you can get faster/better responses.

The ajax delete function in Rxjs doesn't support a body, so the object you have as a body gets used as the headers

```ts
export declare function ajaxDelete(url: string, headers?: Object): Observable<AjaxResponse>;
```

What you can do is call the root ajax with a whole request object

```js
import { ajax } from "rxjs/ajax";
ajax({ method: "DELETE", url, body, headers });
```

**Comment by kondricz** [comment]
Hey,

Thanks! This will be the problem, I also assume. I will close it.

Regards,
Kopppany
