### ISSUE TITLE
ble

### ISSUE THREAD

**Issue by pawelbujna** [redux-observable/redux-observable#549]
**Do you want to request a *feature* or report a *bug*?**  

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**

**What is the expected behavior?**

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

**Comment by jayphelps** [comment]
Hey there please provide info if you’re reporting a bug
