### ISSUE TITLE
React: Rxjs/Redux-Observable IE exception thrown but not caught

### ISSUE THREAD

**Issue by sandy0201** [redux-observable/redux-observable#554]
Hi,

I have some code for an epic. When I get a 401 error, it is supposed to call a callback function and return an Observable stream which will pop up an error modal. This works in all browsers, except for IE (Internet Explorer).

This is the error I get:
[https://i.stack.imgur.com/WiIrv.png](error screenshot)

Versions of relevant dependencies I am using:
 - react: 16.4.1
 - react-dom: 16.4.1
 - react-redux: 5.0.6
 - redux: 3.7.2
 - redux-observable: 0.17.0
 - redux-thunk: 2.2.0
 - rxjs: 5.5.6

Here's the snippet:
```js
export const epic = (action$) =>
     action$.ofType(SUBMIT)
        .mergeMap(action => {
            return Observable.ajax({
                url: `${Config.rootUrl}/${Config.apiContext.registration}/${Config.apiVersion}${Config.apiUri.captureField}`,
                method: 'POST',
                crossDomain: true,
                headers: {
                    ...Config.headers,
                    Authorization: `Bearer ${sessionStorage.getItem('token')}`,
                    'Correlation-Id': getUuid(),
                },
                body: {
                    saId: action.payload.args.field.replace(/[\s]/g, ''),
                },
            })
                .map((response) => {
                    action.payload.callback(response);

                    return {
                        type: CAPTURE,
                        payload: response,
                    };
                })
                .catch(({ xhr }) => {
                    // IE does not come in here at all when 401 error occurs, but works with error 400, 500, etc.
                    action.payload.callback(xhr);

                    return Observable.of(errorHelper(ERROR, xhr));
                });
        });
```

What's weird is that IE does not run the catch statement (as commented in code) at all when 401 error occurs, but it does when other errors 400, 500, etc. occur.

How can I debug this?

**Comment by ksaldana1** [comment]
This seems like less of an issue with redux-observable, and more of an RxJS problem (specifically with `rxjs/ajax` and error handling in IE). I'd post the issue over on their repo / gitter for help. I've run into issues with `rxjs/ajax` and [error handling](https://github.com/ReactiveX/rxjs/issues/3606) before.

**Comment by evertbouw** [comment]
Looks like this issue was already posted there as well. https://github.com/ReactiveX/rxjs/issues/3949 It is indeed a better fit there, closing this.

**Comment by sandy0201** [comment]
Ok cool, thanks @ksaldana1  :)
Yes, thank you @evertbouw :)
