### ISSUE TITLE
Typescript error when Epic has state$

### ISSUE THREAD

**Issue by hackhat** [redux-observable/redux-observable#555]
**Do you want to request a *feature* or report a *bug*?**  

bug
**What is the current behavior?**

When my epic has state I got this typescript error:

![image](https://user-images.githubusercontent.com/11173732/43440177-ecd7727c-94c8-11e8-9b48-7242cc6ef2a8.png)

Not sure why is forcing me to have the `S` as void.

Here are the type definitions:

```
export declare interface Epic<T extends Action, O extends T = T, S = void, D = any> {
  (action$: ActionsObservable<T>, state$: StateObservable<S>, dependencies: D): Observable<O>;
}

export interface EpicMiddleware<T extends Action, O extends T = T, S = void, D = any> extends Middleware {
  run(rootEpic: Epic<T, O, S, D>): void;
}

```

TS Error code:

`const rootEpic: Epic<AppAction, AppAction, IAppState, any> = createClientEpic(api, store);`

TS Is fine:

`const rootEpic: Epic<AppAction, AppAction, any, any> = createClientEpic(api, store);`

**What is the expected behavior?**

No TS error.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

version: 1.0.0-beta.0

**Comment by hackhat** [comment]
ok, just figured out I needed to add types to `createEpicMiddleware`:

`
    const epicMiddleware = createEpicMiddleware<AppAction, AppAction, IAppState, void>();

`

**Comment by daveking999** [comment]
Hi @hackhat ,
Can you please post your full solution for adding the types ?

Thanks

**Comment by hackhat** [comment]
@daveking999 

Is like this:

  createStore() {
    const epicMiddleware = createEpicMiddleware<AppAction, AppAction, IAppState, void>();
    this.store = createStore(reducers, initialState, compose(
      reduxBatch,
      applyMiddleware(
        epicMiddleware,
      ),
      reduxBatch,
    ));
    const rootEpic = createServerEpic(this.store);
    epicMiddleware.run(rootEpic);
  }
