### ISSUE TITLE
createEpicMiddleware typescript definition should set state as any instead of void

### ISSUE THREAD

**Issue by duvet86** [redux-observable/redux-observable#564]
I'm using redux-observable with typescript and I defined an Epic that requires the state$:
```
const saveGraphEpic = (
  action$: ActionsObservable<GraphSaveChangesAction>,
  state$: StateObservable<IState>
) =>
  action$.pipe(
    ofType(GraphSaveActionTypes.GRAPH_SAVE_REQUEST),
    mergeMap(() => {
      const {
        sessionReducer: {
          session: { TenantId, SessionId, QueryGraphId },
          graph
        }
      } = state$.value;

      return saveGraphObs(TenantId, SessionId, QueryGraphId, graph, true).pipe(
        map(() => graphSaveChangesSuccess()),
        catchError(error => handleException(error))
      );
    })
  );
```

But the run method of the **createEpicMiddleware** throws an error:
![image](https://user-images.githubusercontent.com/5604548/44618474-26481e00-a8a9-11e8-9ab0-f5ee34585004.png)

I solved the issue adding parameters to the middleware, in particular the RootState one:
`const epicMiddleware = createEpicMiddleware<ActionInput, ActionOutput, RootState>();`

And this is the typescript definition of createEpicMiddleware: 
`export declare function createEpicMiddleware<T extends Action, O extends T = T, S = void, D = any>(options?: Options<D>): EpicMiddleware<T, O, S, D>;`

Shouldn't S = any ?

**Comment by jayphelps** [comment]
Any opinion @ajcrites?

Original PR #473

**Comment by ajcrites** [comment]
`S = void` was done to default to creating epics where state is not used which I think are more common. In cases where state is used, I don't think we should default to `any`. I prefer enforcing the addition of a type, e.g. `AppState` (or `RootState` or whatever) ... or you could use `any` if you like, but then you lose type safety too.

Let me know if this is an error.

**Comment by duvet86** [comment]
Agreed, my bad.
Actually adding the state parameter forced me to review my reducers and produce better typed code.
As far as it concerns me the issue can be closed.
Thank you for your time and keep up the good work.
