### ISSUE TITLE
takeUntil operator won't cancel the observable

### ISSUE THREAD

**Issue by eyal0803** [redux-observable/redux-observable#581]
**Do you want to request a *feature* or report a *bug*?**  
Not sure it's a bug, just couldn't figure out how to get the `takeUntil` operator to work. [StackOverflow ](https://stackoverflow.com/questions/52919207/cant-get-takeuntil-to-cancel-the-request) and [Gitter](https://gitter.im/redux-observable/redux-observable?at=5bcdf454435c2a518ee9a97f) weren't helpful.

**What is the current behavior?**
`takeUntil` doesn't cancel the observable.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**
Could be a bit hard to reproduce right now but will do if needed.

**What is the expected behavior?**
Upon typing inside an `<input>` a `SEARCH` action is dispatched. After a successful response is received a `SEARCH_SUCCESS` action is dispatched. The user is able to cancel the request, and when he does, a `CLEAR_SEARCH_RESULTS` action is dispatched.

Here's the epic:
```
const searchEpic = action$ =>
    action$.ofType(SEARCH).pipe(
        debounceTime(500),
        switchMap(({ payload }) =>
            search(query).pipe(
                map(({ response }) => SearchActions.searchSuccess(response)),  // dispatches SEARCH_SUCCESS
                takeUntil(
                    action$.ofType(CLEAR_SEARCH_RESULTS)
                )
            )
        )
    )
```

And here's a log of the dispatched actions:

1. `SEARCH`
2. `SEARCH`
3. `SEARCH`
4. `SEARCH_SUCCESS`
5. `SEARCH`
6. `SEARCH`
7. `SEARCH`
8. `CLEAR_SEARCH_RESULTS`
9. `SEARCH_SUCCESS`

The last `SEARCH_SUCCESS` shouldn't happen.

Thanks in advance.

**Comment by eyal0803** [comment]
Here's a demo repo: https://github.com/eyal0803/job-search

**Comment by evertbouw** [comment]
Answered on Gitter but adding here as well should anyone see this. This is a race condition, when SEARCH comes in the epic will wait for 500ms before it starts listening to CLEAR_SEARCH_RESULTS.

I found some solutions here https://stackoverflow.com/questions/45513629/debouncing-and-cancelling-with-redux-observable
