### ISSUE TITLE
Multiple AJAX calls but reducer.success only got invoked once

### ISSUE THREAD

**Issue by ktei** [redux-observable/redux-observable#594]
I'm quite new to this thing so I actually don't know whether this is a bug or I did something silly, buy here's what I did.

I have a List Component A with an Epic that loads all the items in this List. Each item in this List will use Component B, so it goes like this:
```
class A extends React.Component {
  render() {
    return (
      <div>{this.props.items.map(i => <B key={i.name} item={i} />)}</div>
    )
  }
}
```

I have another Epic that loads deatils of an item. So what I did was during comopnentDidMount of B, I start this Epic immediately:
```
class B ... {
  componentDidMount() {
    this.props.requestItemDetail(this.props.item.name);
  }
}
```
As you can imagine, if I have 50 items in the List, then 50 AJAX calls will be made simultaneously because each B comopnent will be mounted superfast. My problem is: the AJAX calls are all fine, but my onSuccess reducer is only triggered once after all the AJAX calls are finished. It's a bit strange, because from what I understand, the Epic will keep listening to my GetItemDetails.request action stream, and it does fire AJAX but somehow it buffers all the 50 responses and in then end it triggers my reducer once, for which I expect 50 times.

Is this a bug or... if it is not, could you tell me what's going on? Thank you

**Comment by evertbouw** [comment]
Hmmm I'm not sure. Can you post the epic?

**Comment by evertbouw** [comment]
You are using `switchMap`, this operator will cancel the previous inner observable when the source observable emits again. If you replace this with `mergeMap` it should work fine.

**Comment by ktei** [comment]
@evertbouw Got it. Thank you very much!
