### ISSUE TITLE
Overlap and differences of redux-observable and redux-stream

### ISSUE THREAD

**Issue by mcoetzee** [redux-observable/redux-observable#60]
Hey guys,

It's me, that guy that wrote and experimented a bit with state streams. Thanks again @blesh for your feedback, it was much appreciated seeing as I'm a newcomer to the open source world. I actually took your feedback to heart about how there is space for both RxJS and Redux and how `Observable.from(store)` just works™. Long story short I revisited Redux again and realised that I could write a Redux store enhancer, which I have been experimenting with for the past 2 weeks. Recently I saw you guys over here at redux-observable have deprecated your `thunk-servable` approach, to be replaced by the `action managers`. This is actually very interesting as there is a lot of overlap with the Redux store enhancer approach I am experimenting with.

The experimental library is called **redux-stream** and can be found over here: https://github.com/mcoetzee/redux-stream

Its main focus is on composing side effect streams (as apposed to state streams). What you guys call action managers I called side effect producers. Small extract from the readme:
> Use RxJS 5 to compose side effect streams with Redux.

> Features:
> - Works alongside middleware
> - Gradually introduce redux-stream into an application that makes use of thunk-middleware
> - Side effect composing of:
>  - Ajax
>  - Inter module actions (eg. selecting a search filter triggers a search)
>  - Independent modules' state changes
>  - Independent modules' actions
> - Dispatch thunks to cater for conditional dispatching

I believe the biggest difference between our two approaches is that the store enhancer can work alongside thunk-middleware. I'm of the opinion that an approach that works with `redux-thunk` will really help drive adoption, as you can take it for a test drive and incrementally add side effect streams to your Redux app.

I would really like to hear what you guys think w.r.t. the differences in our approaches etc.

P.S. I also have some concerns that I would like to discuss

**Comment by jayphelps** [comment]
Will check it out! btw--after the short deprecation period for thunkservables, people will be able to use redux-thunk as normal since we will no longer hijack the "dispatching a function" thing.

**Comment by jayphelps** [comment]
In case you hadn't seen the new docs on the process manager/actions manager/delegator/whatever-we-end-up-calling-it it's here: https://github.com/redux-observable/redux-observable/pull/55

At first glance, the only difference I'm seeing is the custom operators you've added (the thunk think seems to be non-issue once we remove support). Is that correct? 💃

**Comment by mcoetzee** [comment]
Ah ok it's good to know that the thunk-issue falls away with your new approach. I see you have opened up a poll w.r.t. naming - I hope `effect` wins as I see all the actions produced by these `managers` as side effects.

So the one concern I have (common to both approaches I believe) is that merging and subscribing to all these resulting streams seems to be rather expensive (when configuring the store). I did some basic measuring of
`Observable.merge(...sideEffectStreams).subscribe(...`:
100 streams: ~10ms
250 streams: ~20ms
500 streams: ~30ms

Have you guys considered this up front cost perhaps?

W.r.t. other differences between the two approaches, there are some minor differences that I think are worth discussing. 
1. I extended the Redux store with a ```store.getState$(moduleName)``` method, which plucks the module's state stream (thought it might be a cool addition). This I also provided as part of the API to the `action managers`
2. I delayed the execution of that custom `Observable.prototype.mapAction` operator, as I thought it would be wise if side effects first allowed the dispatched action to flow though the reducers

**Comment by mcoetzee** [comment]
Oh and just to clarify - I'm really happy to see redux-observable head in this direction. I will most probably recommend it as the way to go in the near future 👍  Would just like to discuss my findings

**Comment by jayphelps** [comment]
We haven't done any stress testing for redux-observable in regards to merging a large number of streams. We do have decent perf testing of RxJS itself though, https://github.com/ReactiveX/rxjs/tree/master/perf both macro and micro. we haven't yet seen apps with hundreds of these process managers so haven't noticed any perf issues, but 10ms isn't too surprising to me. I know of plenty of framework code that takes that and much longer to set up. Not dismissing it outright, but I don't think it's significantly worrying.

**Comment by mcoetzee** [comment]
I agree I don't think it's very significant. I'm sitting with an app that currently has 100 side effects which is still growing, so those numbers aren't too crazy. I was mostly concerned for people building large _universal_ apps where perf is a priority though. Redux boots up nice and quick, so perhaps there should be a disclaimer or something in the docs? That being said I might be bikeshedding...

**Comment by mcoetzee** [comment]
@jayphelps I'm happy to close this if you are.

**Comment by jayphelps** [comment]
@mcoetzee right on 👍
