### ISSUE TITLE
Is it possible to provide the ofTypes method?

### ISSUE THREAD

**Issue by BlackHole1** [redux-observable/redux-observable#600]
I want to listen to multiple types to operate
I want to listen to multiple types to operate. So I can use rxjs more operators.
such as combineLatest, zip, etc.

code show as below:

```typescript
export const testEpic = (
  action$: ActionsObservable<AnyAction>,
  store$: StateObservable<RootState>
) => {
  return action$.pipe(
    ofTypes('One', 'Two'),
    combineLatest([one, two]),
    map(arr => console.log(arr))
  )
}
```

Similar to this, my expression may not be good enough. But I probably mean to run related operations by listening to multiple actions.

Translation comes with google translation, I hope you can understand what I mean. Thank you very much.

**Comment by jayphelps** [comment]
Yep! ofType supports any number of action types.

**Comment by evertbouw** [comment]
Your example code wouldn't really work tho. If you want to `combineLatest` for two actions you could do something like this

```ts
export const testEpic: Epic<AnyAction, AnyAction, RootState> = (action$, state$) =>
    combineLatest<AnyAction>(
        action$.pipe(ofType("One")),
        action$.pipe(ofType("Two"))
    ).pipe(
        tap(console.log), // should log [{ type: "One" }, { type: "Two" }]
        mapTo({ type: "Three" }),
    );
```

**Comment by BlackHole1** [comment]
@evertbouw Thank you very much, your code is correct. I will close this issue
