### ISSUE TITLE
Getting an error Source.lift is not a function

### ISSUE THREAD

**Issue by adityanaik** [redux-observable/redux-observable#601]
can someone please help with the code. I am not able to catch error outside concat, but i am able to catch inside individual ajax requests. i dont know where i am going wrong. Getting an error Source.lift is not a function

```
export const deleteSettingsEpic = action$ => action$.pipe(
    ofType('DELETE_SETTINGSDATA'),
    flatMap(action$ => concat(
        ajax.ajaxDelete(`${action$.payload.api}/${action$.payload.id}`)
            .pipe(
                map(r => ({ type: 'DELETE_SUCCESS' })),
                // catchError( e => of({type: 'DELETE_ERROR'}))
            ),
        ajax.get(`${action$.payload.api}`)
            .pipe(
                map(r => ({
                    type: action$.payload.getPaginationAction,
                    payload: {
                        leadSourceList: r.response.docs,
                        page: r.response.page,
                        totalPages: r.response.totalPages,
                        limit: r.response.limit,
                        totalDocs: r.response.totalDocs
                    }
                })),
                // catchError(e => of({type: 'FETCH_ERROR'}))
            ),        
            of({type: 'SET_DIMMER_FALSE'})
    ),
    catchError(e => of({type: 'FETCH_ERROR'}))
    ),
);
```

**Comment by evertbouw** [comment]
You've passed `catchError` as the second parameter to `flatMap`. If you move it one line down I think it should work.

**Comment by Naik-Aditya** [comment]
Yes it happened, when i moved catchError into first pipe next to flatMap it worked for the first time, but when i disconnected my server and checked again it didn't work. I implemented your suggestion and boom! it's working. Can you please share some insight what's happening.

**Comment by Naik-Aditya** [comment]
I really appreciate your help. thank you!

**Comment by Naik-Aditya** [comment]
@evertbouw And one last thing how i would delay 'SET_DIMMER_FALSE

**Comment by Naik-Aditya** [comment]
>  And one last thing how i would delay 'SET_DIMMER_FALSE.
Got it using pipe i can use delay.
