### ISSUE TITLE
Does redux observable scale linearly?

### ISSUE THREAD

**Issue by NGuldager** [redux-observable/redux-observable#602]
As the title says:
Does redux-observable scale linearly with the number of registered epics?

In a project I'm working on we are seeing a performance decrease for every epic we add. 
Is this an issue with redux-observable or are we using it wrong?

**Comment by ymaz** [comment]
@NGuldager did you try to load/add epics async/lazy?
For instance, i'm not sure if you really need all 550 epic on app init (or let's say homepage)
maybe you will able to load some of them on demand?
https://redux-observable.js.org/docs/recipes/AddingNewEpicsAsynchronously.html

**Comment by Sawtaytoes** [comment]
@NGuldager Did you every figure out this issue?

The fact that all those epics probably subscribe to `action$` and the fact that `action$` emits on all of them at the same time any action occurs, it's possible you're getting slowdowns from that.

**Comment by jayphelps** [comment]
Could be wrong, but it would seem having 1000 epics and it taking several minutes to render was likely related to something else.

Here's a simple example of 1001 epics:
https://stackblitz.com/edit/redux-observable-playground-hn2jwp?file=configureStore.js

**Comment by jayphelps** [comment]
Please lmk if this is still an issue! I haven't seen it in practice, but would be very interested to have one to optimize with if it does happen!

**Comment by Sawtaytoes** [comment]
I noticed your example has slowdown at 10K epics; that's been my experience too in other projects, but not with 10K epics, only a few epics and 10K+ observables. It's an RxJS issue potentially at that point.

**Comment by jayphelps** [comment]
@jayphelps agreed, that's quite a large chain of subscriptions at that point, and if someone has a practical use case for that, I would suspect their/your app has very unique challenges that are tough to account for with abstractions like these. In those cases one might consider loading/unloading epics based on the section the user is in, or separate your app into pieces/microfrontends, etc. Without seeing a specific real world case I can't be sure, but I'd suspect such a project would have other challenges as well.

**Comment by crimx** [comment]
Here is another angle to address the scaling issue. We move component-wise logic into the component itself via [observable-hooks](https://github.com/crimx/observable-hooks). It has epic-like interface so we can test the logic the same way as epics. This will reduce the number of epics and the need of loading many async epics.
