### ISSUE TITLE
Injecting Dependencies Async - v1.0.0

### ISSUE THREAD

**Issue by kushalmahajan** [redux-observable/redux-observable#606]
Since this solution mentioned [here](https://github.com/redux-observable/redux-observable/issues/301) will break because of `TypeError: Providing your root Epic to createEpicMiddleware(rootEpic)is no longer supported, instead useepicMiddleware.run(rootEpic)`

The error points to https://redux-observable.js.org/MIGRATION.html#setting-up-the-middleware but I'm not sure if that helps.

**Comment by evertbouw** [comment]
If you apply the steps in that migration guide to the snippet it should still work. It says that you no longer pass rootEpic to createEpicMiddleware :
```diff
-const epicMiddleware = createEpicMiddleware(rootEpic, { dependencies });
+const epicMiddleware = createEpicMiddleware({ dependencies });
```
Instead you'll need to call epicMiddleware.run with your root epic somewhere after calling createStore
```js
const store = createStore(rootReducer, composeEnhancers(applyMiddleware(epicMiddleware)));
epicMiddleware.run(rootEpic);
```

**Comment by kushalmahajan** [comment]
I did that and was on same setup since days but somehow it worked when I changed 
```
export const rootEpic = (action$, state$) => epic$.pipe(
    mergeMap(epic => 
        epic(action$, state$)
    )
);


```
```
export const rootEpic = (action$, ...rest) => epic$.pipe(
    mergeMap(epic => 
        // epic(action$, state$)
        epic(action$, ...rest).pipe(
            takeUntil(action$.pipe(
                ofType('EPIC_END')
            ))
        )
    )
);
```

and added this for hot reloading

```
if (module.hot) {
        module.hot.accept('./rootEpic', () => {
            const nextRootEpic = require('./rootEpic').rootEpic;
            // First kill any running epics
            store.dispatch({ type: 'EPIC_END' });
            // Now setup the new one
            epic$.next(nextRootEpic);
        });
    }
```

Link from docs [here](https://redux-observable.js.org/docs/recipes/HotModuleReplacement.html)


One question though what would be best way to see all my epics in console or test in dev tools.

Now it's running with dependencies, I would want to see if the async injected epic has actually been added ( I know this through my functionality though ) but just to see them clearly as an object as I can do that with redux state dump simply by seeing my reducers. Is there anything similar?

**Comment by evertbouw** [comment]
There isn't anything specific for Redux-observable, but you can apply any debugging techniques that work for Rxjs. I'd probably console.log the object you are interested in when it should be available.
