### ISSUE TITLE
debounce ajax managers?

### ISSUE THREAD

**Issue by beckend** [redux-observable/redux-observable#61]
I know it's simple to debounce an input field to throttle ajax calls, but is it possible to debounce this function directly and bypassing to implement input debounce?
```javascript
const fetchUserManager = action$ =>
  action$.ofType(FETCH_USER)
    .switchMap(action =>
      ajax.getJSON(`https://api.github.com/users/${action.payload}`)
        .map(fetchUserFulfilled)
        .catch(({ xhr }) => of(fetchUserRejected(xhr.response)))
    );
```

**Comment by jayphelps** [comment]
If I'm understanding correctly, this is mostly an RxJS "how do I" question. Please try to keep do those on StackOverflow or similar. 👯 

You can place one of the debounce operators like `debounceTime` right after the filtering of the action type.

```js
const fetchUserManager = action$ =>
  action$.ofType(FETCH_USER)
    .debounceTime(300)
    .switchMap(action =>
      ajax.getJSON(`https://api.github.com/users/${action.payload}`)
        .map(fetchUserFulfilled)
        .catch(({ xhr }) => of(fetchUserRejected(xhr.response)))
    );
```
