### ISSUE TITLE
JSBin examples in docs home page are not working

### ISSUE THREAD

**Issue by farskid** [redux-observable/redux-observable#615]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Examples on the home page of docs throwing an error.
`ReduxObservable` is not defined.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**

Just open any one of example links on the main page of docs at https://redux-observable.js.org/
For instance, this is a screenshot from the example using React at https://jsbin.com/jexomi/edit?js,console,output

<img width="1111" alt="screenshot 2019-02-17 at 18 50 53" src="https://user-images.githubusercontent.com/8332043/52916208-37686980-32e5-11e9-98e8-48caffc83c18.png">

**What is the expected behavior?**
That `window.ReduxObservable` be available in the UMD build referenced in HTML of the example link provided above.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**

OS: Mac OS
Browser: Chrome v72.0.3626.109
Redux Observable: v1.0.0

I don't know if it worked for previous versions of ReduxObservable.

**Comment by evertbouw** [comment]
Pretty sure this used to work, but I'm not sure why it doesn't work right now. I've ported this example to code sandbox: https://codesandbox.io/s/yjqx1m994v

**Comment by farskid** [comment]
Probably replacing Codesandbox in the docs might be a good idea.

**Comment by evertbouw** [comment]
Removed by https://github.com/redux-observable/redux-observable/pull/680
