### ISSUE TITLE
ofType property on ActionsObservable makes the types incompatible with the hot and cold helpers in the test scheduler

### ISSUE THREAD

**Issue by natrixnatrix89** [redux-observable/redux-observable#620]
## Do you want to request a *feature* or report a *bug*?
I consider it a **bug** as it makes usage of `hot` and `cold` helpers in the test scheduler impossible

## What is the current behavior?

I have the following short test:
```typescript
scheduler.run(({ hot, expectObservable }) => {
  const action$ = hot<Action>("-a", { a: fetchRates.request() });

  const state$ = hot<IState>("-a");

  const output$ = fetchEpic(action$, state$, {});

  expectObservable(output$).toBe("--a");
});
```
I have a type annotation that assigns the `Epic` type to my `fetchEpic` function. The problem arises because it expects the 1st argument to be `ActionsObservable`, but I'm providing `HotObservable`. Since `HotObservable` lacks the `ofType` property, I'm getting the following error:
```sh
error TS2345: Argument of type 'HotObservable<EmptyAction<"FETCH_RATES_REQUEST"> | PayloadAction<"FETCH_RATES_SUCCESS", IData> | PayloadAction<"FETCH_RATES_FAILURE", Error> | EmptyAction<"DISCARD_MODAL">>' is not assignable to parameter of type 'ActionsObservable<EmptyAction<"FETCH_RATES_REQUEST"> | PayloadAction<"FETCH_RATES_SUCCESS", IData> | PayloadAction<"FETCH_RATES_FAILURE", Error> | EmptyAction<"DISCARD_MODAL">>'.
  Property 'ofType' is missing in type 'HotObservable<EmptyAction<"FETCH_RATES_REQUEST"> | PayloadAction<"FETCH_RATES_SUCCESS", IData> | PayloadAction<"FETCH_RATES_FAILURE", Error> | EmptyAction<"DISCARD_MODAL">>'.

19     const output$ = fetchEpic(action$, $state, {});
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**

It can't be demoed on an online editor, as it's an issue with type incompatibility in `tsc`.

## What is the expected behavior?
I'd expect that `ActionsObservable` has the same signature as Observables in rxjs, so that such problems don't arise. The `ofType` operator should only be used inside the `.pipe()` method (just as described in the [migration guide](https://redux-observable.js.org/MIGRATION.html))

## Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?
I'm using `redux-observable@1.0.0` and `rxjs@6.4.0`.

**Comment by jayphelps** [comment]
Eventually we'll be able to get rid of `ActionObservable` entirely, but for now we need to keep it and `ActionObservable.prototype.ofType` because many still use `import 'rxjs-compat'` and prototype methods for backwards compatibility.

We'd actually _still_ have your problem because `StateObservable` has the `.value` property. Originally there were reasons why we couldn't use BehaviorSubject. I think it was related to `.value` have error handling if accessed prior to the initial Store actually having a state, but I think this no longer applies in Redux 4 so we might be able to get away from it and use `BehaviorSubject` in the future; I'll have to double check. Still, `BehaviorSubject` also has `.value` so you can't provide `HotObservable` directly.

---
## Solution (in case someone reading only cares about it)

The solution is to wrap your `hot()` or `cold()` in an `ActionsObservable` or `StateObservable`. Both are exported by redux-observable for this purpose.

```ts
scheduler.run(({ hot, expectObservable }) => {
  const actionInput$ = hot('-a', { a: ping() });
  const action$ = new ActionsObservable(actionInput$);
  const stateInput$ = hot('-a', { a: { counter: 1 } });
  const state$ = new StateObservable(stateInput$, { counter: 0 });
  const output$ = fetchEpic(action$, state$, null);

  expectObservable(output$).toBe('- 1s a', { a: pong(1) });
});
```

If this boilerplate is deemed cumbersome, it's _possible_ to write your own wrappers around this. The trouble is that RxJS doesn't currently [publicly export the types for the RunHelpers](https://github.com/ReactiveX/rxjs/blob/0d2025540290bd69637247238595302f7ceb5f9b/src/internal/testing/TestScheduler.ts#L13). These are the hot, cold, expectObservable, etc. If your project allows `any`, you can of course just use it instead. But you lose type safety in your tests.

But it is possible. The solution is a bit...voodoo. If anyone's curious, here it is: https://stackblitz.com/edit/typescript-hqtvgk

And a gist in case the stackblitz goes away: https://gist.github.com/jayphelps/f887e1fea7bdad2e9af96f52d13cb8ba

**Comment by jayphelps** [comment]
I thought of an easier way if you don't mind passing in the `hot` helper function into your own helper and don't mind using a private API--`TestScheduler.prototype.createHotObservable` is not exported, so it's technically private. _Use at your own risk, I am not saying it's OK to use private APIs_.

https://stackblitz.com/edit/typescript-xhl4pe?file=index.ts

```ts
type HotFunction = typeof TestScheduler.prototype.createHotObservable;

const hotActions = <T extends Action>(hot: HotFunction, marbles: string, values?: { [marble: string]: T }, error?: any) => {
  const actionInput$ = hot<T>(marbles, values, error);
  return new ActionsObservable(actionInput$);
};

const hotState = <T>(hot: HotFunction, marbles: string, values?: { [marble: string]: T }, error?: any, initialState?) => {
  const stateInput$ = hot<T>(marbles, values, error);
  return new StateObservable<T>(stateInput$, initialState);
};

scheduler.run(({ hot, expectObservable }) => {
  const action$ = hotActions(hot, '-a', { a: ping() });
  const state$ = hotState(hot, '-a', { a: { counter: 1 } }, { counter: 0 });
  const output$ = fetchEpic(action$, state$, null);

  expectObservable(output$).toBe('- 1s a', { a: pong(1) });
});
```

**Comment by natrixnatrix89** [comment]
Thank you very much for the educational hints. Waiting for `ActionObservable` to be dropped then 👍 .

**Comment by dfee** [comment]
How about this simplification:

```ts
import { ActionsObservable, StateObservable } from "redux-observable";
import { Action } from "redux";
import { RunHelpers } from "rxjs/internal/testing/TestScheduler";

export const wrapHelpers = <A extends Action, S extends {}>(
  helpers: RunHelpers,
  initialState: S,
) => ({
  ...helpers,
  coldAction: (
    marbles: string,
    values?: { [marble: string]: A },
    error?: any, // eslint-disable-line @typescript-eslint/no-explicit-any
  ) => new ActionsObservable(helpers.cold<A>(marbles, values, error)),
  hotAction: (
    marbles: string,
    values?: { [marble: string]: A },
    error?: any, // eslint-disable-line @typescript-eslint/no-explicit-any
  ) => new ActionsObservable(helpers.hot<A>(marbles, values, error)),
  hotState: (
    marbles: string,
    values?: { [marble: string]: S },
    error?: any, // eslint-disable-line @typescript-eslint/no-explicit-any
  ) =>
    new StateObservable(helpers.hot<S>(marbles, values, error), initialState),
});
```

... and for usage:
```ts
export const testScheduler = new TestScheduler((actual, expected) => {
  expect(actual).toEqual(expected);
});

it("should work", done => {
  testScheduler.run(helpers => {
    // magic happens here!
    const { hotAction, hotState, expectObservable } = wrapHelpers(
      helpers,
      initialState,
    );

    const action$ = hotAction("-a", { a: { type: "PING" } as const });
    const state$ = hotState("-a", { a: initialState });
    const output$ = pingEpic(action$, state$, {} as any); // last arg is dependencies

    expectObservable(output$).toBe("-a", { a: { type: "PONG" } });
    done();
  });
});

**Comment by Whazor** [comment]
With the latest version of redux-observable you can drop `new ActionsObservable(` and use with rxjs-marbles:
```
import { Action } from 'redux';
import { StateObservable } from 'redux-observable';
import { Subject } from 'rxjs';
import { Context } from 'rxjs-marbles/context';
// helper from https://github.com/redux-observable/redux-observable/issues/620
// adopted for rxjs-marbles

export const wrapHelpers = <A extends Action, S extends {}>(
  helpers: Context,
  initialState: S
) => ({
  ...helpers,
  coldAction: (
    marbles: string,
    values?: { [marble: string]: A },
    error?: any // eslint-disable-line @typescript-eslint/no-explicit-any
  ) => helpers.cold<A>(marbles, values, error),
  hotAction: (
    marbles: string,
    values?: { [marble: string]: A },
    error?: any // eslint-disable-line @typescript-eslint/no-explicit-any
  ) => helpers.hot<A>(marbles, values, error),
  hotState: (
    marbles: string,
    values?: { [marble: string]: S },
    error?: any // eslint-disable-line @typescript-eslint/no-explicit-any
  ) => {
    const subj = new Subject<S>();
    const obs = helpers.hot<S>(marbles, values, error);
    obs.subscribe(subj);
    return new StateObservable(subj, initialState);
  },
});
```
