### ISSUE TITLE
Allow swallowing actions, emitting only epic-produced actions

### ISSUE THREAD

**Issue by halfmatthalfcat** [redux-observable/redux-observable#626]
**Do you want to request a *feature* or report a *bug*?**  

Feature

**What is the current behavior?**

`redux-observable` explicitly states that epic middleware is only ran _after_ the action has already passed through the proceeding middleware and state is changed.

**What is the expected behavior?**

There should be a mechanism (option) that allows actions to run through epics _before_ it reaches the reducers and subsequent middleware.

**Why**

Actions could come from untrusted sources (such as http or a socket) and have to be validated before they hit the resucers and change state. This change would allow the epics to validate (and swallow) actions depending on their validity.

**Comment by evertbouw** [comment]
I don't get it. Why do you want this?

**Comment by halfmatthalfcat** [comment]
Actions could come from untrusted sources (such as a socket) and using epics to validate those actions before they hit the reducers is useful.

**Comment by tjfryan** [comment]
In your reducer, you can just have logic to validate actions, simply returning `state` if the action is deemed invalid by some metric.  I'm not sure I understand how someone is able to inject actions into your store remotely in a way that could be prevented by an in-app check or by managing receiving messages from remote connections differently.

**Comment by halfmatthalfcat** [comment]
In my specific example, I’m feeding a websocket connection directly into ‘store.dispatch’, where the client emits actions to the server. The server needs to ensure that these actions are valid within the context of the user (authentication, authorization, etc). 

Because I don’t want arbitrary and potentially dangerous state mutating actions fed directly into the reducers, I want the epics to validate (through db calls or whatever async actions) that the actions can proceed (as well as making side effecting actions) to the reducers correctly.

I _could_ do this at the actual socket connection handler, but why would I do that when I can leverage rxjs and have my entire flow within an epic, as well as reusing these operators across multiple epics to do similar things.

**Comment by tjfryan** [comment]
IMO you should implement a new Action, 'RECEIVED_WEBSOCKET_ACTION' which has an action as part of its payload. Have your reducers ignore this action, but have an epic watch for this action type, validate the action that's in the payload and emit that action if it's deemed to be valid.

**Comment by halfmatthalfcat** [comment]
That’s definitely one way to do it but I’d have to (1) extract the desired action, (2) figure out it’s type and re-feed that back into the epics (I’m planning on having many different epics to handle different action types) but in some way.

I guess my question is what would be the harm in hiding this behind a flag as opt-in?

**Comment by jayphelps** [comment]
@halfmatthalfcat Hey 👋My initial thoughts is that, while there are absolutely reasons one might want to use the pattern of actions hitting epics before reducers--including the case you describe--I'd like to keep redux-observable fairly simple and not support that pattern within redux-observable itself. The biggest reason is that once we go down this path, I fear the extra configuration and complexity we'll need to add to satisfy additional requests. I've heard a couple people over the years request similar things, but varied in requirements.

For example, the proposed feature in #627 is an all-or-nothing option, which when enabled has the opposite issue of needing to handle every and mirror every action dispatched that _shouldn't_ be swallowed. Very tedious and contrary to the redux-observable pattern. What has been proposed before was allowing individual epics to "opt-in" to this gatekeeping behavior, but when we experimented with it we found we'd need to move to some sort of `createEpic(func, options)` helper pattern, which causes issues with the way people compose epics now, since they're just functions rather than complex objects.

One of the community members created [redux-logic](https://github.com/jeffbski/redux-logic) which does in fact enable that ability of swallowing actions. It's not a redux-observable clone, just inspired by it. You might dig it.

As far as the recommendation made above to put this in your reducers, it can be done this way:

```js
const internalRootReducer = combineReducers({ foo, bar });
const rootReducer = (state, action) => {
  if (validate(action)) {
    return internalRootReducer(state, action);
  } else {
    return state;
  }
};
```

**Comment by tjfryan** [comment]
For validating actions asynchronously, here's an epic that seems like it would accomplish that (using rxjs-compat semantics)

```typescript
function validateRemoteActionsEpic(
  actions: ActionsObservable<Action>, 
  states: StateObservable<AppState>, 
  {validateAction}: {validateAction(action: Action): Observable<boolean>}
): Observable<Action> {
  return actions.ofType(ActionTypes.RECEIVED_WEBSOCKET_ACTION)
    .flatMap(
      ({payload: {internalAction}}) => validateAction(internalAction).filter(Boolean).map(() => internalAction)
  );
}
```

**Comment by halfmatthalfcat** [comment]
Hmmm thanks for all the feedback. I’ll keep mulling over the different strategies presented. I understand wanting to keep things simple and not support one-off use cases @jayphelps.

I looked at redux-logic previously but wanted to avoid moving libs/patterns of possible.

**Comment by jayphelps** [comment]
> I guess my question is what would be the harm in hiding this behind a flag as opt-in?

Good question! The harm is that adding the code and configuration increases the complexity of redux-observable in a way I don't feel is a good fit. While there are a few use cases of swallowing that I think _maybe_ are okay, I've worked with countless engineers using redux-observable and a vast (and I mean _vast_) majority of times people wanted to swallow, it was an anti-pattern that I really don't want to encourage. I fear having the option encourages people to shoot themselves in the foot. Ultimately redux-observable can't do everything, so we have to make choices about what does and doesn't make it in. Often that means being opinionated, like in this case.

I will try my best never discourage or disparage people who choose to experiment with creating a new, competing project, as long as they know that it's not considered idiomatic in redux-observable.

**Comment by jayphelps** [comment]
Ohh forgot to summarize why I think it's usually an anti-pattern.

People who come to know Redux come to have a simple expectation: if I call `store.dispatch(action)` that action will run through my reducers. Breaking this expectation can lead to seemingly weird bugs, and be difficult to debug. It's especially true if you work on a non-trivial team size and don't fully realize it's possible for actions to be swallowed.

This is less of an issue if you _always_ swallow actions dispatched and require epics emit any actions that will actually make it to reducers, but this drifts from the Redux pattern in a pretty significant way, and I haven't myself seen anyone try that pattern in a meaningful way. It might be awesome for all I know! 😄 

In your specific use case, I'd actually advise a simple, custom middleware. It sounds like it's a very special case where you'd want the normal Redux pattern of dispatching always going to reducers, but there's an unlikely (but perhaps possible in your case) situation of a malicious action you want to filter out.

Here's an example:

```js
const createGateKeeperMiddleware = validate => store => next => action => {
  if (validate(action)) {
    return next(action);
  }
};
```

You can see it in action here: https://stackblitz.com/edit/redux-observable-v1-playground-vkwy81?file=configureStore.js

**Comment by jayphelps** [comment]
Closing, but lmk if you'd like to further the discussion!
