### ISSUE TITLE
Docs - Writing tests outdated link

### ISSUE THREAD

**Issue by julioxavierr** [redux-observable/redux-observable#638]
**Do you want to request a *feature* or report a *bug*?**  
"bug"

**What is the current behavior?**

The link of " how to use the testScheduler.run(callback)" is pointing to an outdated document on [Writing Tests](https://redux-observable.js.org/docs/recipes/WritingTests.html#).

**What is the expected behavior?**
Point to the correct document

**Comment by jayphelps** [comment]
Fixed in #639
