### ISSUE TITLE
Store creation broken with Stencil One

### ISSUE THREAD

**Issue by Elvynia** [redux-observable/redux-observable#644]
**Do you want to request a *feature* or report a *bug*?**  
I'm reporting a bug after waiting answers for this stackoverflow [post](https://stackoverflow.com/questions/56350558/cant-use-redux-observable-with-stencilone-class-constructor-observable-cann).

**What is the current behavior?**
Any project with stencil@1.0.0-beta.x and redux-observable should fail at runtime when creating store with this error :
```
TypeError: Class constructor Observable cannot be invoked without 'new'
    at new ActionsObservable (chunk-f18fe9c6.js:3744)
    at epicMiddleware (chunk-f18fe9c6.js:3830)
    at chunk-f18fe9c6.js:4579
    at Array.map (<anonymous>)
    at chunk-f18fe9c6.js:4578
    at createStore (chunk-f18fe9c6.js:4043)
    at chunk-f18fe9c6.js:4716
```

**What is the expected behavior?**
I expected redux-observable to work with Stencil One.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
Npm packages :

- @Stencil/core : 1.0.0-beta.7
- @Stencil/redux : 0.1.1
- redux : 4.0.1
- redux-actions : 2.6.5
- redux-observable : 1.1.0

Node version 12.1.0
Npm version 6.9.0
Browser : Chrome Version 70.0.3538.77
OS : Ubuntu 18.04.2

Please look at the stackoverflow post for more informations.

**Comment by malua** [comment]
i am having the same issue, I created a [issue](https://github.com/ionic-team/stencil/issues/1591) at the stencil repo and also made demo repository
[https://github.com/malua/stencil-redux-observable-demo](https://github.com/malua/stencil-redux-observable-demo).

if somebody has some insight, thank you so much!

**Comment by malua** [comment]
i kind of got it working. i think the problem is babel. it transpiles the creation of ActionsObservable/StateObservable to this:

`_possibleConstructorReturn(this, _getPrototypeOf(ActionsObservable).call(this));`

(this is actually babel 7, the babel 6 output looks a little bit different)

my first idea was to update babel to version 7, but that produced the same error.
i then copied all of the source files and the typings file into my project, and let stencil transpile it. this works. i don't know that much about babel, so i can't really offer a PR...

**Comment by filip1323** [comment]
@malua , I've had the same issue today, but with different package. I could finally solve it by importing redux-observable-es6-compat into project.

**Comment by Elvynia** [comment]
@filip1323 Thanks for sharing this I'm going to try it out today !

**Comment by jayphelps** [comment]
If @iwnow knows a way we can fix this in redux-observable's builds I'd be glad to do so!

**Comment by asvishnyakov** [comment]
@jayphelps I compared your source code and source code of redux-observable-es6-compat, but there is no difference except uniqueQueueScheduler. Looks like it's all about lib, they are completely different.

**Comment by jayphelps** [comment]
@asvishnyakov the `/lib` directory you mean? Suggesting they didn't commit their changes?

**Comment by asvishnyakov** [comment]
@jayphelps I'm not professional in that, but looks like Babel (at least version you use) incorrectly transpiles the code.

**Comment by asvishnyakov** [comment]
@jayphelps Well, it looks like `redux-observable-es6-compat` just compiled with typescript compiler. The main problem here is that babel transpile es2015 classes: typescript-based application can't correctly create instance of them.
