### ISSUE TITLE
Couldn't able to get store value 

### ISSUE THREAD

**Issue by mohan-mu** [redux-observable/redux-observable#647]
when i try to access `state$.value.auth.token` i'm not getting token value . 
is something Wrong ?

Below is my store schema : 
```javascript
auth : {
token:' ',
refreshToken:' '
}
```
and this is my  epic
```javascript
export const fetchCustomerDevices = (action$, state$) =>
  action$.pipe(
    ofType(GET_CUSTOMER_DETAILS),
    mergeMap(action =>
      ajax
        .get(
          `${build_properties.endpoint}/customer/${
            action.payload.customerId
          }/devices?limit=20`,
          {
            "X-Authorization": `Bearer ${state$.value.auth.token}`
          }
        )
        .pipe(
          mergeMap(response => of(updateCustomerDevices(response.response))),
          catchError(error =>
            of({
              type: UPDATE_ERROR_DETAILS,
              payload: error.response
            })
          )
        )
    )
  );
```

i'm using  `redux 4.0.1` ,`redux-observable1.1.0` & `rxjs:6`
```javascript
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-observable": "^1.1.0",
    "redux-persist": "^5.10.0",
    "rn-placeholder": "^1.2.0",
    "rxjs": "^6.5.2",
```

**Comment by jayphelps** [comment]
Sorry! I don't see anything obvious that would cause it.

Have you tried pausing the debugger in that spot where you access `state$.value.auth.token` and inspecting what `state$.value` is? Maybe it will reveal the state having a different shape than you're expecting.

**Comment by jayphelps** [comment]
Code as provided appears to work as expected: https://stackblitz.com/edit/redux-observable-playground-nw6t6v?file=fetchCustomerDevices.js

**Comment by mohan-mu** [comment]
Figured Out the problem , Sorry @jayphelps  i wasted your time

**Comment by jayphelps** [comment]
Glad to hear! Cheers.
