### ISSUE TITLE
Consider adding checks for process managers that don't actually return an observable

### ISSUE THREAD

**Issue by jayphelps** [redux-observable/redux-observable#65]
#64 demos that it's easy for people to not actually return an observable on accident (or intentionally, not realizing they must).

We should consider adding checks to the combine helper and the middleware itself to confirm what they're returning is subscribable.

**Comment by Lxxyx** [comment]
Same problem, need help.

**Comment by Lxxyx** [comment]
I actually not return observer, from the example.

```javascript
interface Action {
  type: string,
  payload: any
}

let user: Epic<Action>

user = function (action$, store) {
  action$
    .ofType(SET_USER_INFO)
}
```

but got an error:

[ts]
Type '(action$: ActionsObservable<Action>, store: MiddlewareAPI<any>) => void' is not assignable to type 'Epic<Action>'.
  Type 'void' is not assignable to type 'Observable<Action>'.

**Comment by jayphelps** [comment]
it is the same problem, but this is a TypeScript error (before our runtime checks would tell you)

You need to return the observable:

```js
user = function (action$, store) {
  return action$
    .ofType(SET_USER_INFO)
}
```

**Comment by Lxxyx** [comment]
Solve it.

just

```javascript
const user: Epic<Action> = (action$, store) => {
  return action$
  
}
```

return the action$ can fix it

**Comment by jayphelps** [comment]
We added runtime checks in #137, so closing this.

**Comment by Lxxyx** [comment]
@jayphelps Solve it. Thanks.

**Comment by jayphelps** [comment]
@Lxxyx ooo don't do that! that makes an infinitely recursive observable. Definitely advise you check out the docs: https://redux-observable.js.org/docs/basics/Epics.html

**Comment by Lxxyx** [comment]
ooo Thanks. @jayphelps
