### ISSUE TITLE
Compat layer not working with redux-observable 1.1.0 and rxjs 6

### ISSUE THREAD

**Issue by PhilipGarnero** [redux-observable/redux-observable#650]
We have yet to migrate to the new rxjs api but will do so progressively.

In the mean time, we updated to rxjs v6 and redux-observable 1.1.0 but there is **no compat method on the ActionsObservable** object.
**Observable does feature those methods** but ActionsObservable does not.
What I did is trying to convert an ActionsObservable to a regular Observable using `Observable.from(action$, queueScheduler)` but then Rxjs will prevent me from subscribing because it does not find the Symbol.observable property on converted Observable instances.

Why is ActionsObservable not picking up the compat methods as said in the Troubleshooting or Migration guide ?

**Comment by PhilipGarnero** [comment]
Found the problem myself.
I was missing `import 'symbol-observable'` at the top of my index.js.
Lost 3 days thanks to that.

**Comment by jayphelps** [comment]
@PhilipGarnero That's a real bummer! But glad you found the solution!
