### ISSUE TITLE
mapTo(state$.value) sometimes passes along stale instead of latest state

### ISSUE THREAD

**Issue by kaleidoc0de** [redux-observable/redux-observable#676]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
I have made an epic for network requests which looks like the following:
```
export default (action$, state$) =>
  action$.pipe(
    ofType(FETCH_DATA),
    mapTo(state$.value),
    map(searchRequestSelector),
    mergeMap(request =>
      ajax({
        url:
          URL,
        method: "POST",
        crossDomain: true,
        responseType: "json",
        body: request
      }).pipe(
        map(handleSearchResponse)
        ),
        takeUntil(action$.pipe(ofType(FETCH_DATA_CANCEL))),
        catchError(error =>
          of(handleFailedSearch([error]))
        )
      )
    )
  );
```

I receive an error message from the selector which complains certain state is missing which is in the store (checked by putting `tap(console.info)` between the selector and state maps and cross referencing store with chrome redux plugin) unless I swap the `mapTo(state$.value)` part to `map(() => state$.value)`

I am also using hot reloading in my app, not sure if this is the culprit.
following code for HMR epics
```
import rootEpic from './epics';
...
let epic = rootEpic;
if (__DEV__) {
  const epic$ = new BehaviorSubject(rootEpic);
    epic = (action$, state$) =>
      epic$.pipe(switchMap(epic => epic(action$, state$)));
    module.hot.accept("./epics", () => epic$.next(rootEpic));
}
epicMiddleware.run(epic)
...
```

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**

**What is the expected behavior?**
mapTo(state$.value) to provide the latest state from store always

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
redux-observable: ^1.2.0
rxjs: ^6.5.3

**Comment by kaleidoc0de** [comment]
Thinking about this a little bit and from thinking about how rxjs works I assume mapTo is mapping all the emitted values to the value of state$.value was upon initialisation and so a function to pull the latest state would be needed.

Closing

**Comment by jayphelps** [comment]
Glad you solved!
