### ISSUE TITLE
Provide troubleshooting guide for typings with redux-starter-kit

### ISSUE THREAD

**Issue by on3iro** [redux-observable/redux-observable#685]
**Do you want to request a *feature* or report a *bug*?**  
Feature/Docs

**What is the current behavior?**
I am trying to get redux-observable to work in conjunction with [redux-starter-kit](https://redux-starter-kit.js.org/), but am unable to get the typings correct. Especially `ofType` is an issue with redux-starter-kits `createSlice`. Though I think there might also be an issue with the  way `createSlice` types its actions (its `Action<string>` instead of `Action<Constant>`.

**What is the expected behavior?**
I would like to see a simple usage example with redux-starter-kit inside the docs or the troubleshooting guide. As far as I can tell redux-starter-kit is gonna be heavily promoted throughout the official redux docs, so I assume it makes sense to ensure compatibility with redux-observable.

I also asked this question over at the repo for redux-starter-kit, which eventually led me here.
https://github.com/reduxjs/redux-starter-kit/issues/228

**Comment by on3iro** [comment]
## Update:

There is a PR proposal over at redux-starter-kit for a change which might fix this issue. If that's the case I am going to close this :)

https://github.com/reduxjs/redux-starter-kit/pull/239

**Comment by on3iro** [comment]
The proposal has been merged and works :)

**Comment by jayphelps** [comment]
@on3iro thanks the update!

**Comment by chanced** [comment]
@on3iro Does it work with createSlice? I don't see the docs for it. 

I'm just getting started with redux and started exploring options for alternatives to thunks. redux-observable seemed ideal. The only caveat for me was the usage of string literals to match actions. 

I spiked this to see if I could get a clean solution: 

```js
const getActions = <T extends Slice>(slice: T) => {
  const genericActions: T['actions'] = slice.actions;  // this is acceptable
  const keys = Object.keys(genericActions) as Array<keyof typeof genericActions>;
  return keys.reduce(
    (accumulator, key) => {
      accumulator[key] = `${slice.name}/${key}`;
      return accumulator;
    },
    {} as Record<keyof typeof genericActions, string>
  );
};
```

You pass it a slice and get a POJO back `{ actionName: "sliceName/actionName", otherAction: "sliceName/otherAction" }`

**Comment by on3iro** [comment]
@chanced sorry, I haven't used redux-observable in a while. So I am a bit out of the loop.

**Comment by evertbouw** [comment]
@chanced I wrote about redux toolkit here https://github.com/redux-observable/redux-observable/issues/706
