### ISSUE TITLE
Online Live Example for React is broken

### ISSUE THREAD

**Issue by vidhill** [redux-observable/redux-observable#686]
**Do you want to request a *feature* or report a *bug*?**  
Bug Report

**What is the current behavior?**
The example jsbin linked to is broken, displays empty output

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**

**What is the expected behavior?**
Should link to a working example

The jsbin at the linked url: https://jsbin.com/jexomi/edit?js,output
Does not point to specific versions of the libraries and is erroring out

I have a working fork of the jsbin here..
https://jsbin.com/timoxej/3/edit?html,js,output

**Comment by evertbouw** [comment]
examples were removed in https://github.com/redux-observable/redux-observable/pull/680
