### ISSUE TITLE
how to fix it ? thanks a lot 

### ISSUE THREAD

**Issue by GravesDXD** [redux-observable/redux-observable#696]
Argument of type '{ systemEpic: any; }' is not assignable to parameter of type 'Epic<any, any, void, any>'.
  Type '{ systemEpic: any; }' provides no match for the signature '(action$: ActionsObservable<any>, state$: StateObservable<void>, dependencies: any): Observable<any>'.

I found the issue 592,but I am a new here ,so I want to get help. I want to get the whole codes

**Comment by evertbouw** [comment]
Can you provide some code? Only the error doesn't tell me enough

**Comment by GravesDXD** [comment]
![1575250293(1)](https://user-images.githubusercontent.com/33920719/69924488-a1ee3d00-14e6-11ea-9d11-17830ff1e443.jpg)
![1575250330(1)](https://user-images.githubusercontent.com/33920719/69924489-a1ee3d00-14e6-11ea-9323-521c3326fa2e.jpg)
![1575250361(1)](https://user-images.githubusercontent.com/33920719/69924490-a3b80080-14e6-11ea-97c9-adf716eb3148.jpg)

**Comment by GravesDXD** [comment]
If you can help me solve this problem, thank you very much. It is difficult for me

**Comment by evertbouw** [comment]
`combineEpics` doesn't take an object, just pass the epics. `combineEpics(systemEpic)` is what you want

**Comment by GravesDXD** [comment]
like reducer, firstly create epic, then collect all of epic in epic.ts ,finally inject epics to the store from epic.ts.

**Comment by evertbouw** [comment]
That is correct, but you should remove the curly brace in `combineEpics`

```diff
-export const rootEpic = combineEpics({
+export const rootEpic = combineEpics(
   systemEpic
-});
+);

```

**Comment by GravesDXD** [comment]
thanks a lot .
