### ISSUE TITLE
Waiting for few epics to be completed.

### ISSUE THREAD

**Issue by Tarvald** [redux-observable/redux-observable#724]
Hi,
In our project, we have one weird case.
We have some standard epics in our application. We launch them by actions and they full-field redux store. 

However, we would like to launch them on app init and after that render app. 
We are doing this already, but our approach skips epic logic and directly launch http calls.

![image](https://user-images.githubusercontent.com/7673542/78353457-5b9b0e80-75aa-11ea-800b-b603957828c8.png)

Do you know how we could launch a batch of epics and wait until they finish?

Thanks a lot!

**Comment by jayphelps** [comment]
Hey there. If this is still needed, your best bet is to post on https://stackoverflow.com/ or on the [Gitter channel](https://gitter.im/redux-observable/redux-observable). We keep the issue tracker reserved for bug reports. Thanks!
