### ISSUE TITLE
Hot Reloading?

### ISSUE THREAD

**Issue by ronag** [redux-observable/redux-observable#73]
How does this work with hot reloading. Do we need some kind of `replaceEpic` similar to:

```javascript
  if (module.hot) {
    module.hot.accept('./reducers', () => {
      const reducers = require('./reducers').default
      store.replaceReducer(reducers)
    })
  }
```

**Comment by jayphelps** [comment]
We're considering it #52 however Epics can maintain state, so if you hot reload them, that state disappears and I'm not confident it wouldn't put your app into a bad state because that state may actually rely being in sync or derived from the state in the store.

**Comment by ronag** [comment]
How does cycles hot reloading get around that issue?

**Comment by ronag** [comment]
Maintaining state in an Epic should be considered an anti-pattern, no?

**Comment by ronag** [comment]
Though, I can see the problem with e.g. `debounceTime` where an action could disappear during a hot-reload.

**Comment by jayphelps** [comment]
@ronag maintaining state is definitely _not_ a blanket anti-pattern. It depend on the state. Almost all side-effects require some sort of temporary state. Even a simple ajax call has state, inside the observable.

I can't provide any examples where Epic state being lost creates any real issues..but I imagine they exist at least in principle. Your `debounceTime` example certainly might be one of them, but I'm not sure if that's truly an issue in practice.

I don't know anything about Cycle's hot reloading, so I can't speak to it.

**Comment by jayphelps** [comment]
A brief google search suggests to me hot reloading is provided by community modules like https://github.com/Widdershin/cycle-restart which apparently record and replay the actions. I'm not sure if something similar would be appropriate. If you replay actions into your Epics, that could kick off a whole mess of side effects like ajax calls, etc. That doesn't seem desirable and is potentially dangerous, if those ajax calls are not pure on the server.

**Comment by ronag** [comment]
@jayphelps: I guess then that it is up to the developer to make sure that an epic is replayable using e.g. `Observable.cache`.

**Comment by jayphelps** [comment]
Check out https://github.com/redux-observable/redux-observable/pull/75

**Comment by ronag** [comment]
What if redux-observable sent a EOF action into the epics and the `replaceEpic` method used `concatMap` instead of `switchMap`?

**Comment by jayphelps** [comment]
@ronag let's bring that sort of discussion over to #75.

**Comment by jayphelps** [comment]
Released as `epicMiddleware.replaceEpic(nextEpic)`. Documented here: http://redux-observable.js.org/docs/recipes/HotModuleReplacement.html

Please let us know how it ends up working in practice.
