### ISSUE TITLE
Extremely slow & barely usable

### ISSUE THREAD

**Issue by pawelotto** [redux-observable/redux-observable#736]
Did you even run performance tests on this? When I'm using this to map actions the target action is executed like 0,7 seconds after the source has action dispatched. On the other hand, when I subscribe directly to the same store variable using RxJS's from() method it takes only 1 ms to dispatch the consecutive action.

This alone makes this plugin virtually useless.

**Comment by jayphelps** [comment]
No one has ever run any of the code in this repo. We're not even sure where the code came from, to be honest.

**Comment by jayphelps** [comment]
In seriousness, I suggest taking a less abusive approach to people who volunteer their time and code. We're friendly people to people who are friendly.

It's unclear exactly what you were doing to run into performance concerns, but here's a simple "hello world" of performance tests—it also includes the intrinsic overhead from Redux and RxJS. If you're able to create a minimum reproduction I can take a look.

https://stackblitz.com/edit/redux-observable-playground-fkikqn?file=index.js

![image](https://user-images.githubusercontent.com/762949/94342991-14368d80-ffe3-11ea-894f-bed903042922.png)

**Comment by Artizmo** [comment]
Here is an idea. Why don't you make your own library that operates to your own liking?

**Comment by pawelotto** [comment]
> It's unclear exactly what you were doing to run into performance concerns, but here's a simple "hello world" of performance tests—it also includes the intrinsic overhead from Redux and RxJS. If you're able to create a minimum reproduction I can take a look.

The ping-pong app looks well cool, congratulations, unfortunately I'm dealing with large stores with dozens of actions and after adding some Epics to my Redux store your plugin is barely usable. And frankly I feel there's need for less nut-hugging and more criticism in the open source community because the codebase is getting worse and less-stable by the day.

I literally wasted two working days on this plugin only to find out it's too slow to handle the work and needed to write my own RxJS-based library from scratch over this weekend that works like 700x faster than your plugin on the exact same store (~700ms vs ~1ms response time).

**Comment by jayphelps** [comment]
lol
