### ISSUE TITLE
Return multiple actions throws error

### ISSUE THREAD

**Issue by adeptb** [redux-observable/redux-observable#737]
**Do you want to request a *feature* or report a *bug*?**  

bug

**What is the current behavior?**

There is example in the section **Actions emitted by your epics are now scheduled on a queue** in [https://redux-observable.js.org/MIGRATION.html](https://redux-observable.js.org/MIGRATION.html) how to return multiple actions in single epic.
I tried it and got error in console:

> Actions must be plain objects. Use custom middleware for async actions.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**
[https://stackblitz.com/edit/redux-observable-playground-uzb5ix?file=index.js](https://stackblitz.com/edit/redux-observable-playground-uzb5ix?file=index.js)

**What is the expected behavior?**
This code should dispatch two actions
```javascript
mergeMap(async () => {
    return of({ type: "ACTION1" }, { type: "ACTION2" });
}) 
```

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
Chrome Version 86.0.4240.75
  "rxjs": "6.4.0",
    "redux": "4.0.5",
    "redux-observable": "1.1.0"

**Comment by evertbouw** [comment]
you've marked the function as `async`, this means it'll return a promise. The promise contains the observable with two actions. `mergeMap` will flatten the value once, so now the epic will dispatch an observable of two actions, instead of two actions.

You can flatten this again or remove `async`

**Comment by adeptb** [comment]
@evertbouw tnx!
