### ISSUE TITLE
Documentation is a horrible experience

### ISSUE THREAD

**Issue by gregbown** [redux-observable/redux-observable#739]

**Comment by jayphelps** [comment]
> First of all, why would you use a vendor that forces you to subscribe to something just to read your documents?
Second, subscribing does not enable the code demos and there is no clear way to locate them on js-bin?
So now one is forced to try to get a refund for some service they never wanted and then search for working examples.
> 
> I am fine with you wanting to monetize your library but at least make sure it works. Please read your own code of conduct, I think you fail on several points.

I'm sorry for your poor experience. It wasn't asking you to pay or get a pro account, but rather me as the person who originally added them using my pro account. I didn't realize embedding was a pro-only feature. It wasn't in any way intended to monetize anything.

**Comment by gregbown** [comment]
@jayphelps I see now that I was a bit to eager to see the examples and should have analyzed the situation more. My apologies for directing my frustration in such a poor way. I see you had only good intentions, and thank you for your patience.
