### ISSUE TITLE
Docs: jsbin examples are broken

### ISSUE THREAD

**Issue by Ayub-Begimkulov** [redux-observable/redux-observable#741]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**

All of the JSBin demos say "This bin needs a pro account"

![image](https://user-images.githubusercontent.com/46418811/108954074-41b06180-767d-11eb-9d88-d5260dbd6480.png)

**If the current behavior is a bug, please provide the steps to reproduce and a minimal demo of the problem using JSBin, StackBlitz, or similar.**

**What is the expected behavior?**

Everything should work.

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
-

**Comment by jayphelps** [comment]
Thanks for reporting. Fixed by #743
