### ISSUE TITLE
Uncaught Type error in epicMiddleware.run(rootEpic)

### ISSUE THREAD

**Issue by dent50cent** [redux-observable/redux-observable#751]
**Do you want to request a *feature* or report a *bug*?**  

bug

I'm trying to follow an example project to get my head around redux-observables and how it works with typescript, but I keep running into this error no matter how I've go about setting up the epics/middleware:
```
Uncaught TypeError: this.schedulerActionCtor is not a constructor
    at QueueScheduler.Scheduler.schedule (Scheduler.js?ef44:10)
    at eval (observeOn.js?142b:6)
    ...
```
When trying to set up the middleware, below is the code I'm trying to get working.

example/epics.ts:
```Typescript
import { delay, filter, mapTo } from 'rxjs/operators'
import { isOfType } from "typesafe-actions"

import { ExampleActionTypes } from './types'
import * as exampleActions from './actions'


export const pingEpic: Epic<RootAction, RootAction, RootState> = (action$) => action$.pipe(
  filter(isOfType(ExampleActionTypes.PING)),
  delay(1000), // Asynchronously wait 1000ms then continue
  mapTo(exampleActions.pong())
)

export const buttonEpic: Epic<RootAction, RootAction, RootState> = (action$) => action$.pipe(...)

export default {
  pingEpic, 
  buttonEpic
}
```
Then in rootEpic.ts:
```Typescript
import { combineEpics } from 'redux-observable';
import {
  pingEpic,
  buttonEpic
} from './example/epics';


export default combineEpics(
  pingEpic,
  buttonEpic
)
```
And in store.ts:
```Typescript
...
export const epicMiddleware = createEpicMiddleware<RootAction, RootAction, RootState>()

const middlewares = [epicMiddleware]
const enhancer = composeEnhancers(applyMiddleware(...middlewares))

const store = createStore(
  rootReducer,
  initialState,
  enhancer
)

epicMiddleware.run(rootEpic)
...
```
Versions of libraries from package.json
```Json
    "redux": "4.1.0",
    "redux-observable": "1.2.0",
    "typesafe-actions": "5.1.0"
```
I've tried structuring my redux setup a few different ways but they always lead back to that same error, the interesting thing is that if you remove the `epicMiddleware.run(rootEpic)` line from store.ts, the error doesn't show up anymore, but I don't know if it's a problem with my epics or with the middleware that's causing it.

**Comment by jason-whitted** [comment]
@dent50cent I ran into a similar issue.  Then I realized the documentation states:
> This has peer dependencies of rxjs@6.x.x and redux@4.x.x, which will have to be installed as well.

I was using `rxjs@7.1.0`

The issue was resolved by downgrading to `rxjs@6.6.7`

Hope that helps!

**Comment by jayphelps** [comment]
Could you both try `npm install redux-observable@2.0.0-rc.2` to see if it fixes it?

**Comment by camille-hdl** [comment]
> Could you both try `npm install redux-observable@2.0.0-rc.2` to see if it fixes it?

I ran into the same issue while upgrading to rxjs7 and this fixed it, thank you.

**Comment by dent50cent** [comment]
That seemed to fix things for me as well, thank you ^_^
