### ISSUE TITLE
Support tslib 2.3.0+ 

### ISSUE THREAD

**Issue by OliverJAsh** [redux-observable/redux-observable#759]
For the same reason RxJS switched the `tslib` version from `~2.1.0` to `^2.1.0`, `redux-observable` should do the same. See https://github.com/ReactiveX/rxjs/issues/6689 and https://github.com/ReactiveX/rxjs/commit/0b2495f72e76627fdd19dd7a670dd74847d6449c.

**Comment by evertbouw** [comment]
tslib is no longer needed
