### ISSUE TITLE
[Feature] fire and forget epics, similar to ngrx

### ISSUE THREAD

**Issue by nate-summercook** [redux-observable/redux-observable#763]
*feature*

**What is the current behavior?**
Currently, when I want to create an epic without emitting another action in the end, it will loop the same epic over and over.
There was a request like this before here, I'm aware, but it was brushed off as being bad practice and there are no real usecases for it. I disagree, there are several.
- redirecting away from your page after logout
- throwing a toastr message
- logging
- persisting something to localStorage or sessionStorage

In order to achieve the desired behaviour, I currently have to return a noop action. I think this is a lot uglier than just having fire-and-forget epics as an option.

**What is the expected behavior?**
I understand that with the current API, it wouldn't be possible to pass such an option. So I'd suggest a function similar to ngrx's `createEffect`:
```javascript
const myEpic$ = createEpic((actions$) => pipe(
  ofType(MY_ACTION),
  tap(() => console.log('just logging something here'))
), { dispatch: false });
```

**Comment by robmcm** [comment]
I think the recommended practice here is to add the rxjs operator `ignoreElements()` at the end of your epic:

```
const myEpic$ = createEpic((actions$) => action$.pipe(
  ofType(MY_ACTION),
  tap(() => console.log('just logging something here')),
  ignoreElements(),
));
```

If you wanted a bespoke epic, you could easily have a `createEffectEpic()` that pipped the ignore onto the stream:
```
export const createEffectEpic = (epic) => epic.pipe(ignoreElements());

// then to use:

const myEpic$ = createEffectEpic((actions$) => action$.pipe(
  ofType(MY_ACTION),
  tap(() => console.log('just logging something here'))
));
```

**Comment by nate-summercook** [comment]
So far I dealt with the problem by creating noop actions wherever I didn't need further processing. Came back to this issue now and your solition, @robmcm, works quite well. That's good enough for me at least. Closing.
