### ISSUE TITLE
Combination of Redux Toolkit and Redux Observables is not working in mobile browsers.

### ISSUE THREAD

**Issue by vforvaios** [redux-observable/redux-observable#772]
Hi everyone. Recently I am experiencing a problem with a local pet project using react, rtk and redux observables ONLY IN MOBILE BROWSERS (chrome, firefox etc). (desktop browsers are playing nice and easy)

Lets see an example:

**ACTION**
`const someAction = createAction('someAction')`

**COMPONENT**
`.....
const dispatch = useDispatch();
....
<button onClick={() => dispatch(someAction())}
....`

**EPICS**
`const someActionEpic = action$ => action$.pipe(
ofType(someAction.type),
map(.........)
)`

With this example, the epic is not triggered. Its as if the action is dispatched but the epic is not listening.

If I change the rtk setup with the old redux setup, everything is fine!!!!!!!

Is there a limitation for redux-observables regarding action of rtk in mobile????

Thanks in advance

**Comment by jayphelps** [comment]
There are no known issues specific to mobile  or RTK. If you’re able to reproduce it with a fresh project and can share that reproduction I can take a look!

**Comment by vforvaios** [comment]
First of all, you can imagine what an honor is for me when Jay Phelps answers my question!!!! However, it was my fault. 
I had a request happening on a useEffect passing through an epic, but the request failed from the mobile, and then the epics stopped listening. Is this indeed an issue??
