### ISSUE TITLE
RxJS should be marked as a peerDependency

### ISSUE THREAD

**Issue by TimHaboldt** [redux-observable/redux-observable#783]
**What is the current behavior?**

RxJS is marked as a production dependency. 

```json
  "dependencies": {
    "rxjs": "^7.0.0",
    "tslib": "~2.1.0"
  },
```

**What is the expected behavior?**

RxJS should be marked as a peerDependency. 

```json
  "peerDependencies": {
    "rxjs": "^7.0.0",
    "redux": ">=4 <5"
  },
```

**Why is this an issue?**

Not all types of RxJS 7.\*.\* are compatible with each other.
(e.g. RxJS 7.8.0 and RxJS 7.5.5 are not compatible)

Using PNPM in the context of a MonoRepository can lead to other services using a higher version of the RxJS library which can lead to PNPM resolving the RxJS version of redux-observable to a higher version automatically. This leads to a type missmatch.

**Codesnipped that leads to a reproduction:**

```ts
import { AnyAction } from "redux";
import { Epic } from "redux-observable";
import { filter } from "rxjs";
import { createSlice } from "@reduxjs/toolkit";

interface RootState {
    value: string
}

const { actions: someActions } = createSlice({
    name: "app",
    initialState: {},
    reducers: {
        mount: (state) => state,
    },
})

const exampleEpic: Epic<AnyAction, AnyAction, RootState> = ($action) =>
    $action.pipe(
        filter(someActions.mount.match),
    );

```

In this example redux-observable is using RxJS internally. This version of RxJS should match with the locally installed RxJS.

**Sandbox link: https://codesandbox.io/p/sandbox/misty-waterfall-gg3k2z**

**Possible solutions for fixing it manually:**
Update version of RxJS to match the version used in redux-observable
**Issue**: Keeping it up to date is a lot of manual work and could break anytime again in the future.

That is why in our opinion the production dependency RxJS should be a peerDependency instead.

**Comment by evertbouw** [comment]
RxJS is a peer dependency now
