### ISSUE TITLE
Could not find a declaration file for module 'redux-observable' - Typescript project upgrading to 3.0.0-rc.1

### ISSUE THREAD

**Issue by ratoaq2** [redux-observable/redux-observable#791]
I have an angular typescript project which I'm currently upgrading to the latest release candidate.

And all the redux-observable imports are showing this error:
![image](https://github.com/redux-observable/redux-observable/assets/9292886/66131c04-a36c-4649-aaed-5bb76cee43ca)

```
Could not find a declaration file for module 'redux-observable'. 'e:/projects/workspaces/develop/myproject/web/node_modules/redux-observable/dist/cjs/redux-observable.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/redux-observable` if it exists or add a new declaration (.d.ts) file containing `declare module 'redux-observable';`ts(7016)
```

Sorry the newbie question. Am I missing something in the upgrade process?

**Comment by evertbouw** [comment]
Hmm the file is called .d.mts which got picked up in my test project just fine. It should have been a .d.ts file. Will fix

**Comment by evertbouw** [comment]
Just published RC2. Does this resolve the issue?

**Comment by ratoaq2** [comment]
I changed manually that file extension and it worked. I'll update to RC2 as soon as possible and let you know.

Thank you

**Comment by ratoaq2** [comment]
Upgraded to RC2 and it worked. Thanks once again
